### ISSUE TITLE
EKS logging flag only works at cluster creation and does not apply for cluster update

### ISSUE THREAD

**Issue by rytswd** [crossplane-contrib/provider-aws#1014]
### What happened?

I have detailed in [Slack](https://crossplane.slack.com/archives/C01718T2476/p1639442487481800), but as it looks like a bug that's impacting some other users as well, I'm cross-posting it here.

--

I have been trying to control EKS logging flag based on some XR attribute, but when I do update the flag, I get the following error from `eks.aws.crossplane.io/v1beta1/Cluster` resource:

```
CannotUpdateExternalResource: cannot update EKS cluster configuration: InvalidParameterException: Only one type of update can be allowed.
```
 
I don’t think I’m updating multiple items at once - here is the snippet of Composition:

```yaml
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            # ... snipped ...
            logging:
              clusterLogging:
                - enabled: false
                  types:
                    - api
                    # - audit
                    # - authenticator
                    # - controllerManager
                    # - scheduler
      patches:
        - fromFieldPath: spec.parameters.enableLogging
          toFieldPath: spec.forProvider.logging.clusterLogging[0].enabled
        # ... snipped ...
```

When creating a cluster, this setup seems to work fine for both enabled / disabled. But updating the cluster with toggling `spec.parameters.enableLogging` doesn’t seem to work. Is this some known limitation for existing cluster update?

### How can we reproduce it?

1. Create a cluster with `logging.clusterLogging` enabled
2. Update the spec with `logging.clusterLogging` disabled

(or vice versa, both seem to have some update issue.)

### What environment did it happen in?
Crossplane version: v1.5.1
provider-aws: v0.21.2 (I'll test with v0.22.0 in the coming days, but I suspect the same issue persists with it, as I see no release note relating to the cluster setup)
