### ISSUE TITLE
EKS Secrets Encryption cannot be enabled after cluster creation

### ISSUE THREAD

**Issue by jessesuen** [crossplane-contrib/provider-aws#1021]
### What happened?

I had an existing EKS Cluster (with KMS encryption disabled). The Cluster CR was updated to enable encryption by adding a `encryptionConfig` stanza. e.g.:

```yaml
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
...
spec:
  forProvider:
    encryptionConfig:
    - provider:
        keyArn: arn:aws:kms:us-west-2:11111111111111111:key/aaaaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
      resources:
      - secrets
```

After the modification these event warnings started appearing:

`
  Warning  CannotUpdateExternalResource  3m4s (x55 over 58m)  managed/cluster.eks.aws.crossplane.io  cannot update EKS cluster configuration: InvalidParameterException: Cluster is already at the desired configuration with endpointPrivateAccess: true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]
`

And the cluster was Available but not Synced state:

```yaml
status:
...
  conditions:
  - lastTransitionTime: "2021-12-18T05:09:31Z"
    message: 'update failed: cannot update EKS cluster configuration: InvalidParameterException:
      Cluster is already at the desired configuration with endpointPrivateAccess:
      true , endpointPublicAccess: true, and Public Endpoint Restrictions: [0.0.0.0/0]'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2021-12-18T05:09:30Z"
    reason: Available
    status: "True"
    type: Ready
```

Note that if I create the cluster from scratch with `encryptionConfig` set, KMS Secret Encryption will be enabled properly. The problem is similar to https://github.com/crossplane/provider-aws/issues/1014 in that updates to an existing EKS cluster do not work, but will work upon creation.

### How can we reproduce it?

1. Create an EKS Cluster without `encryptionConfig`
2. Add `encryptionConfig` and point to KMS Key ARN

### What environment did it happen in?
Crossplane version: 1.5.1
aws-provider: 0.22
