### ISSUE TITLE
Some resources report tag order being different causing Crossplane to continuously request update

### ISSUE THREAD

**Issue by rytswd** [crossplane-contrib/provider-aws#1081]
### What happened?

For some resources such as RouteTable, having multiple tags with `spec.forProvider.tags` could cause the reconciliation to mistakenly treat the current resource as drifted. It looks as if the tag ordering is taken into consideration when reconciling the current resource state and desired state.

For IAM Role, there is also a separate issue reporting the same diff behaviour. It looks as if IAM Role has some default tags applied by Provider, and that can even be exposed to the same behaviour, causing IAM Role in Composition to be applied over and over again.
https://github.com/crossplane/provider-aws/issues/1072#issuecomment-1018837539

There may be other resources affected as well, for which I simply removed tags or merged into a single tag so that ordering won't matter.

### How can we reproduce it?

Create a composition with a RouteTable field like below

```yaml
    - name: route-table-private
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: us-west-2
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                natGatewayIdSelector:
                  matchControllerRef: true
            associations:
              - subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    zone: us-west-2a
                    access: private
            tags:
              - key: Managed-by
                value: Crossplane
              - key: CrossplaneID
                value: unknown # To be overridden by patching
              - key: Name
                value: unknown # To be overridden by patching
      patches:
        # ... some other patches ...

        # Additional Data
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags[1].value
        - fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.tags[2].value
          transforms:
            - type: string
              string:
                fmt: "%s-private-route-table-2"
```

### What environment did it happen in?
Crossplane version: 1.6.1
Provider AWS version: 0.23.0
