### ISSUE TITLE
Tag changes not getting reflected for dynamodb

### ISSUE THREAD

**Issue by madhureddy08** [crossplane-contrib/provider-aws#1093]
In the initial creation when I tried adding the tags it's getting reflected on AWS console. 
But, When tried to modify or remove the existing tag the changes are been seen in kubernetes side but when checking on the console the changes are not reflecting.

Ran this first & I see its creating the default tags
```
kubectl apply -f - <<EOF
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: sample-table
spec:
  forProvider:
    region: us-east-2
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    keySchema:
      - attributeName: attribute1
        keyType: HASH
    billingMode: PROVISIONED
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    streamSpecification:
      streamEnabled: true
      streamViewType: NEW_AND_OLD_IMAGES
  writeConnectionSecretToRef:
    name: sample-table
    namespace: crossplane-system
EOF
```

Tried to check with this by adding additional tags 

```
kubectl apply -f - <<EOF
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: sample-table
spec:
  forProvider:
    region: us-east-2
    tags:
    - key: testing
      value: "123"
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    keySchema:
      - attributeName: attribute1
        keyType: HASH
    billingMode: PROVISIONED
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
    streamSpecification:
      streamEnabled: true
      streamViewType: NEW_AND_OLD_IMAGES
  writeConnectionSecretToRef:
    name: sample-table
    namespace: crossplane-system
EOF
```
