### ISSUE TITLE
Adding another security group to EC2 instance does not work

### ISSUE THREAD

**Issue by mario-bris** [crossplane-contrib/provider-aws#1100]
### What happened?
I had an instance which had 1 security group attached via `securityGroupRefs`
```
spec:
  forProvider:
    imageId: ami-04505e74c0741db8d
    instanceType: r5ad.2xlarge
    region: us-east-1
    keyName: my_key
    securityGroupRefs:
      - name: aws-infra-ssh
    subnetIdSelector:
...
```
Then I wanted to add 1 more security group and so
```
spec:
  forProvider:
    imageId: ami-04505e74c0741db8d
    instanceType: r5ad.2xlarge
    region: us-east-1
    keyName: my-key
    securityGroupRefs:
      - name: aws-infra-ssh
      - name: aws-infra-k8s
    subnetIdSelector:
...
```
However the security group has not been added to the instance, e.g. `kubectl get -o yaml instance <my_instance>` output
```
spec:
  deletionPolicy: Delete
  forProvider:
    disableAPITermination: false
    ebsOptimized: false
    imageId: ami-04505e74c0741db8d
    instanceInitiatedShutdownBehavior: stop
    instanceType: r5ad.2xlarge
    keyName: my_key
    region: us-east-1
    securityGroupIds:
    - sg-02aeb97d8b9f2a706
    securityGroupRefs:
    - name: aws-infra-ssh
    - name: aws-infra-k8s
  subnetId: subnet-069cd4d687f4dd6b5
```
I see nothing in events or in the description of instance. Seems like the reconciliation did not happen.

Recreating the instance attached both security groups.

### How can we reproduce it?
1. create instance with 1 security group via `securityGroupRefs`
2. attach second security group via `securityGroupRefs`

### What environment did it happen in?
Crossplane version: `crossplane/crossplane:v1.5.1`
aws-provider version: `crossplane/provider-aws-controller:v0.22.0`
