### ISSUE TITLE
route53 resource does not work well with wildcard '*'

### ISSUE THREAD

**Issue by mario-bris** [crossplane-contrib/provider-aws#1115]
### What happened?
I am trying to create CNAME with wildcard so I do not have to explicitly create each route53 entry. E.g. I have DNS entry `myproject.mycompany.com` which is `A` type of record. I'd like to have wildcard DNS records (type of CNAME ) for apps (app1, app2, ...), e.g. `*.myproject.mycompany.com` however when I create such record via `route53.aws.crossplane.io/v1alpha1` and kind `ResourceRecordSet` its state is `READY: False`. The same behaviour is for CNAME and A record.
```
test-dns                                 False   True     *.myproject.mycompany.com   CNAME      11m
```
However DNS entry is create in AWS but It's not deleted when I delete `ResourceRecordSet` resource.

### How can we reproduce it?
You can use following manifest 
```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: 'test-dns'
  annotations:
    crossplane.io/external-name: "*.myproject.mycompany.com"
spec:
  forProvider:
    type: A
    ttl: 300
    zoneId: <zoneId>
    resourceRecords:
    - value: 1.2.3.4
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: crossplane/provider-aws-controller:v0.22.0
Aws provider version: crossplane/crossplane:v1.5.1
