### ISSUE TITLE
Lambda function (container image) update issues, infinite reconciliation loop

### ISSUE THREAD

**Issue by doubliez** [crossplane-contrib/provider-aws#1116]
### What happened?

Updating a container Lambda function in Crossplane doesn't work as expected:
- Updating `code.imageURI` alone doesn't trigger a reconciliation
- Updating another field such as `description` does trigger a reconciliation, but then Crossplane goes into an infinite loop trying to update the function in AWS

### How can we reproduce it?

Use a manifest similar to the following:
```yaml
apiVersion: lambda.aws.crossplane.io/v1alpha1
kind: Function
metadata:
  name: my-function
spec:
  forProvider:
    packageType: Image
    code:
      imageURI: xxxx.dkr.ecr.us-west-2.amazonaws.com/my-function:1.0.0
    description: Some function
    region: us-west-2
    roleRef:
      name: lambda-role
  providerConfigRef:
    name: aws-staging
  deletionPolicy: Orphan
```

Creating the Lambda function works as expected.

Once the function has been synced, update `code.imageURI`, observe that the change is not applied to AWS.

Now change the `description`, observe that the change to `code.imageURI` is then applied successfully but not the change to `description`, and the following errors appear in the events:

```
Warning  CannotUpdateExternalResource  9s (x23 over 16m)  managed/function.lambda.aws.crossplane.io  cannot update Function in AWS: ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-west-2:xxxx:function:my-function
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: ""
  },
  Message_: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-west-2:xxxx:function:my-function",
  Type: "User"
}
```

Crossplane is continuously trying to update the function, even when an update is already in progress, causing a 409 error from the AWS API.

### What environment did it happen in?
Crossplane version: 1.6.1
provider-aws version: 0.23.0

**Comment by worzeel** [comment]
hmm yeah I am also seeing this... is this a known issue still?

I am using provider-aws 0.30.1 and crossplane version 1.9 and seeing the same thing

**Comment by digdiego13** [comment]
Same Problem

**Comment by lukonjun** [comment]
Running into exactly the same Problem. Are there plans for fixing this in upcoming releases @haarchri @muvaf @ngez @hasheddan  @jbw976? Just tagging some main contributors here as this in quite a major issue, as Lambda is a super popular service and it is holding us back from deploying lambdas with crossplane instead of terraform at my company. I see the possibility of using one of AWS Controllers https://aws-controllers-k8s.github.io/community/docs/tutorials/lambda-oci-example/ but I would rather not :D

**Comment by worzeel** [comment]
I did have a working example, but we didn't end up going with crossplane in the end, so I didn't end up looking into it more...  but this did let me update the imageURI and I saw updates...

Maybe someone else can improve it better

https://github.com/worzeel/provider-aws/commit/ad3b66b5f8fed3a5a91db07b6cd6735684386442

**Comment by lukonjun** [comment]
Just to confirm @worzeel, you ended up with a working Lambda example by deploying the fork you shared correct?

**Comment by MisterMX** [comment]
This might be related to #1449 and could be fixed by 1553. @lukonjun @worzeel can you check if that is the case?

**Comment by Lincon-Freitas** [comment]
Just to update the thread here, I tested with the provider version `v0.37.1` and it worked for me. Tested applying first:

```yaml
apiVersion: lambda.aws.crossplane.io/v1alpha1
kind: Function
metadata:
  name: my-function
spec:
  forProvider:
    packageType: Image
    code:
      imageURI: xxx.dkr.ecr.region.amazonaws.com/my-image:v1
    description: Some function
    region: eu-central-1
    role: arn:aws:iam::xxx:role/my-role
  providerConfigRef:
    name: aws-provider
```

And then:

```yaml
apiVersion: lambda.aws.crossplane.io/v1alpha1
kind: Function
metadata:
  name: my-function
spec:
  forProvider:
    packageType: Image
    code:
      imageURI: xxx.dkr.ecr.region.amazonaws.com/my-image:v2
    description: Some function
    region: eu-central-1
    role: arn:aws:iam::xxx:role/my-role
  providerConfigRef:
    name: aws-provider
```
