### ISSUE TITLE
SQS - removing deadLetterQueue configuration not affecting the physical resource

### ISSUE THREAD

**Issue by eliran89c** [crossplane-contrib/provider-aws#1126]
### What happened?
removing the `redrivePolicy` property from an existing resource does not affect the physical resource (nor the synced status)
```yaml
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: test-queue
spec:
  forProvider:
    region: us-east-1
    delaySeconds: 4
    redrivePolicy:
      deadLetterTargetArnRef:
        name: test-queue2
      maxReceiveCount: 1
  providerConfigRef:
    name: example
```

after removing the `redrivePolicy` block the SQS is still configured with the dead letter queue
```
~ kubectl get queues
test-queue    arn:aws:sqs:us-east-1:123456789012:test-queue    True    True     16m
```

### How can we reproduce it?
deploying the [sqs](https://github.com/crossplane/provider-aws/blob/master/examples/sqs/queue.yaml) example, after creation remove the `redrivePolicy` block

### What environment did it happen in?
Crossplane version: `v1.6.1`
Provider version: `v0.23.0`
