### ISSUE TITLE
SQS always tries to SetQueueAttribute

### ISSUE THREAD

**Issue by betoui** [crossplane-contrib/provider-aws#1135]
### What happened?

We are migrating resources to crossplane and are in testing phase. I am currently trying to take control of existing SQS queues without giving `SetQueueAttributes` permissions to make sure everything is mapped properly through our existing templates.

This appears to be working as expected for queues without `policy` declared.

I am not sure I understand this correctly but digging around in the source code  it looks like the string comparison doesn’t take into account ordering or syntax such as spaces between keys and values. Might it make sense to convert both policies into map[string]interface{} and then run the cmp.Equal() function to compare those

### How can we reproduce it?

Given the following permissions:

``` terraform
data "aws_iam_policy_document" "crossplane_provider_aws_sqs" {
  statement {
    actions = [
      "sqs:Get*",
      "sqs:List*",
      "sqs:CreateQueue",
      "sqs:TagQueue",
      "sns:UntagQueue"
    ]
    resources = ["*"]
  }
}
```

What I see in the AWS console policy tab: 

``` JSON 
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "AllowSNSPublish",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sqs:SendMessage",
      "Resource": "<sqs-arn>",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": "<sns-arn>"
        }
      }
```

Crossplane resource (all other attributes match) 

``` yaml 
apiVersion: sqs.aws.crossplane.io/v1beta1
kind: Queue
metadata:
  name: test-sqs
spec:
  deletionPolicy: Orphan
  forProvider:
    delaySeconds: 0
    fifoQueue: false
    maximumMessageSize: 8192
    messageRetentionPeriod: 604800
    policy: |
      {"Version": "2008-10-17", "Statement": [{"Sid": "AllowSNSPublish","Effect": "Allow","Principal": {"AWS": "*"},"Action": "sqs:SendMessage","Resource": "<sqs-arn>","Condition": {"ArnEquals": {"aws:SourceArn": "<sns-arn>"}}}]}
    receiveMessageWaitTimeSeconds: 20
      maxReceiveCount: 4
    region: <your-region>
    visibilityTimeout: 300
  providerConfigRef:
    name: provider-aws-config
```

``` bash
Events:
  Type     Reason                        Age                From                                 Message
  ----     ------                        ----               ----                                 -------
  Warning  CannotUpdateExternalResource  40m (x3 over 51m)  managed/queue.sqs.aws.crossplane.io  failed to update the Queue resource: api error AccessDenied: Access to the resource https://sqs.<region>.amazonaws.com/ is denied.
```
