### ISSUE TITLE
Launch Template tagSpecifications not reported correctly 

### ISSUE THREAD

**Issue by St0rmRage** [crossplane-contrib/provider-aws#1136]
Hi ran into a weird bug in case of tag specifications under launch template in 
**spec.forProvider.launchTemplateData.tagSpecifications**
### What happened?
```
      tagSpecifications:
      - resourceType: Instances
        tags:
        - key: k8s.io/cluster-autoscaler/enabled
          value: "true"
        - key: Name
          value: eks-node-aws_eks_cluster.prod-2
        - key: billing
          value: prod2
```
The expected behavior would be to tag the spawned instances with the launch template although under launch template Tag instance is off. 
Weird part is when I go to edit the template manually (doing sanity checks)  Instances are added but you can also add another tag of Instances (which under AWS it looks like it's the same) but turns out that one enables the instance tagging. 
[https://imgur.com/a/1tSvMT3](url)

Another bug that happens is the EBS mapping of storage but I'll probably report in another bug ticket

### How can we reproduce it?
Just use the code above

### What environment did it happen in?
Crossplane version: v.1.6.2
AWS provider: v0.23.0
EKS 1.21, Bottlerocket AMI
