### ISSUE TITLE
Security Group Not getting ready

### ISSUE THREAD

**Issue by tanujd11** [crossplane-contrib/provider-aws#1138]
### What happened?

The security group with the following condition is not getting into ready state. AWS cloudtrail events are showing multiple authorizeEgress, Revoke Egress query at there end continously. 

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-test
spec:
  deletionPolicy: Delete
  forProvider:
    description: crossplane-test security group
    egress:
    - fromPort: 0
      ipProtocol: "-1"
      ipRanges:
      - cidrIp: 0.0.0.0/0
      toPort: 0
    groupName: crossplane-test
    ingress:
    - fromPort: 0
      ipProtocol: "-1"
      ipRanges:
      - cidrIp: 10.20.0.0/16
      toPort: 65535
    region: us-east-1
    vpcId: vpc-1f64aa64
  providerConfigRef:
    name: load
```
Cloudtrail logs:
```
AuthorizeSecurityGroupEgress | February 10, 2022, 19:25:29 (UTC+05:30) | 1644501327306021172 | ec2.amazonaws.com | AWS::EC2::SecurityGroup | sg-03fda54c10e3290d0
  | RevokeSecurityGroupIngress | February 10, 2022, 19:25:28 (UTC+05:30) | 1644501327306021172 | ec2.amazonaws.com | AWS::EC2::SecurityGroup | sg-03fda54c10e3290d0
  | AuthorizeSecurityGroupIngress | February 10, 2022, 19:25:28 (UTC+05:30) | 1644501327306021172 | ec2.amazonaws.com | AWS::EC2::SecurityGroup | sg-03fda54c10e3290d0
  | RevokeSecurityGroupEgress | February 10, 2022, 19:25:28 (UTC+05:30) | 1644501327306021172 | ec2.amazonaws.com | AWS::EC2::SecurityGroup | sg-03fda54c10e3290d0
 
```

### How can we reproduce it?
Apply the above Yaml file to the k8s cluster

### What environment did it happen in?
Crossplane version: 0.22

**Comment by chlunde** [comment]
From AWS docs for IpProtocol:

> IpProtocol
> The IP protocol name (tcp, udp, icmp, icmpv6) or number (see [Protocol Numbers](http://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml)).
>
> [VPC only] Use -1 to specify all protocols. When authorizing security group rules, specifying -1 or a protocol number other than tcp, udp, icmp, or icmpv6 allows traffic on all ports, regardless of any port range you specify. For tcp, udp, and icmp, you must specify a port range. For icmpv6, the port range is optional; if you omit the port range, traffic for all types and codes is allowed.

So AWS ignores the port numbers you set, and return "nil" as from/to port.

So both omiting them from your yaml, or explicitly writing null in the yaml, should work:

```yaml
    egress:
    - ipProtocol: "-1"
      ipRanges:
      - cidrIp: 0.0.0.0/0
#or...
    ingress:
    - fromPort: null
      ipProtocol: "-1"
      ipRanges:
      - cidrIp: 10.20.0.0/16
      toPort: null
```

**Comment by dipendrachaudhary** [comment]
@haarchri still same issue.
tried with this at first
```
      ingress:
        ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
```
seems same. not ready

tried with this again
```
      ingress:
        - fromPort: null
          toPort: null  
          ipProtocol: "-1"
          ipRanges:
            - cidrIp: 0.0.0.0/0
```
same issue

Here the sample-cluster-sg is first condition and sample-cluster-sg-1 is second condition
```
$ kubectl get securitygroup                                                                                                                                      130 ⨯
NAME                  READY   SYNCED   ID                     VPC                     AGE
sample-cluster-sg     False   True     sg-09baa93eb100a3154   vpc-081266c8a09c7b49f   13m
sample-cluster-sg-1   False   True     sg-00b2441df974b01d9   vpc-081266c8a09c7b49f   9m56s
```

`kubectl describe securitygroup sample-cluster-sg` the first condition without `fromPort` and `toPort`
```
$ kubectl describe securitygroup sample-cluster-sg  
Name:         sample-cluster-sg
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2022-02-24T17:23:23Z
              crossplane.io/external-create-succeeded: 2022-02-24T17:23:26Z
              crossplane.io/external-name: sg-09baa93eb100a3154
API Version:  ec2.aws.crossplane.io/v1beta1
Kind:         SecurityGroup
Metadata:
  Creation Timestamp:  2022-02-24T17:23:23Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  6
  Managed Fields:
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:forProvider:
          .:
          f:description:
          f:egress:
          f:groupName:
          f:region:
          f:tags:
          f:vpcIdRef:
            .:
            f:name:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-24T17:23:36Z
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:ingress:
          f:vpcId:
      f:status:
        .:
        f:atProvider:
          .:
          f:ownerId:
          f:securityGroupID:
        f:conditions:
    Manager:         crossplane-aws-provider
    Operation:       Update
    Time:            2022-02-24T17:23:39Z
  Resource Version:  5634050
  UID:               88f66db7-8471-4989-b297-6b7aeb020f2c
Spec:
  For Provider:
    Description:  Cluster communication with worker nodes
    Egress:
      Ip Protocol:  -1
      Ip Ranges:
        Cidr Ip:  0.0.0.0/0
    Group Name:   my-cool-ekscluster-sg
    Ingress:
      From Port:    22
      Ip Protocol:  tcp
      Ip Ranges:
        Cidr Ip:    0.0.0.0/0
      To Port:      22
      From Port:    22
      Ip Protocol:  -1
      Ip Ranges:
        Cidr Ip:    0.0.0.0/0
      To Port:      22
      From Port:    80
      Ip Protocol:  tcp
      Ip Ranges:
        Cidr Ip:  0.0.0.0/0
      To Port:    80
    Region:       us-east-1
    Tags:
      Key:    Name
      Value:  crossplane-sg
    Vpc Id:   vpc-081266c8a09c7b49f
    Vpc Id Ref:
      Name:  sample-vpc
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Owner Id:           885300287765
    Security Group ID:  sg-09baa93eb100a3154
  Conditions:
    Last Transition Time:  2022-02-24T17:23:23Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-02-24T17:23:26Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type     Reason                       Age                 From                                         Message
  ----     ------                       ----                ----                                         -------
  Normal   CreatedExternalResource      14m                 managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Warning  CannotUpdateManagedResource  14m                 managed/securitygroup.ec2.aws.crossplane.io  Operation cannot be fulfilled on securitygroups.ec2.aws.crossplane.io "sample-cluster-sg": the object has been modified; please apply your changes to the latest version and try again
  Normal   UpdatedExternalResource      17s (x19 over 13m)  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested update of external resource
```
`kubectl describe securitygroup sample-cluster-sg-1` the second condition with `fromPort` and `toPort` set to `null`
```
$ kubectl describe securitygroup sample-cluster-sg-1
Name:         sample-cluster-sg-1
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-failed: 2022-02-24T17:27:16Z
              crossplane.io/external-create-pending: 2022-02-24T17:27:16Z
              crossplane.io/external-create-succeeded: 2022-02-24T17:27:19Z
              crossplane.io/external-name: sg-00b2441df974b01d9
API Version:  ec2.aws.crossplane.io/v1beta1
Kind:         SecurityGroup
Metadata:
  Creation Timestamp:  2022-02-24T17:26:41Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  5
  Managed Fields:
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
      f:spec:
        .:
        f:forProvider:
          .:
          f:description:
          f:egress:
          f:groupName:
          f:region:
          f:tags:
          f:vpcIdRef:
            .:
            f:name:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-24T17:26:41Z
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-create-failed:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:ingress:
          f:vpcId:
      f:status:
        .:
        f:atProvider:
          .:
          f:ownerId:
          f:securityGroupID:
        f:conditions:
    Manager:         crossplane-aws-provider
    Operation:       Update
    Time:            2022-02-24T17:27:20Z
  Resource Version:  5635953
  UID:               5ee9f7e9-509e-4d3a-9d53-560585626d59
Spec:
  For Provider:
    Description:  Cluster communication with worker nodes
    Egress:
      Ip Protocol:  -1
      Ip Ranges:
        Cidr Ip:  0.0.0.0/0
    Group Name:   my-cool-ekscluster-sg-1
    Ingress:
      From Port:    22
      Ip Protocol:  tcp
      Ip Ranges:
        Cidr Ip:    0.0.0.0/0
      To Port:      22
      From Port:    80
      Ip Protocol:  -1
      Ip Ranges:
        Cidr Ip:    0.0.0.0/0
      To Port:      80
      From Port:    80
      Ip Protocol:  tcp
      Ip Ranges:
        Cidr Ip:  0.0.0.0/0
      To Port:    80
    Region:       us-east-1
    Tags:
      Key:    Name
      Value:  crossplane-sg-1
    Vpc Id:   vpc-081266c8a09c7b49f
    Vpc Id Ref:
      Name:  sample-vpc
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Owner Id:           885300287765
    Security Group ID:  sg-00b2441df974b01d9
  Conditions:
    Last Transition Time:  2022-02-24T17:26:41Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-02-24T17:27:19Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type     Reason                        Age                 From                                         Message
  ----     ------                        ----                ----                                         -------
  Warning  CannotUpdateManagedResource   12m                 managed/securitygroup.ec2.aws.crossplane.io  cannot update managed resource: Operation cannot be fulfilled on securitygroups.ec2.aws.crossplane.io "sample-cluster-sg-1": the object has been modified; please apply your changes to the latest version and try again
  Warning  CannotCreateExternalResource  11m (x18 over 12m)  managed/securitygroup.ec2.aws.crossplane.io  failed to create the SecurityGroup resource: InvalidGroup.Duplicate: The security group 'my-cool-ekscluster-sg' already exists for VPC 'vpc-081266c8a09c7b49f'
  Normal   CreatedExternalResource       11m                 managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Normal   UpdatedExternalResource       86s (x14 over 11m)  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested update of external resource
  ```

**Comment by dipendrachaudhary** [comment]
now I only put this and this worked. Seems putting port 80 gave the issue. Why is that? When I again put 80, it is not ready. I dont understand why
 ingress:
```
       - fromPort: 22
         toPort: 22
         ipProtocol: tcp
         ipRanges:
           - cidrIp: 0.0.0.0/0
       - fromPort: null
         toPort: null
         ipProtocol: "-1"
         ipRanges:
           - cidrIp: 0.0.0.0/0
     egress:
       - fromPort: null
         toPort: null
         ipProtocol: "-1"
         ipRanges:
           - cidrIp: 0.0.0.0/0
```
