### ISSUE TITLE
LogGroup: Importing existing log group does not work

### ISSUE THREAD

**Issue by petteja** [crossplane-contrib/provider-aws#1188]
### What happened?
Wanted to take ownership over an existing log group using the crossplane.io/external-name annotation, but Crossplane tries to create a new LogGroup instead. This is failing because the LogGroup already exists.

### How can we reproduce it?
Create a log group manually in AWS called `/not/working`
Create a managed resource in kubernetes with matching logGroupName and external name annotation:
```
apiVersion: cloudwatchlogs.aws.crossplane.io/v1alpha1
kind: LogGroup
metadata:
  annotations:
    crossplane.io/external-name: /not/working
  name: not-working
spec:
  deletionPolicy: Orphan
  forProvider:
    logGroupName: /not/working
    region: eu-north-1
    retentionInDays: 7
  providerConfigRef:
    name: default
```

Will result in:
`create failed: cannot create LogGroup in AWS: ResourceAlreadyExistsException: The specified log group already exists`

### What environment did it happen in?
Crossplane version: v1.6.1
EKS v1.21.9
