### ISSUE TITLE
New Distribution Bugs and Issues

### ISSUE THREAD

**Issue by kferrone** [crossplane-contrib/provider-aws#1210]
### What happened?

On a Distributions CacheBehaviors there are lambdaFunctionAssociations and functionAssociations
The functionAssociations still has quantity on it and did not exist in the previous version 0.24.1. 

I also get this error when making a new Distribution:
```
- lastTransitionTime: '2022-03-14T20:48:24Z'
      message: >
        create failed: cannot create Distribution in AWS: InvalidParameter: 10
        validation error(s) found.

        - missing required field,
        CreateDistributionInput.DistributionConfig.CacheBehaviors.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.CustomErrorResponses.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.DefaultCacheBehavior.ForwardedValues.Headers.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.DefaultCacheBehavior.ForwardedValues.QueryStringCacheKeys.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.DefaultCacheBehavior.LambdaFunctionAssociations.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.DefaultCacheBehavior.TrustedKeyGroups.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.DefaultCacheBehavior.TrustedSigners.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.OriginGroups.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.Origins.Items[0].CustomHeaders.Quantity.

        - missing required field,
        CreateDistributionInput.DistributionConfig.Restrictions.GeoRestriction.Quantity.
      reason: ReconcileError
      status: 'False'
      type: Synced
```

**Comment by haarchri** [comment]
Added a PR for this https://github.com/crossplane/provider-aws/pull/1209

**Comment by kferrone** [comment]
Ok, after some trial and error I discovered anything that has quantity and items can't be empty an empty object.
 e.g. This will tell me quantity is required
```yaml
cacheBehaviors: {}
```

**Comment by haarchri** [comment]
Can you add an example manifest

**Comment by kferrone** [comment]
On another note, I actually saw what can cause the Distribution to infinite loop. Basically it was hiding the quantity errors in the Composition but the distribution was already there so it just kept seeing changes because of that. 

```yaml
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: example-distribution
spec:
  forProvider:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution
      origins:
        items:
          - domainName: supernova-stack.s3.us-east-1.amazonaws.com
            id: s3Origin
            s3OriginConfig:
              originAccessIdentity: origin-access-identity/cloudfront/EBSXJII4DIQVW
      defaultCacheBehavior:
        targetOriginID: s3Origin
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false
      # these will cause quantity errors on create, anythin like this did as well
      cacheBehaviors: {}
      originGroups: {}
  providerConfigRef:
    name: default
  deletionPolicy: Delete
```
