### ISSUE TITLE
Cloudfront Function Resource

### ISSUE THREAD

**Issue by kferrone** [crossplane-contrib/provider-aws#1215]
### What problem are you facing?

After trying to attach a Lambda function to Cloudfront as a Cloudfront function, I realized Lambda and Cloudfront functions have nothing to do with each other. Cloudfront Functions are a totally new resource and they fall under the cloudfront api. These are not something I can create with Crossplane at the moment. 

### How could Crossplane help solve your problem?

Make a new Cloudfront Function resource like so:

```yaml
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Function
metadata:
  name: rewriter
spec:
  forProvider:
    comment:  A lil rewriter
    runtime: cloudfront-js-1.0
    code: |
      function handler(event) {
          var request = event.request;
          if (!/\..+/.test(request.uri)) {
              request.uri = `/index.html`;
          }
          return request;
      }
```
