### ISSUE TITLE
cloudfront oai creation failing with dns resolution error

### ISSUE THREAD

**Issue by rnm212** [crossplane-contrib/provider-aws#1270]
### What happened?

Using v0.24.1 of aws provider and expecting the cloudfront originaccessidentity to be created. Unfortunately the creation fails as the connection fails on dns resolution as regional endpoint is being used for cloudfront.

message: >-
        observe failed: failed to describe CloudFrontOriginAccessIdentity:
        RequestError: send request failed

        caused by: Get
        "https://cloudfront.eu-west-1.amazonaws.com/2020-05-31/origin-access-identity/cloudfront/cf-oai":
        dial tcp: lookup cloudfront.eu-west-1.amazonaws.com on x.x.x.x:53:
        no such host
      reason: ReconcileError
      status: 'False'
      type: Synced

### How can we reproduce it?

Create a test resource definition for cloudfront OAI as below.
```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: CloudFrontOriginAccessIdentity
metadata:
  name: cf-oai
spec:
  providerConfigRef:
    name: testprovider
  forProvider:
    cloudFrontOriginAccessIdentityConfig: 
      comment: test-cf-oai-config
    region: "eu-west-1"
```

### What environment did it happen in?
Crossplane version:  1.4.0
provider version: v.0.24.1
