### ISSUE TITLE
Failed to create IAM Policy

### ISSUE THREAD

**Issue by steve-fraser** [crossplane-contrib/provider-aws#1271]
### What happened?

I tried to create an I am IAM Policy and it produced the following error

```
{"object": {"kind":"Policy","name":"test-policy-crossplane"," │
│ uid":"8957d567-707b-4fc4-8ba8-e8780914ad92","apiVersion":"iam.aws.crossplane.io/v1beta1","resourceVersion":"4059524" │
│ }, "reason": "CannotObserveExternalResource", "message": "failed to update the IAM Policy external-name: operation e │
│ rror STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole │
│ , failed to resolve service endpoint, an AWS region is required, but was not found"}                                 
```

### How can we reproduce it?

```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: test-policy-crossplane
  # annotations:
  #   crossplane.io/external-name: "arn:aws:iam::407967248065:policy/test-crossplane"
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: sti-provider
  forProvider:
    description: "Test policy"
    name: test-crossplane
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "VisualEditor0",
                  "Effect": "Allow",
                  "Action": "s3:ListBucket",
                  "Resource": "*"
              }
          ]
      }     
```
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: sti-provider
spec:
  assumeRole:
    roleARN: "arn:aws:iam::<account-id>:role/testing-role-gitops"
  credentials:
    source: InjectedIdentity
```
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-provider
spec:
  package: crossplane/provider-aws:v0.26.1
  controllerConfigRef:
    name: aws-config
```
### What environment did it happen in?
Crossplane version: Helm chart 1.7.0

* Cloud provider or hardware configuration: EKS
* Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:29:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
EKS
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
