### ISSUE TITLE
KMS Key is ignoring the providerConfigRef role arn

### ISSUE THREAD

**Issue by steve-fraser** [crossplane-contrib/provider-aws#1289]
### What happened?

Crossplane for `Key` in `kms.aws.crossplane.io/v1alpha` seems to be ignoring the 
```
  providerConfigRef:
    name: example-provider
```
```
AccessDeniedE │
│ xception: User: arn:aws:sts::{wrong-account}:assumed-role/crossplane/{SESSION-ID} is not authorized to  │
│ perform: kms:CreateKey on resource: * because no identity-based policy allows the kms:CreateKey action   
```
### How can we reproduce it?

```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example-provider
spec:
  assumeRole:
    externalID: example-crossplane-eks
    roleARN: arn:aws:iam::{account id}:role/crossplane_role
  credentials:
    source: InjectedIdentity
```
```
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: dev-flux
  namespace: default
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: example-provider
```

### What environment did it happen in?
Crossplane version: 
[crossplane/provider-aws@v0.26.1](https://doc.crds.dev/github.com/crossplane/provider-aws@v0.26.1)

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:29:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

EKS
