### ISSUE TITLE
LaunchTemplate ownership not transferrable

### ISSUE THREAD

**Issue by ONordander** [crossplane-contrib/provider-aws#1290]
### What happened?

When trying to take ownership of a previously created LaunchTemplate the provider incorrectly errors out with:
`cannot create LaunchTemplate in AWS: InvalidLaunchTemplateName.AlreadyExistsException: Launch template name already in use.`
Note: only happens when the `LaunchTemplate.metadata.name` doesn't match `LaunchTemplate.spec.forProvider.launchTemplateName`. This happens because `LaunchTemplate.metadata.name` is used as the externalName and added as a LaunchTemplateName together with the actual LaunchTemplateName from `LaunchTemplate.spec.forProvider.launchTemplateName`.

### How can we reproduce it?

```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  name: test-lt-with-different-name
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: example
  forProvider:
    region: eu-central-1
    launchTemplateName: test-lt
    launchTemplateData:
      instanceType: t3.micro
```
```bash
k apply -f launchtemplate.yaml
k delete -f launchtemplate.yaml
k apply -f launchtemplate.yaml
```
