### ISSUE TITLE
S3 Bucket Ready: False after ReconcileSuccess

### ISSUE THREAD

**Issue by lorand-plensys** [crossplane-contrib/provider-aws#1302]
### What happened?

We have a Composition that is aimed to create a AWS S3 Bucket that notifies an AWS SQS Queue. 
All seams fine, but Bucket never gets Ready (False) and the secret created is empty.

As the Bucket cannot be created at once, as it is missing the "queueArn", that will be provided when SQS is up.
So it seams that the Bucket waits until that point (ARN is provided over with status.sqsArn), and then it is 
capable of creating the Bucket with notification. - Looking at the AWS Console, all works fine: bucket created, events
are sent to the SQS. Albeit the Bucket never gets to Ready state and the corresponding created secret is there, but empty.

### How can we reproduce it?

The corresponding part from XR:

````
    - name: sqs
      base:
        apiVersion: sqs.aws.crossplane.io/v1beta1
        kind: Queue
        metadata: {}
        spec:
          forProvider:
            region: eu-central-1
#            policy: ""
          writeConnectionSecretToRef:
            namespace: myproject-dev
            name: myproject-bucket-dev-sqs
      patches:
        - fromFieldPath: spec.bucketName
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-sqs"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "status.atProvider.arn"
          toFieldPath: "status.sqsArn"
          type: ToCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.bucketName"
              - fromFieldPath: "spec.bucketName"
            strategy: string
            string:
              fmt: |
                {
                    "Version": "2012-10-17",
                    "Statement": [
                      { 
                        "Effect": "Allow",
                        "Principal": "*",
                        "Action": "sqs:SendMessage",
                        "Resource": "arn:aws:sqs:*:*:%s-sqs",
                        "Condition": {
                          "ArnEquals": { "aws:SourceArn": "arn:aws:s3:::%s" }
                        }
                      }
                    ]
                }
          toFieldPath: "spec.forProvider.policy"
        - fromFieldPath: metadata.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.bucketName
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-sqs"

    - name: bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata: {}
        spec:
          forProvider:
            locationConstraint: eu-central-1
            acl: private
            notificationConfiguration:
              queueConfigurations:
                - events:
                    - "s3:ObjectCreated:*"
                  filter:
                    key:
                      filterRules:
                        - name: prefix
                          value: job/
                        - name: suffix
                          value: .json
                  queueArn: ""
          writeConnectionSecretToRef:
            namespace: myproject-dev
            name: bucket-endpoint
      patches:
        - fromFieldPath: "spec.trigger-prefix"
          toFieldPath: "spec.forProvider.notificationConfiguration.queueConfigurations[0].filter.key.filterRules[0].value"
        - fromFieldPath: "spec.trigger-suffix"
          toFieldPath: "spec.forProvider.notificationConfiguration.queueConfigurations[0].filter.key.filterRules[1].value"
        - fromFieldPath: "status.sqsArn"
          toFieldPath: "spec.forProvider.notificationConfiguration.queueConfigurations[0].queueArn"
          policy:
            fromFieldPath: Required
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.locationConstraint"
        - fromFieldPath: "metadata.namespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - fromFieldPath: "spec.bucketName"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket"
````

### What environment did it happen in?

Crossplane version: 
- crossplane/crossplane:v1.7.1
- crossplane/provider-aws:v0.26.1

Kubernetes:
- kubectl: v1.23.5
- EKS: v1.22.6-eks-7d68063
