### ISSUE TITLE
Specify default tags for each resource in ProviderConfig

### ISSUE THREAD

**Issue by MisterMX** [crossplane-contrib/provider-aws#1306]
### What problem are you facing?

To achieve a more fine-grained access control we want to tag each of our AWS resources with the ID of the tenant who owns it.

We could achieve this by patching all MRs through Crossplane compositions. However, it is a huge effort and quite complex to patch every resource in all of our compositions of which we have multiple dozens.

It would make things easier if we could set the list of tags to add in each `ProviderConfig` of which we have one per tenant and let the controller handle it.

### How could Crossplane help solve your problem?

1. Add a new field `spec.resource.tags` to `ProviderConfig` where one can specify a set of default tags that are set to every resource:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    # ...
  resource:
    tags:
      tenant: <id>
```

2. Add these tags to the MR during the controllers reconcile.. Maybe `lateInitialize` might be suited for that.
