### ISSUE TITLE
Creating an instance does not become ready in crossplane status

### ISSUE THREAD

**Issue by retr0h** [crossplane-contrib/provider-aws#1326]
### What happened?

Creating an instance does not become ready, however, the instance shows up in aws ec2 console with no apparent issues. 

```
test-instance   False   True     i-029635e6f392703b4           3m32s
```

Reconciler errors with the following:

```
1.6536007898950615e+09	ERROR	controller.managed/instance.ec2.aws.crossplane.io	Reconciler error	
{"reconciler group": "ec2.aws.crossplane.io", "reconciler kind": "Instance", "name": "test-instance", "namespace": "", 
"error": "cannot update managed resource status: Instance.ec2.aws.crossplane.io \"test-instance\" is invalid: 
[status.atProvider.networkInterfaces.association.ipOwnerId: Invalid value: \"null\": 
status.atProvider.networkInterfaces.association.ipOwnerId in body must be of type string: \"null\", 
status.atProvider.networkInterfaces.association.publicDnsName: Invalid value: \"null\": 
status.atProvider.networkInterfaces.association.publicDnsName in body must be of type string: \"null\", 
status.atProvider.networkInterfaces.association.publicIp: Invalid value: \"null\": 
status.atProvider.networkInterfaces.association.publicIp in body must be of type string: \"null\", 
status.atProvider.networkInterfaces.privateIpAddresses.association.ipOwnerId: Invalid value: \"null\": 
status.atProvider.networkInterfaces.privateIpAddresses.association.ipOwnerId in body must be of type string: \"null\", 
status.atProvider.networkInterfaces.privateIpAddresses.association.publicDnsName: Invalid value: \"null\": 
status.atProvider.networkInterfaces.privateIpAddresses.association.publicDnsName in body must be of type string: 
\"null\", status.atProvider.networkInterfaces.privateIpAddresses.association.publicIp: Invalid value: \"null\": 
status.atProvider.networkInterfaces.privateIpAddresses.association.publicIp in body must be of type string: \"null\", 
status.atProvider.capacityReservationSpecification.capacityReservationTarget.capacityReservationId: Invalid value: 
\"null\": status.atProvider.capacityReservationSpecification.capacityReservationTarget.capacityReservationId in body must
be of type string: \"null\"]"}
```

### How can we reproduce it?

```yaml
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: test-vpc
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    region: us-east-1
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
      - key: Name
        value: test-vpc
  providerConfigRef:
    name: aws-provider-config

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: test-subnet
spec:
  forProvider:
    cidrBlock: 192.168.1.0/24
    region: us-east-1
    vpcIdRef:
      name: test-vpc
    tags:
      - key: Name
        value: test-subnet
  providerConfigRef:
    name: aws-provider-config

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: test-sg
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: test-vpc
    groupName: test-sg
    description: Management Network SG
    ingress:
      - fromPort: 22
        toPort: 22
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 0.0.0.0/0
            description: Any
    egress:
      - fromPort: 0
        toPort: 65535
        ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
            description: ALL egress allowed
    tags:
      - key: Name
        value: test-sg
  providerConfigRef:
    name: aws-provider-config

---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: test-instance
spec:
  forProvider:
    region: us-east-1
    imageId: ami-09e67e426f25ce0d7
    instanceType: m5.large
    keyName: cms-bastion
    securityGroupRefs:
      - name: test-sg
    subnetIdRef:
      name: test-subnet
    metadataOptions:
      httpEndpoint: disabled
      httpTokens: optional
      httpPutResponseHopLimit: 1
    tags:
      - key: Name
        value: test-instance
  providerConfigRef:
    name: aws-provider-config

```

Should also be noted the `metadataOptions` above is optional, but if I do not provide it, I receive the following when looking at the `Instance` object status:

```
    - lastTransitionTime: "2022-05-26T21:16:56Z"
      message: 'cannot update Instance custom resource: Instance.ec2.aws.crossplane.io
        test-instance" is invalid: spec.forProvider.metadataOptions: Invalid value:
        null": spec.forProvider.metadataOptions in body must be of type object: "null"'
      reason: ReconcileError
      status: "False"
      type: Synced
```

### What environment did it happen in?
Crossplane version: 

```
aws-provider-866abfbb37fc   1/1     1            1           23m   provider-aws   crossplane/provider-aws-controller:v0.27.0   pkg.crossplane.io/provider=provider-aws,pkg.crossplane.io/revision=aws-provider-866abfbb37fc
crossplane                  1/1     1            1           20d   crossplane     crossplane/crossplane:v1.6.3                 app=crossplane,release=crossplane
crossplane-rbac-manager     1/1     1            1           20d   crossplane     crossplane/crossplane:v1.6.3                 app=crossplane-rbac-manager,release=crossplane
```

Kubectl client v1.22.5
Kubectl server v1.19.16-eks-25803e

Deployed with Terraform via:

```
module "eks_blueprints_kubernetes_addons" {
  source         = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons"
  eks_cluster_id = module.eks.cluster_id

  enable_crossplane = true

  crossplane_aws_provider = {
    enable                   = true
    provider_aws_version     = "v0.26.1"
    additional_irsa_policies = ["arn:aws:iam::aws:policy/AmazonVPCFullAccess", "arn:aws:iam::aws:policy/AmazonEC2FullAccess"]
  }

  depends_on = [module.eks.cluster_id]
}
```
