### ISSUE TITLE
rds.aws.crossplane.io/v1alpha1 - missing parameter AllowMajorVersionUpgrade - cannot upgrade

### ISSUE THREAD

**Issue by afirth** [crossplane-contrib/provider-aws#1330]
### What happened?

When trying to upgrade an RDS instance, receive error that `AllowMajorVersionUpgrade` must be set. However, this option is not present on [dbinstance.rds.aws.crossplane.io](https://doc.crds.dev/github.com/crossplane/provider-aws/rds.aws.crossplane.io/DBInstance/v1alpha1@v0.27.0#spec-forProvider), although it is on [rdsinstance.database.aws.crossplane.io](https://doc.crds.dev/github.com/crossplane/provider-aws/database.aws.crossplane.io/RDSInstance/v1beta1@v0.27.0#spec-forProvider-allowMajorVersionUpgrade). Furthermore, the tests for [clients/rds](https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/clients/rds/rds_test.go#L42) are missing it too.

### How can we reproduce it?

change engineVersion to a new major
```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: redacted
spec:
  deletionPolicy: Orphan
  forProvider:
    engineVersion: "13.4" # <<< CHANGED to 14.2 to trigger error
    applyImmediately: true
    autoMinorVersionUpgrade: true
    autogeneratePassword: false
    availabilityZone: eu-west-1b
    dbInstanceClass: db.t4g.micro
    dbName: redacted
    engine: postgres
    multiAZ: false
    region: eu-west-1
    vpcSecurityGroupIDs:
    - redacted
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    name: db-connection
    namespace: redacted
status:
  atProvider:
    redacted
  conditions:
  - lastTransitionTime: "2022-05-27T18:41:37Z"
    message: "update failed: cannot update DBInstance in AWS: InvalidParameterCombination:
      The AllowMajorVersionUpgrade flag must be present when upgrading to a new major
      version.\n\tstatus code: 400, request id: "
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2022-05-27T18:30:38Z"
    reason: Available
    status: "True"
    type: Ready
```
#### try to edit or deploy
set
``` 
spec:
  forProvider:
    allowMajorVersionUpgrade: true
    engineVersion: "14.2"
```
#### UPDATE ERROR:
```
# * <nil>: Invalid value:
"The edited file failed validation": ValidationError(DBInstance.spec.forProvider):
 unknown field "allowMajorVersionUpgrade" in io.crossplane.aws.rds.v1alpha1.DBInstance.spec.forProvider
```
#### RECONCILER ERROR
```
"update failed: cannot update DBInstance in AWS: InvalidParameterCombination:
      The AllowMajorVersionUpgrade flag must be present when upgrading to a new major
      version
```
### What environment did it happen in?
Crossplane version: 1.8.1
provider aws 0.26
AWS
K8s 1.21
