### ISSUE TITLE
VPCEndpoint is getting "UnauthorizedOperation" if ProviderConfig has "assumeRole" field

### ISSUE THREAD

**Issue by artem-nefedov** [crossplane-contrib/provider-aws#1334]
### What happened?

In our setup, Crossplane AWS provider has an IAM role injected with IRSA (this role only has "sts:AssumeRole" permissions), and then the actual role with administrator permissions is specified in ProviderConfig.

If ProviderConfig contains "assumeRoleARN" field (one that doesn't allow to specify external ID, and is planned for deprecation), it works fine for all resource types.
If instead I specify "assumeRole" field, most of resource types still work, except VPCEndpoint, which is getting "UnauthorizedOperation" error.

Example of config that works (if role doesn't require external ID):

```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: foo
spec:
  assumeRoleARN: arn:aws:iam::<redacted>:role/crossplane-admin
  credentials:
    source: InjectedIdentity
```

Example of setup that doesn't work:

```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: foo
spec:
  assumeRole:
    externalID: foo-bar
    roleARN: arn:aws:iam::<redacted>:role/crossplane-admin
  credentials:
    source: InjectedIdentity
```

### What environment did it happen in?

Crossplane version: helm chart 1.7.0
AWS provider version: v0.27.0 (also tested on master)
