### ISSUE TITLE
Issue adding ONEZONE_IA lifecycle rule to s3 bucket

### ISSUE THREAD

**Issue by thejosephstevens** [crossplane-contrib/provider-aws#1337]
### What happened?
I created an s3 bucket with this lifecycleConfiguration

```
          lifecycleConfiguration:
            rules:
              - status: Enabled
                transition:
                  days: 30
                  storageClass: ONEZONE_IA
```

And I got this error
```
Warning  CannotUpdateExternalResource  29s (x5 over 38s)  managed/bucket.s3.aws.crossplane.io  cannot create or update: api error InvalidRequest: At least one action needs to be specified in a rule
```

### How can we reproduce it?

Create a bucket with this lifecycle rule
```
          lifecycleConfiguration:
            rules:
              - status: Enabled
                transition:
                  days: 30
                  storageClass: ONEZONE_IA
```

### What environment did it happen in?
Crossplane version: 
Crossplane version `1.8.0` (deployed with helm)
Crossplane-aws version `v0.27.0`
EKS 1.21 (AWS)
