### ISSUE TITLE
ResourceRecordSet override problem

### ISSUE THREAD

**Issue by liubog2008** [crossplane-contrib/provider-aws#1343]
### What happened?

If I create two `ResourceRecordSet` with same name but different value, both of them will be synced and available.

### How can we reproduce it?

```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  annotations:
    crossplane.io/external-name: abcdefg.test.com
  name: test-dns-1
spec:
  forProvider:
    type: TXT
    ttl: 300
    resourceRecords:
    - value: "\"aaa\""
    zoneId: xxx
  providerConfigRef:
    name: provider-aws
```

```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  annotations:
    crossplane.io/external-name: abcdefg.test.com
  name: test-dns-1
spec:
  forProvider:
    type: TXT
    ttl: 300
    resourceRecords:
    - value: "\"bbb\""
    zoneId: xxx
  providerConfigRef:
    name: provider-aws

### What environment did it happen in?
Crossplane version: 

<!--
Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider or hardware configuration
* Kubernetes version (use `kubectl version`)
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
* OS (e.g. from /etc/os-release)
* Kernel (e.g. `uname -a`)
-->
