### ISSUE TITLE
Error while creating IAM resources using localstack

### ISSUE THREAD

**Issue by TarasLykhenko** [crossplane-contrib/provider-aws#1375]
### What happened?

We are using LocalStack as a local dev environment. However, we stumbled upon some issue while creating IAM Policies. Other resources like s3 and IAM Roles work correctly.

**Error while creating the resource**
`Cannot observe external resource        {"controller": "managed/policy.iam.aws.crossplane.io", "request": "/somepolicy", "uid": "2e92a9b7-e2fe-4514-94ea-17ed2da8ccad", "version": "1888", "external-name": "", "error": "failed to update the IAM Policy external-name: api error UnknownError: UnknownError", "errorVerbose": "api error UnknownError: UnknownError\nfailed to update the IAM Policy external-name\ngithub.com/crossplane-contrib/provider-aws/pkg/clients.Wrap\n\t/home/runner/work/provider-aws/provider-aws/pkg/clients/aws.go:1239\ngithub.com/crossplane-contrib/provider-aws/pkg/controller/iam/policy.(*external).Observe\n\t/home/runner/work/provider-aws/provider-aws/pkg/controller/iam/policy/controller.go:117\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:767\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/asm_amd64.s:1581"}`

**notes:** 
Adding an annotation to the resource `crossplane.io/external-name:  external-name` lets the resource be created but if then you try to update the policy it gives the same error.

### How can we reproduce it?

Following https://github.com/crossplane/provider-aws/blob/master/examples/providerconfig/localstack.yaml, create the following resources:
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: credentials
      name: crossplane-aws-localstack
      namespace: crossplane
    source: Secret
  endpoint:
    hostnameImmutable: true
    url:
      static: http://localstack:4566
      type: Static
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-aws
spec:
  args:
  - --debug
  env:
  podSecurityContext:
    fsGroup: 2000
  replicas: 1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-aws
spec:
  controllerConfigRef:
    name: crossplane-aws
  ignoreCrossplaneConstraints: false
  package: crossplane/provider-aws:v0.22.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
```

then create a Policy:
```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: somepolicy  
spec:
  forProvider:
    name: external-name
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
  providerConfigRef:
    name: aws-provider
```

then see the failures in the providers logs:

```
Cannot observe external resource        {"controller": "managed/policy.iam.aws.crossplane.io", "request": "/somepolicy", "uid": "2e92a9b7-e2fe-4514-94ea-17ed2da8ccad", "version": "1888", "external-name": "", "error": "failed to update the IAM Policy external-name: api error UnknownError: UnknownError", "errorVerbose": "api error UnknownError: UnknownError\nfailed to update the IAM Policy external-name\ngithub.com/crossplane-contrib/provider-aws/pkg/clients.Wrap\n\t/home/runner/work/provider-aws/provider-aws/pkg/clients/aws.go:1239\ngithub.com/crossplane-contrib/provider-aws/pkg/controller/iam/policy.(*external).Observe\n\t/home/runner/work/provider-aws/provider-aws/pkg/controller/iam/policy/controller.go:117\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:767\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/asm_amd64.s:1581"}
```

### What environment did it happen in?
Crossplane version: 1.8.1
Kubernetes Provider: KIND 1.21.1
provider-aws version: 0.28.1
