### ISSUE TITLE
APIGateway (v1) controllers aren't loaded

### ISSUE THREAD

**Issue by cdloh** [crossplane-contrib/provider-aws#1381]
### What happened?

The controllers for some of the new APIGateway v1 resources added [!1230](https://github.com/crossplane-contrib/provider-aws/pull/1230) isn't loaded.

### How can we reproduce it?

Use provider-aws v0.29 and attempt to use a APIGateway resource like Method and note that it doesn't update or attempt to sync

eg

```
apiVersion: apigateway.aws.crossplane.io/v1alpha1
kind: Method
metadata:
  name: xcp-poc-rest-api-method-faviconss
spec:
  deletionPolicy: Delete
  forProvider:
    apiKeyRequired: false
    authorizationType: NONE
    httpMethod: ANY
    region: us-east-1
    requestParameters: {}
    resourceIdRef:
      name: xcp-poc-rest-api-resource-favicon
    restApiIdRef:
      name: xcp-poc-rest-api
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: provder-aws v0.29
