### ISSUE TITLE
S3 Bucket reconciliation issues when using loggingConfiguration settings

### ISSUE THREAD

**Issue by pauloeliasjr1** [crossplane-contrib/provider-aws#1382]
### What happened?
I am trying to set up a S3 bucket using the default Bucket resource on provider-aws, but I'm getting reconciliation issues while trying to set it up with a loggingConfiguration (to write access logs inside the same bucket). 

It sorts out that when you "enable" logging configuration for a bucket, [AWS automatically writes a bucket policy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html#grant-log-delivery-permissions-bucket-policy) to allow access from AWS logging service principal. This changes expected configuration from Crossplane's perspective and leads to several API calls on PutBucketPolicy and PutBucketLogging events on AWS due reconciliation. 

The resource itself stays stuck:

```
NAME                                  READY   SYNCED   AGE
bucket-loggingconfiguration-testing   False   True     11m
```
We also tried to write a custom bucket policy allowing this permission but to no avail. Other methods such as using a bucket ACL are not recommended by AWS and probably will lead to same situation.

Do you guys have any lead on that? This looks like a fully supported field on docs.

### How can we reproduce it?

Use this sample to deploy a new Bucket. It is the same sample available [here](https://github.com/crossplane-contrib/provider-aws/blob/master/examples/s3/bucket.yaml), but including `loggingConfiguration` parameters.

```yaml
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bucket-loggingconfiguration-testing
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: bucket-loggingconfiguration-testing
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-east-1
    paymentConfiguration:
      payer: BucketOwner
    loggingConfiguration:
      targetPrefix: bucket-loggingconfiguration-testing-
      targetBucket: bucket-loggingconfiguration-testing
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: aws-provider
```

### What environment did it happen in?
* Crossplane version: v1.8.1
* aws-provider: provider-aws-controller:v0.27.1
