### ISSUE TITLE
ReplicationGroup SYNCED = False [cannot modify ElastiCache replication group: at least 1 replica is required]

### ISSUE THREAD

**Issue by nicolasbelanger** [crossplane-contrib/provider-aws#1384]
### What happened?
ReplicationGroup SYNCED = False with error:
```yaml
  conditions:
    - lastTransitionTime: '2022-07-08T00:03:02Z'
      message: >-
        update failed: cannot modify ElastiCache replication group: at least 1
        replica is required
      reason: ReconcileError
      status: 'False'
      type: Synced
```

On a 3 shards + 1 replica per shard cluster.

### How can we reproduce it?
```yaml
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
metadata:
  name: redis-clustered
spec:
  deletionPolicy: Delete
  forProvider:
    applyModificationsImmediately: true
    atRestEncryptionEnabled: true
    authEnabled: true
    automaticFailoverEnabled: true
    cacheNodeType: cache.t2.micro
    cacheParameterGroupName: redis-clustered
    cacheSubnetGroupNameRef:
      name: redis-clustered
    engine: redis
    engineVersion: 6.x
    numNodeGroups: 3
    port: 6379
    region: us-east-1
    replicasPerNodeGroup: 1
    replicationGroupDescription: redis-clustered via Crossplane
    securityGroupIdRefs:
    - name: redis-clustered
    tags:
    - key: Name
      value: redis-clustered
    - key: env
      value: development
    transitEncryptionEnabled: true
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    name: redis-clustered-cache-connection-secret
    namespace: test
```

### What environment did it happen in?
Crossplane version: v1.8.1
* Cloud provider or hardware configuration: AWS
* Kubernetes version (use `kubectl version`): 1.20.11
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS
