### ISSUE TITLE
SecurityGroup stuck in Ready: false

### ISSUE THREAD

**Issue by brian-scb** [crossplane-contrib/provider-aws#1400]
### What happened?

I'm experiencing a problem where setting the `ipProtocol: '-1'` on a `SecurityGroup` causes the resource to never become _Ready_.  There was no error message or event that I could find. It just would not ready.

From the documentation it seems that -1 is valid: "Use -1 to specify all protocols"

YAML to reproduce:

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: db-security-group
spec:
  forProvider:
    description: Enable rds access
    egress:
      - fromPort: 0
        ipProtocol: '-1' # <===========  changing to 'tcp' gets readies instantly
        ipRanges:
          - cidrIp: 0.0.0.0/0
        toPort: 0
    groupName: db-sg
    ingress:
      - fromPort: 5432
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 172.31.0.0/16
        toPort: 5432
    region: ca-central-1
    vpcId: vpc-0xxxx
```

### What environment did it happen in?

Crossplane version:  crossplane/crossplane:v1.9.0
provider-aws: v0.29.0
kubernetes version: 1.22
kubernetes provider: EKS
Kernel: `Linux provider-aws-a2e16ca2fc1a-776769ccbd-jp7v2 5.4.196-108.356.amzn2.x86_64 #1 SMP Thu May 26 12:49:47 UTC 2022 x86_64 Linux`
kubectl version: 
> Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by nabuskey** [comment]
Looks like the issue is with the return value here: https://github.com/crossplane-contrib/provider-aws/blob/99481118b914659ca3b3e392c549ae27190671b3/pkg/clients/ec2/securitygroup_diff.go#L36

The value returned by AWS API in `IpPermission`'s `FromPort` and `ToPort` fields are nil so their corresponding fields in diff objects are set as -1. This does not match what you want, which is 0 for these fields. 
So if you want to allow egress to access anything, you should be able to omit these fields and it should sync. e.g. 
```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: db-security-group
spec:
  forProvider:
    description: Enable rds access
    egress:
      - ipProtocol: '-1' 
        ipRanges:
          - cidrIp: 0.0.0.0/0
    groupName: db-sg
    ingress:
      - fromPort: 5432
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 172.31.0.0/16
        toPort: 5432
    region: ca-central-1
    vpcId: vpc-0xxxx
```
I am not sure if this is the intended configuration specification by this provider though.
