### ISSUE TITLE
Can't reconcile Route53 ResourceRecordSet in AWS China

### ISSUE THREAD

**Issue by artem-nefedov** [crossplane-contrib/provider-aws#1407]
### What happened?

As you may know, AWS China exists in a separate partition, standalone from other AWS regions.
We are trying to work with both AWS global and AWS China from a single control plane with Crossplane.

Important details about the setup:

- The control plane cluster itself is deployed in AWS global (EKS), us-west-2 region.
- ServiceAccount used by Crossplane AWS provider has IRSA annotation, which makes EKS-managed webhook automatically inject credentials into pod, and also inject `AWS_REGION=us-west-2` and `AWS_DEFAULT_REGION=us-west-2` environment variables.
- When managing AWS global resources, we just use InjectedIdentity (which then assumes another role).
- When managing AWS China resources, we use static IAM user (which then assumes another role).

ProviderConfig for AWS global looks like this (it works fine):

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: global
spec:
  assumeRoleARN: arn:aws:iam::00000000000:role/crossplane-admin
  credentials:
    source: InjectedIdentity
```

ProviderConfig for AWS China initially looked like this:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: cn
spec:
  assumeRoleARN: arn:aws-cn:iam::00000000000:role/crossplane-admin
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-cn-creds
      key: credentials
```

This works perfectly fine for region-scoped resources (VPC, Subnet, etc.), probably because endpoint detection based on region works in SDK.

The problems start with global resources (in our case it's Route53). Normally, the solution with AWS SDK would be to specify region anyway, which is generally enough for it to figure out the correct endpoint, but that doesn't seem to work for ResourceRecordSet resource. Note that ResourceRecordSet **does** support `spec.forProvider.region` field, but the docs say it's for "Latency-based resource record sets only", so I'm assuming this field isn't used when creating a session. With that, I would just get `The security token included in the request is invalid.` error.

So, I've changed ProviderConfig to look like this:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: cn
spec:
  endpoint:
    partitionId: aws-cn
    signingRegion: cn-northwest-1
    url:
      type: Dynamic
      dynamic:
        host: amazonaws.com.cn
        protocol: https
  assumeRoleARN: arn:aws-cn:iam::00000000000:role/crossplane-admin
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-cn-creds
      key: credentials
```

And with such configuration, I've got the following error: `observe failed: failed to list the ResourceRecordSet resource: operation error Route 53: ListResourceRecordSets, failed to parse endpoint URL: parse "https://route 53.aws-global.amazonaws.com.cn": invalid character " " in host name`. Two points to note here: 1) There's a space in the URL somehow. 2) Even if there was no space, it would still be incorrect (correct endpoint for R53 in China is `route53.amazonaws.com.cn`).

As a last resort, I've also tried the following ProviderConfig:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: cn
spec:
  endpoint:
    partitionId: aws-cn
    signingRegion: cn-northwest-1
    url:
      type: Static
      static: https://route53.amazonaws.com.cn
  assumeRoleARN: arn:aws-cn:iam::00000000000:role/crossplane-admin
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-cn-creds
      key: credentials
```

Unfortunately, that didn't work either, and I got back to `The security token included in the request is invalid.` errors with such configuration. I figured this is probably because authentication url is still incorrect.

This is where I'm currently stuck at.

From my perspective, the correct solution seems to be to make ResourceRecordSet correctly honor `region` field for all record types, as region-scoped resources show that it works. However, maybe something can be done from ProviderConfig side as well.

### How can we reproduce it?

Use setup described above and try to create ResourceRecordSet. Having IRSA webhook inject env.variables NOT from China partition may possibly be important for reproduction.

### What environment did it happen in?

Crossplane version: Helm chart v1.9.0
AWS provider version: v0.30.0-rc.0.26.gbf45f435
Kubernetes version: 1.22 (EKS)

**Comment by artem-nefedov** [comment]
Looks like #1408 is related

**Comment by haarchri** [comment]
@nabuskey any ideas ?

**Comment by artem-nefedov** [comment]
It looks like the fix from #1408 may help, and I wanna try it asap. But I'm having troubles running local build (even in docker). So I have to wait till the image is available.

**Comment by artem-nefedov** [comment]
So I've tried fix from #1408 (pr #1411, image `v0.30.0-rc.0.38.gf11a1f1c`) with this ProviderConfig:

```yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: cn
spec:
  endpoint:
    partitionId: aws-cn
    signingRegion: cn-northwest-1
    url:
      type: Dynamic
      dynamic:
        host: amazonaws.com.cn
        protocol: https
  assumeRoleARN: arn:aws-cn:iam::00000000000:role/crossplane-admin
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-cn-creds
      key: credentials
```

I no longer see `failed to parse endpoint URL`, so that part works. Unfortunately, it still doesn't authenticate within AWS China, and I get `The security token included in the request is invalid` error (my guess is because of `AWS_REGION` and `AWS_DEFAULT_REGION` env.variables in aws-provider container pointing to us-west-2).

Regional resources (vpc, etc.) that use `region` field still work correctly.
