### ISSUE TITLE
Default tags cause infinite reconcile with compositions

### ISSUE THREAD

**Issue by eloo** [crossplane-contrib/provider-aws#1419]
### What happened?

Since the introduction of default tags (e.g. crossplane-kind) in some resource we see a huge increase (millions) of generations of our MRs.
We have check what is happening and found out that the default tags together with custom set tags in combination with a composition causes reconciles the whole times.

We have investigated the following resources are affected in our case (but i guess all resources with default tags are affected):
- Roles
- Policy
- ReplicationGroup

A workaround here would be to not have `tags` set to custom values..
But we want to use tags :D

Maybe this issue is related to this issues:
- https://github.com/crossplane-contrib/provider-aws/issues/1352
- https://github.com/crossplane-contrib/provider-aws/issues/1412

### How can we reproduce it?
here is the composition and xrd
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: iamrole-composition-test
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: crossplane.test/v1
    kind: XIAMRoleInstanceTest
  resources:
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Role
        metadata:
          name: METADATA_UID
        spec:
          forProvider:
            assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}'
            tags:
              - key: claim-namespace
                value: CLAIM_NAMESPACE_PLACEHOLDER
          providerConfigRef:
            name: aws-provider-config
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.permissionsBoundary
          toFieldPath: spec.forProvider.permissionsBoundary

--- 
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiamrolecompositionstest.crossplane.test
spec:
  group: crossplane.test
  names:
    kind: XIAMRoleInstanceTest
    plural: xiamrolecompositionstest
  claimNames:
    kind: IAMRoleInstanceTest
    plural: iamrolecompositionstest
  defaultCompositionRef: 
    name: iamrole-composition-test
  connectionSecretKeys: []
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  deletionPolicy:
                    type: string
                    description: Deletion policy for the AWS resources
                  awsAccountId:
                    type: string
                    description: Id of the aws account
                  roleName:
                    type: string
                    description: The name of the role to be created in IAM
                  serviceAccountName:
                    type: string
                    description: Service account name for this role
                  oidcProvider:
                    type: string
                    description: Id of our oidc provider
                  permissionsBoundary:
                    type: string
                    description: PermissionsBoundary is the ARN of the policy that is used to set the permissions boundary for the role.
                required:
                - awsAccountId
                - roleName
                - serviceAccountName
                - oidcProvider
                - permissionsBoundary
            required:
            - parameters
```

and then we the MR looping between the following spec.forProvider.Tags
```
...
 forProvider:
    tags:
    - key: claim-namespace
      value: CLAIM_NAMESPACE_PLACEHOLDER

and 
 forProvider:
    tags:
    - key: claim-namespace
      value: CLAIM_NAMESPACE_PLACEHOLDER
    - key: crossplane-kind
      value: role.iam.aws.crossplane.io
    - key: crossplane-name
      value: iamrole-instance-n6xg2-nv9fz
    - key: crossplane-providerconfig
      value: aws-provider-config
```

### What environment did it happen in?
Crossplane version: v1.7.0
Provider version: v0.28.1
