### ISSUE TITLE
Failed to create IAM Role

### ISSUE THREAD

**Issue by ganeshk1928** [crossplane-contrib/provider-aws#1441]
Unable to create IAM role, getting the below error

**_kubectl describe role.iam.aws.crossplane.io crossplane-eks-master-role_**

```
Events:
  Type     Reason                         Age                   From                                Message
  ----     ------                         ----                  ----                                -------
  Warning  CannotObserveExternalResource  32s (x10 over 4m29s)  managed/role.iam.aws.crossplane.io  failed to get Role with name: operation error IAM: GetRole, failed to resolve service endpoint, an AWS region is required, but was not found
```

role.yaml
```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: crossplane-eks-master-role
  labels:
    role.name: crossplane-eks-master-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      - key: Name
        value: crossplane-eks-master-role
  providerConfigRef:
    name: test-customer
```

provider-config.yaml
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: test-customer
spec:
  assumeRole:
    roleARN: "arn:aws:iam::xxxxxxxxxxx:role/test-customer-assume-role"
  credentials:
    source: InjectedIdentity
```

AWS provider version : **crossplane/provider-aws:v0.30.1**

**Comment by haarchri** [comment]
did you use InjectedIdentity with IRSA ?

**Comment by ganeshk1928** [comment]
@haarchri No, I’m using the assumeRole based authentication, and the role I’m using has full IAM access. I was able to create role using aws cli assuming the same role. Also, I’m facing this problem with only IAM resources, other resources like security groups I’m able to create.

**Comment by haarchri** [comment]
InjectedIdentity IS for IRSA or Kube2IAM so you need Credentials first to assumeRole

**Comment by ganeshk1928** [comment]
Normally we can assume a role directly to provision resources in AWS right. Will that not work here the same way. 
Is this `request temporary security credentials` what you are referring to by saying `need Credentials first to assumeRole`, because when I did a `kubectl get sa -n crossplane-system` I got
```
NAME                                   SECRETS   AGE
crossplane                             1         4d22h
crossplane-provider-aws-f72884c6b119   1         10m
default                                1         4d22h
```
and also `kubectl get sa  crossplane-provider-aws-f72884c6b119 -n crossplane-system -o yaml` gave 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-08-22T10:51:50Z"
  name: crossplane-provider-aws-f72884c6b119
  namespace: crossplane-system
  ownerReferences:
  - apiVersion: pkg.crossplane.io/v1
    controller: true
    kind: ProviderRevision
    name: crossplane-provider-aws-f72884c6b119
    uid: 000c1a2f-b7ed-41d7-b897-73474275d4d1
  resourceVersion: "2633524"
  uid: ea8e0709-a8e6-4310-ae6a-a07591a4b491
secrets:
- name: crossplane-provider-aws-f72884c6b119-token-wllkg
```
So i think I’m having the credentials here. If I’m not at all having the credentials I shouldn’t be able to create any other resource too but I’m able to create.

**I’m facing this problem with only IAM resources, other resources like security groups I’m able to create.**

**Comment by haarchri** [comment]
Can you Show me your other providerConfigs ?

**Comment by ganeshk1928** [comment]
I only have one provider config which I shared in the beginning. Sharing it here again.
```
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: test-customer
spec:
  assumeRole:
    roleARN: "arn:aws:iam::xxxxxxxxxxx:role/test-customer-assume-role"
    externalID: "crossplane-aws"
  credentials:
    source: InjectedIdentity
```
`kubectl get providerconfig` gives
```
NAME                                              AGE
providerconfig.aws.crossplane.io/test-customer     4d4h

```
