### ISSUE TITLE
Claim with out of sync EC2 instance incorrectly shows `SYNCED: True`

### ISSUE THREAD

**Issue by spkane** [crossplane-contrib/provider-aws#1448]
### What happened?
I created my first configuration package to do some exploration of Crossplane and its functionality. This configuration package creates a very simple EC2 instance and an IAM user.

I installed the configuration package and then applied a claim, which worked as expected.

The claim allows the user to set the AWS Instance Type. In the initial claim, I set it to `t2.medium`.

I then edited the `claim.yaml` and changed the instanceType parameter to `t2.small` and re-applied it. I expected nothing to change, since this would require Crossplane to destroy the instance, however, I did expect the managed resource to go out of sync, which did not happen.

```
$ kubectl get instance.ec2.aws.crossplane.io/my-userserver-m5ccd-g2b82
NAME                        READY   SYNCED   ID                    STATE     AGE
my-userserver-m5ccd-g2b82   True    True     i-05d49e573792960c7   running   22m

$ kubectl describe instance.ec2.aws.crossplane.io/my-userserver-m5ccd-g2b82 | grep "Instance Type"
    Instance Type:                         t2.small
    Instance Type:      t2.medium
``` 

### How can we reproduce it?

**Configuration Package**

* `definition.yaml`
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xuserservers.example.org
spec:
  group: example.org
  names:
    kind: XUserServer
    plural: xuserservers
  claimNames:
    kind: UserServer
    plural: userservers
  connectionSecretKeys: []
  defaultCompositionRef:
    name: example
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  instanceType:
                    type: string
                  iamPath:
                     type: string
                required:
                - instanceType
            required:
            - parameters
          status:
            type: object
            properties:
              address:
                description: IP address of this cloud instance.
                type: string
```

* `composition.yaml`
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: userserver.example.org
  labels:
    crossplane.io/xrd: xuserservers.example.org
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: XUserServer
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: cloudinstance
    base:
      apiVersion: ec2.aws.crossplane.io/v1alpha1
      kind: Instance
      spec:
        forProvider:
          imageId: "ami-06f29effee622eb00"
          region: "us-west-2"
          instanceType: "t2.micro"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.instanceType
      toFieldPath: spec.forProvider.instanceType
      policy:
        fromFieldPath: Required
    readinessChecks:
    - type: None
  - name: clouduser
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: User
      spec:
        forProvider:
          path: "/"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.iamPath
      toFieldPath: spec.forProvider.path
      policy:
        fromFieldPath: Required
    readinessChecks:
    - type: None
```

* `cat crossplane.yaml`
```yaml
apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: aws-iam-user-and-ec2-instance
  annotations:
    guide: custom
    provider: aws
spec:
  crossplane:
    version: ">=v1.9.0-0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.30.1"
```

**Claims**

* `claim.yaml`
```yaml
apiVersion: example.org/v1alpha1
kind: UserServer
metadata:
  namespace: default
  name: my-userserver
  annotations:
    crossplane.io/external-name: superhero
spec:
  compositionSelector:
    matchLabels:
      crossplane.io/xrd: xuserservers.example.org
      provider: aws
  writeConnectionSecretToRef:
    name: my-user-instance-details
  parameters:
    instanceType: t2.medium
    iamPath: /
```

* `claim-changed.yaml`
```yaml
apiVersion: example.org/v1alpha1
kind: UserServer
metadata:
  namespace: default
  name: my-userserver
  annotations:
    crossplane.io/external-name: superhero
spec:
  compositionSelector:
    matchLabels:
      crossplane.io/xrd: xuserservers.example.org
      provider: aws
  writeConnectionSecretToRef:
    name: my-user-instance-details
  parameters:
    instanceType: t2.small
    iamPath: /test/
```

### What environment did it happen in?

* **Crossplane version**: `crossplane/crossplane:v1.9.0`
* **Crossplane CLI version**:  `v1.9.0`
* **Cloud**: `AWS`
* **K8s Client Version**: `v1.24.4`
* **Kustomize Version**: `v4.5.4`
* **K8s Server Version**: `v1.23.6+k3s1`
* **Kubernetes distribution**: k3s in a colima VM
* **Desktop OS**: `macOS 12.5.1` 
* **VM OS**: `Alpine Linux v3.14`
* **Kernel**: `Linux colima 5.10.109-0-virt #1-Alpine SMP Mon, 28 Mar 2022 11:20:52 +0000 x86_64 Linux`
