### ISSUE TITLE
Changes to EKS NodeGroup LaunchTemplateVersion does not update NodeGroup

### ISSUE THREAD

**Issue by adamjohnson01** [crossplane-contrib/provider-aws#1455]
### What happened?

I created a `LaunchTemplate` and a `LaunchTemplateVersion` and then created a `NodeGroup` and configured it to use the `LaunchTemplateVersion`. When I create a new `LaunchTemplateVersion` and apply the version to the `NodeGroup` I would expect that the `NodeGroup` would update to use the configured version but it does not. The `NodeGroup` status is synced and ready but when I check the AWS console it is still using the previous Version.

### How can we reproduce it?

Create `LaunchTemplate`
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  annotations:
    crossplane.io/external-name: default-us-east-1a
  name: default-us-east-1a
spec:
  deletionPolicy: Delete
  forProvider:
    launchTemplateData:
      imageID: ami-0cca3d8b6715c9f74
      instanceType: m5.xlarge
```

Create `LaunchTemplateVersion`
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplateVersion
metadata:
  name: default-us-east-1a-ami-0cca3d8b6715c9f74
spec:
  deletionPolicy: Delete
  forProvider:
    launchTemplateData:
      imageID: ami-0cca3d8b6715c9f74
      instanceType: m5.xlarge
    launchTemplateName: default-us-east-1a
    launchTemplateNameRef:
      name: default-us-east-1a
    region: us-east-1
```

Create `NodeGroup` using `LaunchTemplateVersion`
```yaml
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: default-us-east-1a
spec:
  deletionPolicy: Delete
  forProvider:
    amiType: CUSTOM
    capacityType: ON_DEMAND
    clusterName: cluster
    launchTemplate:
      name: default-us-east-1a
      nameRef:
        name: default-us-east-1a
      version: "2"
      versionRef:
        name: default-us-east-1a-ami-0cca3d8b6715c9f74
    nodeRole: arn:aws:iam::000000000000:role/role
    region: us-east-1
    releaseVersion: ami-06ce408c7d97c5f2d
    scalingConfig:
      maxSize: 15
      minSize: 1
```

Create new `LaunchTemplateVersion`
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplateVersion
metadata:
  name: default-us-east-1a-ami-0f80e6144aa24f34d
spec:
  deletionPolicy: Delete
  forProvider:
    launchTemplateData:
      imageID: ami-0f80e6144aa24f34d
      instanceType: m5.xlarge
    launchTemplateName: default-us-east-1a
    launchTemplateNameRef:
      name: default-us-east-1a
    region: us-east-1
```

Update `NodeGroup` with new `LaunchTemplateVersion`
```yaml
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: default-us-east-1a
spec:
  deletionPolicy: Delete
  forProvider:
    amiType: CUSTOM
    capacityType: ON_DEMAND
    clusterName: cluster
    launchTemplate:
      name: default-us-east-1a
      nameRef:
        name: default-us-east-1a
      version: "3"
      versionRef:
        name: default-us-east-1a-ami-0f80e6144aa24f34d
    nodeRole: arn:aws:iam::000000000000:role/role
    region: us-east-1
    releaseVersion: ami-06ce408c7d97c5f2d
    scalingConfig:
      maxSize: 15
      minSize: 1
```

### What environment did it happen in?
Crossplane version:  v1.9.0
Kubernetes version: v1.22.10-eks-84b4fe6
