### ISSUE TITLE
Target resource doesn't register with an ALB target type

### ISSUE THREAD

**Issue by erickfaustino** [crossplane-contrib/provider-aws#1458]
### What happened?
Hi, first of all, thank you for the great work!

I'm trying use crossplane to create a TargetGroup that has a Target to an Application Load Balancer. I'm using the Target resource that was introduced in the very last release of the provider.

The problem is: The target doesn't register if the Target type is an ALB

### How can we reproduce it?
- Create a Network LoadBalancer
- Create a TargetGroup
- Create a Listener to the NLB using forwarding the traffic to the previous TargetGroup
- Create a target resource to register an Application Load Balancer as it's target

* I've created these resources:
```
---
apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: LoadBalancer
metadata:
  name: mytest-lb
spec:
  deletionPolicy: Delete
  forProvider:
    ipAddressType: ipv4
    loadBalancerType: network
    region: sa-east-1
    name: mytest-lb
    scheme: internet-facing
    subnetMappings:
      - subnetID: subnet-xxxxxxxxx
      - subnetID: subnet-xxxxxxxxx
      - subnetID: subnet-xxxxxxxxx
  providerConfigRef:
    name: aws-provider
---
apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  name: test-targetgroup
spec:
  forProvider:
    name: test-targetgroup
    port: 80
    protocol: HTTP  #I've tried with TCP too 
    region: sa-east-1
    targetType: alb
    vpcID: "vpc-xxxxxxx"
  providerConfigRef:
    name: aws-provider
---
apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: Listener
metadata:
  name: test-listener
spec:
  forProvider:
    region: sa-east-1
    defaultActions:
      - actionType: forward
        forwardConfig:
          targetGroups:
            - targetGroupArnRef:
                name: test-targetgroup
    loadBalancerArnRef:
      name: mytest-lb
    port: 80
    protocol: TCP
  providerConfigRef:
    name: aws-provider
---
apiVersion: elbv2.aws.crossplane.io/v1alpha1
kind: Target
metadata:
  annotations:
    crossplane.io/external-name: arn:aws:elasticloadbalancing:sa-east-1:xxxxxxxxxxx:loadbalancer/app/xxxx-xxxx-xxxxxx
  name: test-target
spec:
  forProvider:
    region: sa-east-1
    targetGroupArnRef:
      name: test-targetgroup
  providerConfigRef:
    name: aws-provider
```
Whenever I exec `kubectl get target test-target -o yaml` I get this status:
```
status:
  atProvider:
    targetHealth:
      description: Target is not registered to the target group
      reason: Target.NotRegistered
      state: unused
  conditions:
  - lastTransitionTime: "2022-08-30T01:21:48Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2022-08-30T01:21:48Z"
    reason: Unavailable
    status: "False"
    type: Ready
```
The status of the target is:
```
reason: Target.NotRegistered
state: unused
```
At the AWS the target doesn't show up inside of the Target Group

### What environment did it happen in?
Crossplane version: 1.9.1

* Cloud provider: AWS
* Kubernetes version: 1.22
* Kubernetes distribution: EKS
* OS: Amazon Linux 2
* Kernel: `5.4.209-116.363.amzn2.x86_64`
