### ISSUE TITLE
Bi-Directional Patching 

### ISSUE THREAD

**Issue by jcputter** [crossplane-contrib/provider-aws#1473]
### What happened?
I'm trying to create an RDS with a vanity DNS, but it's not working. Docs seem to be vague about it

### How can we reproduce it?
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mariadb
  labels:
    crossplane.io/xrd: xinstances.database.example.org
    provider: aws-provider
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: XDBInstance
  resources:
  - name: rdsinstance
    base:
      apiVersion: database.aws.crossplane.io/v1beta1
      kind: RDSInstance
      spec:
        providerConfigRef:
          name: aws-provider
        forProvider:
          region: eu-west-1
          masterUsername: example
          maxAllocatedStorage: 1
          allowMajorVersionUpgrade: false
          applyModificationsImmediately: true
          autoMinorVersionUpgrade: false
          backupRetentionPeriod: 7
          skipFinalSnapshotBeforeDeletion: true
          dbInstanceClass: xsize
          engine: xenige
          engineVersion: x
          preferredBackupWindow: 02:30-03:00
          preferredMaintenanceWindow: tue:03:30-tue:04:30
    patches:
      - fromFieldPath: RDSInstance.status.atProvider.endpoint.address
        toFieldPath: composite.status.atProvider.endpoint.address
        type: ToCompositeFieldPath
        transforms:
        - type: string
          string:
            fmt: "%s"
  - name: route53record
    base:
      apiVersion: route53.aws.crossplane.io/v1alpha1
      kind: ResourceRecordSet
      metadata:
        name: mydns
        annotations:
          crossplane.io/external-name: mydns.example.org
      spec:
        providerConfigRef:
          name: aws-provider
        forProvider:
          region: eu-west-1
          type: CNAME
          ttl: 60
          zoneId: xxxxxxxx
          zoneIdRef:
            name: example.org
          setIdentifier: "dev"
    patches:
        - fromFieldPath: composite.status.atProvider.endpoint.address
          toFieldPath: ResourceRecordSet.spec.forProvider.resourceRecords[0].value
          type: FromCompositeFieldPath
```

### What environment did it happen in?
Crossplane version: 1.9.0

* Cloud provider: AWS
* Kubernetes version: 1.23
* Kubernetes distribution: EKS
