### ISSUE TITLE
SecurityGroupRule not created

### ISSUE THREAD

**Issue by ONordander** [crossplane-contrib/provider-aws#1479]
### What happened?
Creating a SecurityGroupRule fails with the error:
`Update needs recreation`

The SGR successfully gets an external name, however the SGR doesn't actually exist in AWS.

### How can we reproduce it?
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: new-rule
spec:
  forProvider:
    fromPort: 1024
    toPort: 49151
    region: eu-central-1
    protocol: TCP
    cidrBlock: "0.0.0.0/0"
    description: "Test SGR"
    type: ingress
    securityGroupId: <sg-id>
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 1.9.0
Provider AWS version: 0.30.1
