### ISSUE TITLE
CannotObserveExternalResource on newly-created SecurityGroup

### ISSUE THREAD

**Issue by HarrisonTotty** [crossplane-contrib/provider-aws#1483]
### What happened?

When trying to create a `SecurityGroup` resource with the following contents:

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    crossplane.io/external-name: eks-dev-rds
  name: crossplane-rds
spec:
  deletionPolicy: Delete
  forProvider:
    description: Crossplane RDS Security Group for eks-dev
    groupName: eks-dev-rds
    ingress:
    - fromPort: 5432
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.115.0.0/16
      toPort: 5432
    region: us-west-2
    vpcId: vpc-XXXX
  writeConnectionSecretToRef:
    name: crossplane-rds-sg
    namespace: crossplane-system
```

... after describing the resource I see the following:

```
Warning  CannotObserveExternalResource  5s (x4 over 10s)  managed/securitygroup.ec2.aws.crossplane.io  failed to describe SecurityGroup: api error InvalidGroupId.Malformed: Invalid id: "eks-dev-rds" (expecting "sg-...")
```

This seems to indicate that Crossplane is attempting to reference the group by its name rather than its Id. I've seen other similar tickets ( such as #1316), but none that seem to occur in such a simple usage of the resource. Please let me know if there's any additional info I could provide that could be of use :)

P.S. I should also mention that it doesn't seem like the Security Group is actually created on the AWS side.

### How can we reproduce it?

In theory, simply applying the above resource, replacing `vpcId` with something appropriate should suffice.

### What environment did it happen in?

| Component | Version |
|----------------| ----------|
| Crossplane AWS Provider | 0.31 |
| Crossplane (Helm Chart) | 1.9.0 |
| EKS | 1.22 |

I've already verified that crossplane has appropriate permissions to provision RDS `DBInstance` resources (it has full `*:*` on all AWS resources) so I know it's not a general permissions issue.
