### ISSUE TITLE
Instance Profile doesn't attach roles or tags:

### ISSUE THREAD

**Issue by empath-nirvana** [crossplane-contrib/provider-aws#1493]
### What happened?
I created an instance profile and no roles or tags were attached, even though it says it successfully synced

### How can we reproduce it?

create role and instance profile with role and tags attached to instance profile and it will have neither a role nor tags attached.

```
apiVersion: iam.aws.crossplane.io/v1alpha1
kind: InstanceProfile
metadata:
  name: control-plane-node-profile-prod-use2
spec:
  deletionPolicy: Orphan
  forProvider:
    role: control-plane-node-role-prod-use2
    roleRef:
      name: control-plane-node-role-prod-use2
    tags:
    - key: Name
      value: control-plane-node-role-prod-use2
  providerConfigRef:
    name: control-plane
```

```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: control-plane-node-role-prod-use2
spec:
  deletionPolicy: Orphan
  forProvider:
    assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"ec2.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
    description: Role for Nodes
    maxSessionDuration: 3600
    path: /
    tags:
    - key: Name
      value: control-plane-node-role-prod-use2
  providerConfigRef:
    name: control-plane
```

```
{
    "InstanceProfile": {
        "Path": "/",
        "InstanceProfileName": "control-plane-node-profile-prod-use2",
        "Arn": "arn:aws:iam::<account_number>:instance-profile/control-plane-node-profile-prod-use2",
        "CreateDate": "2022-09-16T17:24:09+00:00",
        "Roles": [],
        "Tags": []
    }
}
```

### What environment did it happen in?
Crossplane version:  crossplane/provider-aws-controller:v0.29.0
eks version 1.23
