### ISSUE TITLE
Log Level - Cannot observe external resource

### ISSUE THREAD

**Issue by clementblaise** [crossplane-contrib/provider-aws#1495]
### What happened?

`Cannot observe external resource` is at Debug log level. I would expect that a problem occurring when observing a resources would be log at an Error level.

In my case there was a JSON formatting error:
```bash
1.6642013886487856e+09	DEBUG	provider-aws	Cannot observe external resource	{"controller": "managed/role.iam.aws.crossplane.io", "request": "/demo-9kjmv", "uid": "d61a1530-a3c8-47be-891b-e819949b42f3", "version": "8123422", "external-name": "demo-9kjmv", "error": "cannot check whether object is up-to-date: malformed AssumeRolePolicyDocument JSON: invalid character '}' looking for beginning of object key string", "errorVerbose": "invalid character '}' looking for beginning of object key string\nmalformed AssumeRolePolicyDocument JSON\...}
```

### How can we reproduce it?

Any patching were JSON cannot be validated properly should triggered the issue, example on a IAM Role

```yaml
- name: provider-aws-iam-role
  base:
    apiVersion: iam.aws.crossplane.io/v1beta1
    kind: Role
    metadata:
      labels:
        role: provider-aws
    spec:
      forProvider:
        assumeRolePolicyDocument: ""
  patches:
    - type: CombineFromComposite
      toFieldPath: spec.forProvider.assumeRolePolicyDocument
      combine:
        variables:
          - fromFieldPath: status.accountId
          - fromFieldPath: status.eks.oidc
          - fromFieldPath: status.eks.oidc
        strategy: string
        string:
          fmt: |
            { not json }
```

### What environment did it happen in?
Crossplane version: 1.9.0
provider-aws version: 0.31.0
