### ISSUE TITLE
SecurityGroupRule not creating when only sourceSecurityGroupId specified 

### ISSUE THREAD

**Issue by clementblaise** [crossplane-contrib/provider-aws#1496]
### What happened?

The SecurityGroupRule resource can take a CIDR or sourceSecurityGroupId as source. When only sourceSecurityGroupId is defined  I am having an error :
```bash
1.6642110888967266e+09	DEBUG	events	Warning	{"object": {"kind":"SecurityGroupRule","name":"demo-cwc4d","uid":"c1798984-1a3a-4690-bb86-1d9b6f2ef146","apiVersion":"ec2.aws.crossplane.io/v1alpha1","resourceVersion":"7421806"}, "reason": "CannotCreateExternalResource", "message": "operation error EC2: AuthorizeSecurityGroupIngress, https response error StatusCode: 400, RequestID: 52c724d2-9224-49a9-b167-12807695cf4a, api error MissingParameter: Missing source specification: include source security group or CIDR information"}
```

### How can we reproduce it?

```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: demo
spec:
  forProvider:
    description: rds
    fromPort: 5432
    protocol: tcp
    region: us-west-2
    securityGroupId: <dbSgId>
    sourceSecurityGroupId: <eksSgID>
    toPort: 5432
    type: ingress
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: demo
    namespace: demo
```

### What environment did it happen in?
Crossplane version: 1.9.0
provider-aws version: 0.31.0
