### ISSUE TITLE
Problem when setting explicit tags for some AWS resources

### ISSUE THREAD

**Issue by Roman-Simik** [crossplane-contrib/provider-aws#1498]
Hey guys, I have recently got into problem or atleast weird functioning of some resources in AWS provider, I will try to explain

### What happened?
When I deploy some AWS resouces (for example: EC2 Address, EC2 Subnet, EC2 VPC), crossplane automatically adds by itself some tags, and that's a problem:

 Why?
 - Because I deploy this resources through argoCD (I have stored the yamls in the Git, and ArgoCD is automatically syncing it and applying, but it will always result in OutOfSync mode, because the desired state will always differ from the deployed yaml (It is explained in How to reproduce below)

PS: This is not happening for other resources like EC2 NatGateway or EC2 Subnet, because on this resources crossplane is not setting another tags by itself

### How can we reproduce it?
You can reproduce it pretty easily

1. Deploy EC2 VPC with some explicit tags set
```
forProvider:
 ...
 tags:
  - key: Name
    value: production-vpc
```
2. In the deployed yaml in k8s you will also see
```
forProvider:
 ...
 tags:
  - key: Name
    value: production-vpc
  - key: crossplane-kind
    value: production-vpc
  - key: crossplane-providerconfig
    value: default
```

- The problem is that ArgoCD wants to have there only single tag, which is defined by me, but this never happens because crossplane will always add there the other tags...
- This is the difference which ArgoCD is always reporting and trying to fix, (it is basically in infinite loop)
![image](https://user-images.githubusercontent.com/41468539/192615320-0783b27e-9a4f-4bdc-b14a-5d0f6e0a1641.png)

### What environment did it happen in?
Crossplane version: 1.9.0 deployed by original Helm Chart
CloudProvider: self hosted on AWS
Kubernetes version: 1.21
