### ISSUE TITLE
Cognito User Pool MFA Configuration 'ON' not working

### ISSUE THREAD

**Issue by abacus3** [crossplane-contrib/provider-aws#1499]
### What happened?

Creating a Cognio User-Pool with `mfaConfiguration` set to `ON` will result in an immediate failure due to SMS configuration being required by AWS as default. Using the https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserPoolMfaConfig.html API action it is possible to enable TOTP/SoftwareToken based MFA and finally set the `mfaConfiguration` to `ON` even after initially issuing the `CreateUserPool` API call.
In general it should be possible to set https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserPoolMfaConfig.html#API_SetUserPoolMfaConfig_RequestSyntax and https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserPoolMfaConfig.html#API_SetUserPoolMfaConfig_RequestSyntax in order to be able to set `mfaConfiguration` to `ON`.

### How can we reproduce it?

```
kubectl apply -f - << EOF
apiVersion: cognitoidentityprovider.aws.crossplane.io/v1alpha1
kind: UserPool
metadata:
  name: user-pool-mfa-bug
spec:
  deletionPolicy: Delete
  forProvider:
    mfaConfiguration: 'ON'
    poolName: user-pool-mfa-bug
    region: us-east-1
  providerConfigRef:
    name: default
EOF
```

### What environment did it happen in?
Crossplane version: v1.9.0
Crossplane provider-aws version: v0.31.0
Kubernetes version: v1.21.14
