### ISSUE TITLE
DocumentDB DBInstance update request without change (causes instance to restart in loop)

### ISSUE THREAD

**Issue by pandrez** [crossplane-contrib/provider-aws#1510]
This issue seems to be very similar to #1348 but for DocumentDB resources

### What happened?

- Deployed a `dbinstance.docdb.aws.crossplane.io` along with a `dbcluster.docdb.aws.crossplane.io`
- Sync is ok for `DBCluster`
```
NAME     READY   SYNCED   EXTERNAL-NAME
db           True       True          db
```
- Sync is ok for `DBInstance`
```
NAME               READY   SYNCED   EXTERNAL-NAME
db-instance0   True    True             db-instance0
```
- Describing the `DBInstance`, we see multiple `UpdatedExternalResource` events  being fired:
```
Events:
  Type    Reason                   Age                From                                        Message
  ----    ------                   ----               ----                                        -------
  Normal  UpdatedExternalResource  3m (x65 over 68m)  managed/dbinstance.docdb.aws.crossplane.io  Successfully requested update of external resource
```

### How can we reproduce it?

- Create a DocDB `DBCluster`
```
apiVersion: docdb.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: db
spec:
  forProvider:
    region: eu-central-1
    engine: "docdb"
    engineVersion: "4.0.0"
    dbSubnetGroupName: "<SUBNETGROUP>"
    vpcSecurityGroupIDs: [ <VPC-SECURITY-GROUP-ID> ]
    storageEncrypted: true
    backupRetentionPeriod: 35
    skipFinalSnapshot: true
    masterUsername: <MASTERUSERNAME>
    masterUserPasswordSecretRef:
      name: <DOCDB-SECRET>
      namespace: <DOCDB-SECRET-NAMESPACE>
      key: master-password
  writeConnectionSecretToRef:
    name: <DOCDB-CONNECTION-SECRET>
    namespace: <DOCDB-CONNECTION-SECRET-NAMESPACE>
  deletionPolicy: Orphan
```

- Create a DocDB `DBInstance`
```
apiVersion: docdb.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: db-instance0
spec:
  forProvider:
    region: eu-central-1
    engine: "docdb"
    dbInstanceClass: "db.t4g.medium"
    dbClusterIdentifierRef:
      name: db
    availabilityZone: eu-central-1a
    preferredMaintenanceWindow: "Mon:00:00-Mon:06:00"
  deletionPolicy: Orphan
```

- On Cloudtrail we can see multiple `ModifyDBInstance`events with the following details:

```
    "eventSource": "rds.amazonaws.com",
    "eventName": "ModifyDBInstance",
    "awsRegion": "eu-central-1",
    "userAgent": "aws-sdk-go/1.42.0 (go1.18.6; linux; amd64) crossplane-provider-aws/v0.32.0",
    "requestParameters": {
        "allowMajorVersionUpgrade": false,
        "cACertificateIdentifier": "rds-ca-2019",
        "dBInstanceIdentifier": "db-instance0",
        "preferredMaintenanceWindow": "Mon:00:00-Mon:06:00",
        "applyImmediately": false,
        "promotionTier": 1,
        "autoMinorVersionUpgrade": true,
        "dBInstanceClass": "db.t4g.medium"
    },
  "responseElements":{
     "storageEncrypted":true,
     "preferredBackupWindow":"00:40-01:10",
     "backupTarget":"region",
     "preferredMaintenanceWindow":"mon:00:00-mon:06:00",
     "backupRetentionPeriod":35,
     "allocatedStorage":1,
     "storageType":"aurora",
     "engineVersion":"4.0.0",
     "dBClusterIdentifier":"db",
     "dbInstancePort":0,
     "associatedRoles":[
        
     ],
     "optionGroupMemberships":[
        {
           "status":"in-sync",
           "optionGroupName":"default:docdb-4-0"
        }
     ],
     "dBParameterGroups":[
        {
           "dBParameterGroupName":"default.docdb4.0",
           "parameterApplyStatus":"in-sync"
        }
     ],
     "instanceCreateTime":"Jul 27, 2022 3:23:51 PM",
     "monitoringInterval":0,
     "dBInstanceClass":"db.t4g.medium",
     "readReplicaDBInstanceIdentifiers":[
        
     ],
     "masterUsername":"ffgadmin",
     "multiAZ":false,
     "autoMinorVersionUpgrade":true,
     "engine":"docdb",
     "httpEndpointEnabled":false,
     "cACertificateIdentifier":"rds-ca-2019",
     "promotionTier":1,
     "deletionProtection":false,
     "endpoint":{
        "address":"https://ddd",
        "port":27017
     },
     "dBSecurityGroups":[
        
     ],
     "pendingModifiedValues":{
        "cACertificateIdentifier":"rds-ca-2019"
     },
     "customerOwnedIpEnabled":false,
     "storageThroughput":0,
     "dBInstanceStatus":"available",
     "publiclyAccessible":false,
     "domainMemberships":[
        
     ],
     "copyTagsToSnapshot":false,
     "dBInstanceIdentifier":"db-instance0",
     "licenseModel":"na",
     "tagList":[
        {
           "value":"default",
           "key":"crossplane-providerconfig"
        },
        {
           "value":"dbinstance.docdb.aws.crossplane.io",
           "key":"crossplane-kind"
        },
        {
           "value":"db-instance0",
           "key":"crossplane-name"
        }
     ]
  }
```

### What environment did it happen in?
Crossplane version: 1.8.1
Provider-aws-controller: v0.32.0

* Cloud provider or hardware configuration: AWS
* Kubernetes version (use `kubectl version`): v1.25.0
* Kubernetes distribution: EKS v1.22.11-eks-18ef993
