### ISSUE TITLE
SecurityGroupRule docs missing ignoreIngress and ignoreEgress hint for using securityGroupId

### ISSUE THREAD

**Issue by BGrasnick** [crossplane-contrib/provider-aws#1516]
### What happened?
When using SecurityGroup and SecurityGroupRule together and appending them directly using securityGroupId in the SecurityGroupRule we observed odd behavior of repeated recreation of SecurityGroupRules. By sheer luck I opened the collapsable on securityGroupIdRef and found out about ignoreIngress and ignoreEgress.

### How can we reproduce it?
Create a SecurityGroup and use it's ID to create a SecurityGroupRule:

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: my-sg
spec:
  forProvider:
    region: eu-central-1
    groupName: my-sg
    vpcId: my-vpc
    description: my description
```

```
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: my-sgr-1
spec:
  forProvider:
    protocol: "-1"
    fromPort: -1
    toPort: -1
    type: ingress
    region: eu-central-1
    securityGroupId: my-sg-id
    sourceSecurityGroupId: my-sg-id
```

When using the following SecurityGroup it does not happen:

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: my-sg
spec:
  forProvider:
    region: eu-central-1
    groupName: my-sg
    vpcId: my-vpc
    description: my description
    ignoreEgress: true
    ignoreIngress: true
```

### What environment did it happen in?
Crossplane version: 1.9.1
Kubernetes version (use `kubectl version`): v1.24.0
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): kind
