### ISSUE TITLE
Cannot use LaunchTemplate + NodeGroup with non-default VPC, own SecurityGroup and own subnets

### ISSUE THREAD

**Issue by BGrasnick** [crossplane-contrib/provider-aws#1519]
### What happened?

We have the following setup in our AWS account:

- a non-default VPC
- three non-default subnets in this VPC

For our crossplane based workload we use the following:

- a composition A to create an EKS cluster and peripherals including a SecurityGroup to be used by NodeGroups
- a composition B for creating an arbitrary number of NodeGroups for this cluster
	- this includes a LaunchTemplate as we need to make some specific settings like volume encryption

We want to use the SecurityGroup created in composition A in the LaunchTemplate in composition B but when we do so, the NodeGroup has problems because of this issue:

https://github.com/aws/aws-sdk/issues/401

In the LaunchTemplate resource we use spec.forProvider.launchTemplateData.securityGroups[0] to give it the name of the SecurityGroup we created in composition A. This however puts the SecurityGroup name in the LaunchTemplate and as we also use our three subnets for the NodeGroup instances can not be started:

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/run-instances.html

option --security-groups:
The names of the security groups. **For a nondefault VPC, you must use security group IDs instead.**

This is not possible with the current LaunchTemplate when we cannot use the ID directly because the resolution from resource name to ID is not implemented.

In provider-jet-aws mapping from SecurityGroup name to ID is implemented using vpcSecurityGroupIdRefs:

https://github.com/crossplane-contrib/provider-jet-aws/blob/main/apis/ec2/v1alpha2/zz_launchtemplate_types.go#L479

### How can we reproduce it?

- create Cluster with custom subnets using spec.forProvider.resourcesVpcConfig.subnetIds
- create SecurityGroup with vpcId of your non-default VPC
- create LaunchTemplate and reference created SecurityGroup with spec.forProvider.launchTemplateData.securityGroups[0]
- create NodeGroup using custom subnets with spec.forProvider.subnets and reference Cluster with spec.forProvider.clusterNameRef.name and LaunchTemplate with spec.forProvider.launchTemplate.nameRef.name

### What environment did it happen in?

Crossplane version: 1.9.1
provider-aws: v0.32.0
Kubernetes version (use `kubectl version`): v1.24.0
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): kind

### Solution ideas

I think it would be necessary to investigate how the resolution from SecurityGroup name to SecurityGroup ID can be done with AWS SDK go and then implement this in the LaunchTemplate controller while introducing a new parameter like vpcSecurityGroupIdRefs in provider-jet-aws.

**Comment by pjanouse** [comment]
I've tried a similar way recently. `SecurityGroup` ID propagation can be solved by other way - you can push the `securityGroupId` to status of your `CompositeResourceDefinition` and then pull it back to your `LaunchTemplate` - see below.

However as you can get your own experience, it doesn't work, at least in provider-aws v0.31.0 either - ID is properly set on the LaunchTemplate object level (check `kubectl describe ....`) however that SecGroup ID *isn't* set on the Amazon side (you can check that via WebUI). This *isn't* unfortunately the only issue I've got and frankly gave up my effort with `SecurityGroup`, `NodeGroup` and `LaunchTemplate` now - using just `NodeGroup` with default template and sec-group (loosing tagging instances feature as well).

What I mean above is:

Cluster composition:
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
spec: 
...
         status: 
            type: object
              sgId: 
                description: SecurityGroup ID
                type: string
```

SecurityGroup:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec: 
  resources: 
  - name: sg-nodepool
    base: 
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: SecurityGroup
...
    patches: 
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.securityGroupID
      toFieldPath: status.sgId
```

LaunchTemplate:
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec: 
  resources: 
  - name: lt-nodegroup
    base: 
      apiVersion: ec2.aws.crossplane.io/v1alpha1
      kind: LaunchTemplate
...
    patches: 
    - type: FromCompositeFieldPath
      fromFieldPath: status.sgId
      toFieldPath: spec.forProvider.launchTemplateData.securityGroupIDs[0]
```
