### ISSUE TITLE
EKS InvalidParameterException: Encryption is already enabled on the cluster

### ISSUE THREAD

**Issue by gmykhailiuta** [crossplane-contrib/provider-aws#1520]
### What happened?
We manage an EKS cluster using crossplane with encryptionConfig defined:
```
forProvider:
  encryptionConfig:
  - provider:
      keyArn: arn:aws:kms:us-west-2:<awsAccountId>:alias/<keyAlias>
    resources:
    - secrets
```
and cluster ends up in degraded state with next error message:
```
update failed: cannot update EKS cluster version: InvalidParameterException:
        Encryption is already enabled on the cluster
```
It looks very similar to https://github.com/hashicorp/terraform-provider-aws/issues/19968.

### How can we reproduce it?
Here's the full spec (had to redact sensitive values):
```
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: test
spec:
  deletionPolicy: Delete
  forProvider:
    encryptionConfig:
    - provider:
        keyArn: arn:aws:kms:us-west-2:<awsAccountId>:alias/<keyAlias>
      resources:
      - secrets
    logging:
      clusterLogging:
      - enabled: true
        types:
        - api
        - audit
        - authenticator
        - controllerManager
        - scheduler
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      publicAccessCidrs:
      - 0.0.0.0/0
      securityGroupIdRefs:
      - name: <securityGroupNameRef>
      securityGroupIds:
      - <seccurityGroupId>
      subnetIdRefs:
      - name: <subnetName>
      subnetIds:
      - <subnetId>
    roleArn: arn:aws:iam::<awsAccountId>:role/<roleName>
    roleArnRef:
      name: <roleName>
    version: "1.23"
  providerConfigRef:
    name: aws-provider
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: test
status:
  atProvider:
    arn: arn:aws:eks:us-west-2:<awsAccountId>:cluster/<name>
    certificateAuthorityData: <redacted>
    createdAt: "2022-09-11T08:01:09Z"
    endpoint: <redacted>
    identity:
      oidc:
        issuer: <redacted>
    platformVersion: eks.2
    resourcesVpcConfig:
      clusterSecurityGroupId: <redacted>
      vpcId: <redacted>
    status: ACTIVE
    version: "1.23"
  conditions:
  - lastTransitionTime: "2022-09-11T08:16:13Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-10-07T15:34:39Z"
    message: 'update failed: cannot update EKS cluster version: InvalidParameterException:
      Encryption is already enabled on the cluster'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### What environment did it happen in?
Crossplane version: 1.9.1
AWS provider: 0.31.0
Kubernetes: v1.23.10-eks-15b7512
