### ISSUE TITLE
Unable to create AWS-Transfer (SFTP) server via crossplane 

### ISSUE THREAD

**Issue by ChaiNikhilShinde** [crossplane-contrib/provider-aws#1532]
Hi, I'm trying to configure AWS Transfer server using Crossplane (provider-aws version-0.23.0). Please find the all details below

1. Server config

```
apiVersion: transfer.aws.crossplane.io/v1alpha1
kind: Server
metadata:
  name: dev-sftp-server-1
  annotations:
    crossplane.io/external-name: dev-sftp-server-1
spec:
  deletionPolicy: Orphan
  forProvider:
    region: ap-southeast-1
    endpointType: public
    loggingRoleRef:
      name: dev-sftp-logging-access-role
    securityPolicyName: TransferSecurityPolicy-2020-06
    tags:
      - key: Name
        value: dev-sftp-server-1
  providerConfigRef:
    name: aws-dev
```

2. Results on creating a server using
```
$ kubectl apply -f sftp-server-test.yaml
server.transfer.aws.crossplane.io/dev-sftp-server-1 created
```
As per log the server is created, but it's not actually created in the AWS.

3. Logs from aws-provider-pod
```
2022-10-18T07:35:14.148Z	DEBUG	provider-aws	Cannot observe external resource	 {
   "controller":"managed/server.transfer.aws.crossplane.io",
   "request":"/dev-sftp-server-1",
   "uid":"149df12d-926e-49c7-a80e-ff593eb468da",
   "version":"219240674",
   "external-name":"dev-sftp-server-1",
   "error":"failed to describe Server: InvalidParameter: 1 validation error(s) found.\n- minimum field size of 19, DescribeServerInput.ServerId.\n",
   "errorVerbose":"InvalidParameter: 1 validation error(s) found.\n- minimum field size of 19, DescribeServerInput.ServerId.\n\nfailed to describe Server\ngithub.com/crossplane/provider-aws/pkg/clients.Wrap\n\t/home/runner/work/provider-aws/provider-aws/pkg/clients/aws.go:978\ngithub.com/crossplane/provider-aws/pkg/controller/transfer/server.(*external).Observe\n\t/home/runner/work/provider-aws/provider-aws/pkg/controller/transfer/server/zz_controller.go:83\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\t/home/runner/work/provider-aws/provider-aws/vendor/github.com/crossplane/crossplane-runtime/pkg/reconciler/managed/reconciler.go:681\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/work/provider-aws/provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.16.13/x64/src/runtime/asm_amd64.s:1371"
}
2022-10-18T07:35:14.149Z	DEBUG	controller-runtime.manager.events	Warning	{
   "object":{
      "kind":"Server",
      "name":"dev-sftp-server-1",
      "uid":"149df12d-926e-49c7-a80e-ff593eb468da",
      "apiVersion":"transfer.aws.crossplane.io/v1alpha1",
      "resourceVersion":"219240674"
   },
   "reason":"CannotObserveExternalResource",
   "message":"failed to describe Server: InvalidParameter: 1 validation error(s) found.\n- minimum field size of 19, DescribeServerInput.ServerId.\n"
}

```

I've followed all closed issues in this repository around the Transfer server setup, this seems to be the new issue. Ple let me know if you need any additional details.

**Comment by haarchri** [comment]
can you upgrade von v0.23 to a later provider ? as minimum to v0.24.1

**Comment by ChaiNikhilShinde** [comment]
@haarchri ... I've updated the version to v0.24.1

Still seeing the following error:

```
Events:
  Type     Reason                         Age               From                                       Message
  ----     ------                         ----              ----                                       -------
  Warning  CannotObserveExternalResource  7s (x6 over 36s)  managed/server.transfer.aws.crossplane.io  failed to describe Server: InvalidParameter: 1 validation error(s) found.
- minimum field size of 19, DescribeServerInput.ServerId.
```

Any suggestions how to fix this?

**Comment by ChaiNikhilShinde** [comment]
@haarchri , here's the spec I'm using to create the server

```
apiVersion: transfer.aws.crossplane.io/v1alpha1
kind: Server
metadata:
  name: dev-sftp-server-1
  annotations:
    # This will be the actual server name
    crossplane.io/external-name: dev-sftp-server-1
spec:
  deletionPolicy: Orphan
  forProvider:
    region: ap-southeast-1
    domain: S3
    endpointDetails:
      securityGroupIDRefs:
        - name: dev-sftp-security-group
      subnetIDRefs:
        - name: dev-eks-public-subnet1
      vpcIDRef:
        name: dev-vpc
    endpointType: PUBLIC
    identityProviderType: SERVICE_MANAGED
    securityPolicyName: TransferSecurityPolicy-2020-06
    protocols:
      - SFTP
    tags:
      - key: Name
        value: dev-sftp-server-1
  writeConnectionSecretToRef:
    name: dev-sftp-secret
    namespace: default
  providerConfigRef:
    name: aws-dev
```

All other AWS resources linked here are already created and present, I'm still seeing the `DescribeServerInput.ServerId` related error, Anything missing in this spec?

**Comment by haarchri** [comment]
Can you remove the external-name ?

**Comment by ChaiNikhilShinde** [comment]
Thanks a lot @haarchri , removing the external name did help. but we are seeing this unexpected error
```
apiVersion: transfer.aws.crossplane.io/v1alpha1
kind: Server
metadata:
  name: dev-sftp-server-1
spec:
  deletionPolicy: Orphan
  forProvider:
    region: ap-southeast-1
    domain: S3
    endpointDetails:
      securityGroupIDRefs:
        - name: dev-sftp-security-group
      subnetIDRefs:
        - name: dev-eks-public-subnet1
      vpcIDRef:
        name: dev-vpc
      addressAllocationIDRefs:
        - name: dev-sftp-eip
    endpointType: VPC
    identityProviderType: SERVICE_MANAGED
    securityPolicyName: TransferSecurityPolicy-2020-06
    protocols:
      - SFTP
    tags:
      - key: Name
        value: dev-sftp-server-1
  writeConnectionSecretToRef:
    name: dev-sftp-secret
    namespace: default
  providerConfigRef:
    name: aws-dev
```

Seeing error while setting `AddressAllocationRefIDs`
```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2022-10-18T16:04:29Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-10-18T16:04:29Z
    Message:               create failed: cannot create Server in AWS: InvalidRequestException: AddressAllocationIds cannot be set in CreateServer
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                        Age                    From                                       Message
  ----     ------                        ----                   ----                                       -------
  Warning  CannotCreateExternalResource  4m33s (x133 over 50m)  managed/server.transfer.aws.crossplane.io  cannot create Server in AWS: InvalidRequestException: AddressAllocationIds cannot be set in CreateServer
```

Seeing the same error incase I don't set the AddressAllocationIds | AddressAllocationRefIDs.

How should we configure this?
