### ISSUE TITLE
The password in the secret Ref are not match with the password from the RDS Instance after restore

### ISSUE THREAD

**Issue by benonich** [crossplane-contrib/provider-aws#1542]
### What happened?

If we restore an RDS instance a new secret will be created with following attributes: "password, username, port, endpoint". The password from the new secrets don't match with the password from the RDS Instance because that has still the old password. So it’s not possible to log in to the RDS Instance with the newly created secrets.

### How can we reproduce it?

First, an RDS instance must be created (postgres). Then a restore must be created from the created rds instance. 
Now the password in the Secret must be checked from the restore instance.  

Here is an example of the configuration: 

```yaml
# Config to create the rds instance
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rds
spec:
  forProvider:
    region:  eu-central-1
    allocatedStorage: 5
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: true
    dbInstanceClass: db.t3.small
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    dbName: postgres
    engine: postgres
    engineVersion: 13.7
    licenseModel: postgresql-license
    masterUsername: admin
    multiAZ: true
    port: 5432
    applyModificationsImmediately: true
    skipFinalSnapshotBeforeDeletion: true
    publiclyAccessible: false
    storageEncrypted: true
    storageType: gp2
    preferredMaintenanceWindow: mon:03:00-mon:04:00
    preferredBackupWindow: 00:00-00:30
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: example-postgres-secrets
---
# Config to create a restore from a rds instance
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rds-restore
spec:
  forProvider:
    region:  eu-central-1
    allocatedStorage: 5
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: true
    dbInstanceClass: db.t3.small
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: postgres
    engineVersion: 13.7
    licenseModel: postgresql-license
    masterUsername: admin
    multiAZ: true
    port: 5432
    restoreFrom:
      pointInTime:
        sourceDBInstanceIdentifier: example-rds
        useLatestRestorableTime: true
      source: PointInTime
    applyModificationsImmediately: true
    skipFinalSnapshotBeforeDeletion: true
    publiclyAccessible: false
    storageEncrypted: true
    storageType: gp2
    preferredMaintenanceWindow: mon:03:00-mon:04:00
    preferredBackupWindow: 00:00-00:30
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: example-postgres-restore-secrets

```

### What environment did it happen in?
Crossplane version: 1.9.0
