### ISSUE TITLE
old connection secret is not deleted on namespace change (insecure?)

### ISSUE THREAD

**Issue by condaatje** [crossplane-contrib/provider-aws#1545]
### What happened?

tried to change the destination of the connection secret (for a few different resource types - eks cluster, rds instance, and ec2 instance)
```
writeConnectionSecretToRef:
    name: example-conn
    # namespace: default
    namespace: crossplane-system
```

the new secret was placed, but the old one was not deleted

### What environment did it happen in?

Crossplane version: 
- all latest (v33)
- fresh crossplane install from stable
