### ISSUE TITLE
Provider unable to assume assigned annotated role

### ISSUE THREAD

**Issue by chandrakanthkannam** [crossplane-contrib/provider-aws#1546]
### What happened?

I have a EKS cluster, which has `ControllerConfig` configured with a IAM role, which has `Trusted entities` configured with permission
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<acc-id>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/<oidc>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/<oidc>:sub": "system:serviceaccount:<namespace>:<sa>"
                }
            }
        }
    ]
}
```
and the `ProviderConfig` with following setting (along with other resources),
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<acc-id>:role/<role-name>
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:v0.32.0
  controllerConfigRef:
    name: aws-config
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
spec:
  credentials:
    source: InjectedIdentity
```
after creating this setup i have tried creating a [Role](https://doc.crds.dev/github.com/crossplane/provider-aws/iam.aws.crossplane.io/Role/v1beta1@v0.33.0), which resulted in this below error

Role:
```
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "",
                "Effect": "Allow",
                "Principal": {
                    "Federated": "arn:aws:iam::<acc-id>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/oidc"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                    "StringEquals": {
                        "oidc.eks.us-east-1.amazonaws.com/id/<oidc>:sub": "system:serviceaccount:<namespace>:<sa>"
                    }
                }
            }
          ]
       }
    tags:
      - key: role
        value: <name>
  providerConfigRef:
    name: aws-provider
metadata:
  name: <name>
  namespace: <namespace>
```

ERR:
```
observe failed: failed to get Role with name: api error AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

can you please assist me here? i'm unable to point what I'm missing here

### What environment did it happen in?
Crossplane version: v1.10.0
Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): EKS, v1.22
