### ISSUE TITLE
Cannot create ECS service managed resource

### ISSUE THREAD

**Issue by AlexXin14** [crossplane-contrib/provider-aws#1548]
### What happened?

Try to create service managed resource.
Error message from describe the service resource. 
```
cannot run refresh: refresh failed: error reading ECS service (arn:aws:ecs:***:***:cluster/example-cluster/sample-service): InvalidParameterException: Unsupported resource type: cluster:
```
### How can we reproduce it?
Deploy service managed resource. 
Example Service YAML file:
```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
  name: sample-service
spec:
  forProvider:
    clusterRef:
      name: example-cluster
    desiredCount: 1
    launchType: FARGATE
    region: ap-southeast-2
    taskDefinition: sampleservice
    enableEcsManagedTags: true
    networkConfiguration:
      - assignPublicIp: true
        securityGroups:
          - "***"
        subnets:
          - "***"
```
Cluster YAML file:
```
apiVersion: ecs.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: example-cluster
  name: example-cluster
spec:
  forProvider:
    region: ap-southeast-2
```

### What environment did it happen in?
Crossplane version: 1.9.1-up.2
AWS provider version: v0.18.0
Kubernetes version:
-   Client Version: v1.25.3
-   Kustomize Version: v4.5.7
-   Server Version: v1.22.2

Kubernetes distribution: Kind (kind v0.11.1 go1.16.4 linux/amd64)
