### ISSUE TITLE
Help understanding how Ref works

### ISSUE THREAD

**Issue by phyzical** [crossplane-contrib/provider-aws#1549]
### What happened?
Im trying to learn crossplane to review the viability to replace some app specific resources out of our terraform infra but im running into issues using Ref attributes for example to make a single composite for a bucket

Below is the composition and definition All these resources are created But the RolePolicyAttachment always complains with `cannot resolve references: mg.Spec.ForProvider.PolicyARN: cannot get referenced resource: Policy.iam.aws.crossplane.io "some-bucket-servicepolicy" not found`

i ran into a similar issue with the role too until i changed it to an explicit name and used the external-name annotation for its creation and using the roleName instead of roleNameRef , but this same approach doesn't seem to fix the issue like it did for the role.

i thought the policyArnRef would reference the name of the MRs name in the resource block? or is this wrong
`crossplane.io/composition-resource-name: some-bucket-servicepolicy`

### How can we reproduce it?
composition
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-aws
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: someorg.com.au/v1alpha1
    kind: XBucket
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: some-bucket
      base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        metadata:
          name: some-bucket
        spec:
          forProvider:
            locationConstraint: "ap-southeast-2" # choose your own region
            acl: private
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            tags:
              created-by: crossplane
          providerConfigRef:
            name: aws-provider-config
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: some-bucket-secrets
      connectionDetails:
        - type: FromConnectionSecretKey
          name: endpoint
          fromConnectionSecretKey: endpoint
    - name: some-bucket-servicepolicy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        metadata:
          name: some-bucket-servicepolicy
          annotations:
            crossplane.io/external-name: arn:aws:iam::123456789:policy/some-bucket-servicepolicy
        spec:
          # TODO: reference the arn from the bucket here
          forProvider:
            name: some-bucket-servicepolicy
            document: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Action": [
                      "s3:*"
                    ],
                    "Effect": "Allow",
                    "Resource": "*"
                  }
                ]
              }
          providerConfigRef:
            name: aws-provider-config
    - name: some-bucket-servicepolicy-attachment
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        metadata:
          name: some-bucket-servicepolicy-attachment
          annotations:
            crossplane.io/external-name: some-bucket-servicepolicy-attachment
        spec:
          forProvider:
            roleName: some-role
            policyArnRef:
              name: some-bucket-servicepolicy
          reclaimPolicy: Delete
          providerConfigRef:
            name: aws-provider-config
```
definition 
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.someorg.com.au
spec:
  connectionSecretKeys:
    - endpoint
  defaultCompositionRef:
    name: bucket-aws
  group: someorg.com.au
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
```
claim
```
apiVersion: someorg.com.au/v1alpha1
kind: Bucket
metadata:
  namespace: development
  name: some-bucket-that-is-unique
spec:
  writeConnectionSecretToRef:
    name: some-bucket-secrets-xrc
```
### What environment did it happen in?
Crossplane version: 1.8.1
provider version: 0.24.1

**Comment by phyzical** [comment]
Looks like i was wrong on how magic it is from this context, but rather its up to you to template it up to be magic, https://github.com/crossplane/crossplane/discussions/2399 this helped me get to a working solution

```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-aws
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: someorg.com.au/v1alpha1
    kind: XBucket
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - base:
        apiVersion: s3.aws.crossplane.io/v1beta1
        kind: Bucket
        spec:
          forProvider:
            locationConstraint: "ap-southeast-2" # choose your own region
            acl: private
            publicAccessBlockConfiguration:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            tags:
              created-by: crossplane
          providerConfigRef:
            name: aws-provider-config
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
        # Write the bucket information to a secret called: {bucket_name}-connection-details
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-connection-details"
      connectionDetails:
        # The resulting secret contains a bucket_name key
        # This key contains the value that was generated by the bucket resource in the endpoint key
        - name: bucket_name
          fromConnectionSecretKey: endpoint
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        spec:
          # TODO: reference the arn from the bucket here
          deletionPolicy: Delete
          writeConnectionSecretToRef:
            namespace: crossplane-system
          forProvider: {}
          providerConfigRef:
            name: aws-provider-config
      patches:
        # We'll use the name defined in the claim/composite resource for the bucket name
        # We suffix it with '-bucket-access-policy'
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket-access-policy"
        # Use the bucket name + the '-bucket-access-policy' suffix
        # This will be the resulting name in aws
        # Each bucket name must be unique, so this in turn will be unique
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket-access-policy"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.description"
          transforms:
            - type: string
              string:
                fmt: "Policy for access to the %s bucket"
        # CombineForComposite works just like the string transforms above
        # Except we can define multiple placeholders in the fmt
        # We need crossplane >= 1.3.0 for this feature
        - type: CombineFromComposite
          toFieldPath: "spec.forProvider.document"
          policy:
            fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: spec.parameters.name
            strategy: string
            # This policy gives a user full access to the bucket and bucket objects
            string:
              fmt: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Action": [
                        "s3:*"
                      ],
                      "Effect": "Allow",
                      "Resource": "arn:aws:s3:::%s"
                    }
                  ]
                }
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-policy-details"
    - base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          deletionPolicy: Delete
          forProvider:
            roleName: some-role
          reclaimPolicy: Delete
          writeConnectionSecretToRef:
            namespace: crossplane-system
          providerConfigRef:
            name: aws-provider-config
      patches:
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "metadata.name"
          transforms:
            - type: string
              string:
                fmt: "%s-user-bucket-policy"
        # Reference the policy we created above
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.forProvider.policyArnRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-bucket-access-policy"
        - fromFieldPath: "spec.parameters.roleName"
          toFieldPath: "spec.forProvider.roleName"
        - fromFieldPath: "spec.parameters.name"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
          transforms:
            - type: string
              string:
                fmt: "%s-role-details"
```
```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.someorg.com.au
spec:
  connectionSecretKeys:
    - bucket_name
  defaultCompositionRef:
    name: bucket-aws
  group: someorg.com.au
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    # The full name of the bucket
                    name:
                      type: string
                    #name of owner role to give access to this bucket
                    roleName:
                      type: string
                  required:
                    - name
                    - roleName
              required:
                - parameters
```

```
apiVersion: someorg.com.au/v1alpha1
kind: Bucket
metadata:
  namespace: development
  name: some-bucket-that-is-unique
spec:
  writeConnectionSecretToRef:
    name: some-bucket-secrets-xrc
  parameters:
    # You would need to change this to something unique
    name: "some-bucket-that-is-unique"
    roleName: "some-role"
```
