### ISSUE TITLE
RDSInstance & masterPasswordSecretRef: missing username & password keys in connection secret

### ISSUE THREAD

**Issue by mateusz-lubanski-sinch** [crossplane-contrib/provider-aws#1571]
### What happened?

After importing existing RDS Instance into crossplane 
- can't change password for RDS master user via `masterPasswordSecretRef`
(very similar functionality is working fine in provider-sql: https://doc.crds.dev/github.com/crossplane-contrib/provider-sql/mysql.sql.crossplane.io/User/v1alpha1@v0.5.0#spec-forProvider-passwordSecretRef)
 - when I import existing RDS Instance into crossplane via XRC with `masterPasswordSecretRef` than connection secret is missing below keys
   - username
   - password

### Expected behaviour 
- crossplane is able to change password for RDS master user via `masterPasswordSecretRef`
- crossplane should populate missing `username` & `password` keys in connection secret after importing existing RDS into crossplane when `masterPasswordSecretRef` is set to current password

#### Can't change password for RDS master user

Create RDS Instance with `deletionPolicy` set to Orphan
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: default-mysql-1
  name: crossplane-poc-mysql-1
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t4g.small
    engine: mysql
  providerConfigRef:
    name: crossplane-provider-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: importtest-rdsinstance
```
Once RDS Instance is fully provisioned (READY=TRUE & STATE==AVAILABLE) delete
`kubectl delete rdsinstances crossplane-poc-mysql-1`
Run `kubectl create` on below code snippet
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-1-master-password
type: Opaque
data:
  password: SW5pdGlhbHQwcFMzY3JFdA==
---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/external-name: default-mysql-1
  name: crossplane-poc-mysql-1
spec:
  deletionPolicy: Orphan
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t4g.small
    engine: mysql
    masterPasswordSecretRef:
      key: password
      name: mysql-1-master-password
      namespace: default
  providerConfigRef:
    name: crossplane-provider-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    name: importtest-rdsinstance
```

#### missing keys in connection secret
Below you can find result for provisioned RDSInstance and missing `username` & `password` keys for its connection secret
(If needed I can post source code for XRD, XRC & Composition)

```
#Secret with password for RDS master user
kubectl get secrets -n crossplane-poc mysql-1-master-password -o json | jq '.data'                                                                                                                                              {
  "password": "SW5pdGlhbHQwcFMzY3JFdA=="
}

#RDSInstance
kubectl get rdsinstances -o json | jq '.items[].spec.forProvider.masterPasswordSecretRef'                                                                                                                                       {
  "key": "password",
  "name": "mysql-1-master-password",
  "namespace": "crossplane-poc"
}
kubectl get rdsinstances -o json | jq '.items[].spec.publishConnectionDetailsTo'                                                                                                                                                {
  "configRef": {
    "name": "default"
  },
  "metadata": {
    "labels": {
      "secret.crossplane.io/owner-uid": "a2a45c4d-de3e-4215-9ee3-4597d9a05d53"
    }
  },
  "name": "38974088-da23-449f-94b8-f4b28315d0a3-rdsinstance"
}

#RDSInstance connection secret
kubectl get secrets -n crossplane-system 38974088-da23-449f-94b8-f4b28315d0a3-rdsinstance -o json | jq '.data'                                                                                                                  {
  "endpoint": "ZGVmYXVsdC1teXNxbC0xLXAyYmNyLmN3b2h2eWw4ejNnYS5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb20=",
  "port": "MzMwNg=="
}
```

### What environment did it happen in?
Crossplane version: `1.9.1`
provider-aws: `v0.30.1`
Kubernetes: `v1.21.14-eks-fb459a0`

### Possible related issues:

- #1542 
- #1121
