### ISSUE TITLE
Some ApiGateway managed resources have no controller registered

### ISSUE THREAD

**Issue by eapri** [crossplane-contrib/provider-aws#1573]
### What happened?
I successfully composed and apigateway.aws.crossplane.io/v1alpha1 Integration resource like this:

```yaml
apiVersion: apigateway.aws.crossplane.io/v1alpha1
kind: Integration
metadata:
  name: a-private-any-intergration
spec:
  forProvider:
    resourceId: some-resource-id
    restApiId: some-rest-api-id
    region: some-region
    connectionType: VPC_LINK
    httpMethod: ANY
    integrationHTTPMethod: ANY    
    type_: HTTP_PROXY
    uri: [https://www.example.com/{proxy}](https://www.example.com/%7Bproxy%7D)
  providerConfigRef:
    name: provider-aws
```

Then I noticed that this resources is not evaluated by a controller. 

When take a look in the File: https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/controller/aws.go only certain apigatewayV1 resources seem to be registered. The following apigatewayV1 resources seem to be missing here: 

- apikey
- authorizer
- basepathmapping
- deployment
- documentationpart
- documentationversion
- domainname
- gatewayresponse
- integration
- integrationresponse
- methodresponse
- model
- requestvalidator
- stage
- usageplan
- usageplankey
- vpclink

ApiGatewayV1 managed resources like RestApi, Resource and Method are evaluated like I expected.

### How can we reproduce it?

Create an apigateway.aws.crossplane.io/v1alpha1 Integration resource like mentioned above.

### What environment did it happen in?
Crossplane version: 

- AWS EKS 1.21
- PROVIDER-AWS V0.31.0
- CROSSPLANE v1.9.1-stable
