### ISSUE TITLE
APIGateway API doesn't update with crossplane

### ISSUE THREAD

**Issue by zalejus** [crossplane-contrib/provider-aws#1581]
### What happened?

I have created API resource (API.apigatewayv2.aws.crossplane.io/v1alpha1) with crossplane. The object was created as I expected. But when I make some changes into the manifest, the changes aren't propagated into AWS.

### How can we reproduce it?

The APIGateway code for creating API
```
apiVersion: apigatewayv2.aws.crossplane.io/v1alpha1
kind: API
metadata:
  name: my-api
  labels:
    name: my-api
spec:
  forProvider:
    region: my-region
    name: my-api
    protocolType: HTTP
    disableExecuteAPIEndpoint: False
  providerConfigRef:
    name: aws-provider
```
And then I would like to change API Endpoint to True:
```
apiVersion: apigatewayv2.aws.crossplane.io/v1alpha1
kind: API
metadata:
  name: my-api
  labels:
    name: my-api
spec:
  forProvider:
    region: my-region
    name: my-api
    protocolType: HTTP
    disableExecuteAPIEndpoint: True
  providerConfigRef:
    name: aws-provider
```
At this point nothing happen. I see in crossplane manifest changed code, but it doesn't sync into AWS. Of course if I delete the object on AWS side, it is created once again properly (with new value - disableExecuteAPIEndpoint: True).
But it should be re-sync automatically, I presume (without deletion).

### What environment did it happen in?
Crossplane version: 1.10.1

Cloud provider:
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0"
  controllerConfigRef:
    name: aws-config
```

EKS kubernetes version: 1.23
