### ISSUE TITLE
Credentials Source Environment -- Bad Request

### ISSUE THREAD

**Issue by rejoshed** [crossplane-contrib/provider-aws#1608]
### What happened?
I configured the crossplane provider-aws to use an environment variable for credentials.

As partially documented here:
https://doc.crds.dev/github.com/crossplane-contrib/provider-aws/aws.crossplane.io/ProviderConfig/v1beta1@v0.34.0#spec-credentials

I formated the environment variable as an ini aws creds file and did not encode the data.

I expected to be able to create an s3 bucket, but I get a BadRequest error.

Unfortunately, I also can't inspect it well because the provider container is so well locked down.

I also posted in the slack: https://crossplane.slack.com/archives/CEG3T90A1/p1671686187670039?thread_ts=1671685171.950729&cid=CEG3T90A1

### How can we reproduce it?
Use the environment source as a credentials file for AWS and try to create a bucket like so...

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-provider-controller-config
  namespace: crossplane-system
spec:
  args: 
    - --debug
  env:
    - name: AWS_INFRA_PLATFORM_DEV2_ADMIN
      value: |
        [default]
        aws_access_key_id=${vault:aws/creds/infra-platform-dev2-admin#access_key}
        aws_secret_access_key=${vault:aws/creds/infra-platform-dev2-admin#secret_key}
        aws_session_token=${vault:aws/creds/infra-platform-dev2-admin#security_token}

  metadata:
    annotations:
      vault.security.banzaicloud.io/vault-addr: <vault addr>
      vault.security.banzaicloud.io/vault-path: k8s-nexus
      vault.security.banzaicloud.io/vault-role: crossplane-operator
      vault.security.banzaicloud.io/vault-skip-verify: "true"
      vault.security.banzaicloud.io/inline-mutation: "true"
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-crossplane-provider
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0
  controllerConfigRef:
    name: aws-provider-controller-config
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  credentials:
    source: Environment
    env:
      name: AWS_INFRA_PLATFORM_DEV2_ADMIN
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: s3-crossplane-demo
spec:
  forProvider:
    acl: private
    locationConstraint: us-west-2
    publicAccessBlockConfiguration:
      blockPublicPolicy: true
    tagging:
      tagSet:
        - key: Name
          value: s3-crossplane-demo
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 
xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0

* Cloud provider or hardware configuration
EKS
* Kubernetes version (use `kubectl version`)
1.21
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift)
EKS
* OS (e.g. from /etc/os-release)
From mac to AWS EKS EC2 os I suppose.
* Kernel (e.g. `uname -a`)
Can ssh to node later if this becomes necessary for troubleshooting.

Thanks!
