### ISSUE TITLE
RolePolicyAttachment constantly removes and re-adds the role name.

### ISSUE THREAD

**Issue by Ezzmo** [crossplane-contrib/provider-aws#1609]
### What happened?

I have a composition in which I create an IAM role, policy and their attachment. Everything creates as intended and is reflected in AWS. Frequently however, the RolePolicyAttachment alternates between ready and not ready. This is because the `roleName` field is being populated and then emptied repeatedly. Honestly this would be fine as the intended functionality is being served. But the real problem is when I want to delete the XR. The IAM resources don't get deleted because the attachment is broken. If I  manually populate the `roleName` with any string then it does delete but the actual attachment in AWS is still there and therefore the role and policy remain. 

### How can we reproduce it?
This is the relevant part of the composition:

```
    - name: Policy
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Policy
        spec:
          forProvider:
            document: <Policy>
          providerConfigRef:
            name: crossplane-provider-config
      patches:
        - fromFieldPath: metadata.labels["crossplane.io/claim-name"]
          toFieldPath: spec.forProvider.name
          type: FromCompositeFieldPath
        - fromFieldPath: status.atProvider.arn
          toFieldPath: spec.policyARN
          type: ToCompositeFieldPath
    - name: Role
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: Role
        spec:
          forProvider:
            assumeRolePolicyDocument: |
              {
                "Version": "2012-10-17",
                "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Service": "lambda.amazonaws.com"
                      },
                      "Action": "sts:AssumeRole"
                    }
                ]
              }
            description: Role for connector execution
          providerConfigRef:
            name: crossplane-provider-config
      patches:
        - fromFieldPath: status.atProvider.arn
          toFieldPath: spec.roleARN
          type: ToCompositeFieldPath
    - name: PolicyRoleAttachment
      base:
        apiVersion: iam.aws.crossplane.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          providerConfigRef:
            name: crossplane-provider-config
      patches:
        - fromFieldPath: spec.roleARN
          toFieldPath: spec.forProvider.roleName
          transforms:
            - string:
                trim: arn:aws:iam::*************:role/
                type: TrimPrefix
              type: string
          type: FromCompositeFieldPath
        - fromFieldPath: spec.policyARN
          toFieldPath: spec.forProvider.policyArn
          type: FromCompositeFieldPath
```

### What environment did it happen in?
Crossplane version: v1.9.1
AWS provider version: 0.32.0
