### ISSUE TITLE
The ec2 instance example code doesnt work

### ISSUE THREAD

**Issue by soumypau1** [crossplane-contrib/provider-aws#1618]
### What happened?
We are trying to deploy an ec2 instance using the example code. While the ec2 instance do get created, the status sync fails. 

### How can we reproduce it?
Create a VPC with code
```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: pes-vpc
  annotations: 
    crossplane.io/external-name: "pes-vpc"
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    cidrBlock: 10.10.20.0/22
    region: us-west-2
    tags:
    - key: name
      value: pes-vpc
```
Create a subnet with code 
```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: pes-subnet
  annotations: 
    crossplane.io/external-name: "pes-subnet"
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    availabilityZone: us-west-2a
    cidrBlock: 10.10.20.0/24
    vpcIdRef:
      name: pes-vpc
    tags:
    - key: name
      value: pes-subnet
```
Then create a security group with following code
```
kind: SecurityGroup
metadata:
  name: pes-sg
spec:
  forProvider:
    region: us-west-2
    vpcIdRef:
      name: pes-vpc  
    groupName: pes-sg
    description: Allow ssh
    # ignoreIngress: true
    # ignoreEgress: true
    ingress:
      - fromPort: 22
        toPort: 22
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/8
  providerConfigRef:
    name: default
```
At this stage we have all the resources ready and synced
```
Soumyadeeps-MacBook-Pro:kubernetes soumyadeep$ kubectl get vpc,subnet,securitygroup
NAME                                READY   SYNCED   ID                      CIDR            IPV6CIDR   AGE
vpc.ec2.aws.crossplane.io/pes-vpc   True    True     vpc-078f3fb3afb3a502c   10.10.20.0/22              10m

NAME                                      READY   SYNCED   ID                         VPC                     CIDR            AGE
subnet.ec2.aws.crossplane.io/pes-subnet   True    True     subnet-09794a794fa1faf48   vpc-078f3fb3afb3a502c   10.10.20.0/24   2m7s

NAME                                         READY   SYNCED   ID                     VPC                     AGE
securitygroup.ec2.aws.crossplane.io/pes-sg   True    True     sg-0e695e2c8a63272d6   vpc-078f3fb3afb3a502c   9m38s

```
And finally create an instance with following code
```
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: sample-instance
spec:
  forProvider:
    region: us-west-2
    imageId: ami-0ceecbb0f30a902a6
    blockDeviceMappings:
     - deviceName: /dev/sdx
       ebs:
         volumeSize: 20
    securityGroupRefs:
      - name: pes-sg
    subnetIdRef:
      name: pes-subnet
  providerConfigRef:
    name: default

```

The instance does get created  But status is not ready 
```
kubectl get instance.ec2.aws.crossplane.io/sample-instance
NAME              READY   SYNCED   ID                    STATE   AGE
sample-instance   False   True     i-0089687e864d2e564           3m

```

There is no error in the description:
```
 kubectl describe  instance.ec2.aws.crossplane.io/sample-instance
Name:         sample-instance
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2022-12-30T08:41:38Z
              crossplane.io/external-create-succeeded: 2022-12-30T08:41:40Z
              crossplane.io/external-name: i-0089687e864d2e564
API Version:  ec2.aws.crossplane.io/v1alpha1
Kind:         Instance
Metadata:
  Creation Timestamp:  2022-12-30T08:41:38Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  4
  Managed Fields:
    API Version:  ec2.aws.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:blockDeviceMappings:
          f:imageId:
          f:region:
          f:securityGroupRefs:
          f:subnetIdRef:
            .:
            f:name:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-create
    Operation:    Update
    Time:         2022-12-30T08:41:38Z
    API Version:  ec2.aws.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:atProvider:
          .:
          f:architecture:
          f:hypervisor:
          f:instanceLifecyle:
          f:instanceType:
          f:platform:
          f:rootDeviceType:
          f:state:
          f:virualizationType:
        f:conditions:
    Manager:      crossplane-aws-provider
    Operation:    Update
    Subresource:  status
    Time:         2022-12-30T08:41:40Z
    API Version:  ec2.aws.crossplane.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:disableAPITermination:
          f:ebsOptimized:
          f:instanceInitiatedShutdownBehavior:
          f:instanceType:
          f:securityGroupIds:
          f:subnetId:
          f:tags:
    Manager:         crossplane-aws-provider
    Operation:       Update
    Time:            2022-12-30T08:41:43Z
  Resource Version:  375606
  UID:               7cb324ac-5c7f-4118-a7e8-9f6365bef0d1
Spec:
  Deletion Policy:  Delete
  For Provider:
    Block Device Mappings:
      Device Name:  /dev/sdx
      Ebs:
        Volume Size:                       20
    Disable API Termination:               false
    Ebs Optimized:                         false
    Image Id:                              ami-0ceecbb0f30a902a6
    Instance Initiated Shutdown Behavior:  stop
    Instance Type:                         m1.small
    Region:                                us-west-2
    Security Group Ids:
      sg-0e695e2c8a63272d6
    Security Group Refs:
      Name:     pes-sg
    Subnet Id:  subnet-09794a794fa1faf48
    Subnet Id Ref:
      Name:  pes-subnet
    Tags:
      Key:    crossplane-kind
      Value:  instance.ec2.aws.crossplane.io
      Key:    crossplane-name
      Value:  sample-instance
      Key:    crossplane-providerconfig
      Value:  default
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Architecture:        
    Hypervisor:          
    Instance Lifecyle:   
    Instance Type:       
    Platform:            
    Root Device Type:    
    State:               
    Virualization Type:  
  Conditions:
    Last Transition Time:  2022-12-30T08:41:40Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-12-30T08:41:40Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
Events:
  Type    Reason                   Age   From                                    Message
  ----    ------                   ----  ----                                    -------
  Normal  CreatedExternalResource  4m3s  managed/instance.ec2.aws.crossplane.io  Successfully requested creation of external resource

```

We see the following error in provider debug log

```
1.6723899712874196e+09	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/vpc.ec2.aws.crossplane.io", "request": "/pes-vpc", "uid": "3a10a580-104a-4acc-aea3-78abbe55042c", "version": "374449", "external-name": "vpc-078f3fb3afb3a502c", "requeue-after": 1672390031.2874165}
1.6723900012858248e+09	DEBUG	provider-aws	Reconciling	{"controller": "managed/securitygroup.ec2.aws.crossplane.io", "request": "/pes-sg"}
1.6723900019804435e+09	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/securitygroup.ec2.aws.crossplane.io", "request": "/pes-sg", "uid": "f261f774-22fb-43e7-a8d0-6381aafa2890", "version": "374535", "external-name": "sg-0e695e2c8a63272d6", "requeue-after": 1672390061.9804397}
1.6723900257091024e+09	DEBUG	provider-aws	Reconciling	{"controller": "managed/subnet.ec2.aws.crossplane.io", "request": "/pes-subnet"}
1.672390026454314e+09	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/subnet.ec2.aws.crossplane.io", "request": "/pes-subnet", "uid": "4c1f4446-ed66-494d-bfbb-e4dc8e82e313", "version": "375640", "external-name": "subnet-09794a794fa1faf48", "requeue-after": 1672390086.4543095}
1.6723900312655125e+09	DEBUG	provider-aws	Reconciling	{"controller": "managed/instance.ec2.aws.crossplane.io", "request": "/sample-instance"}
1.6723900313066685e+09	DEBUG	provider-aws	Reconciling	{"controller": "managed/vpc.ec2.aws.crossplane.io", "request": "/pes-vpc"}
1.6723900324417586e+09	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/vpc.ec2.aws.crossplane.io", "request": "/pes-vpc", "uid": "3a10a580-104a-4acc-aea3-78abbe55042c", "version": "374449", "external-name": "vpc-078f3fb3afb3a502c", "requeue-after": 1672390092.4417543}
1.6723900336932411e+09	DEBUG	provider-aws	External resource is up to date	{"controller": "managed/instance.ec2.aws.crossplane.io", "request": "/sample-instance", "uid": "7cb324ac-5c7f-4118-a7e8-9f6365bef0d1", "version": "375606", "external-name": "i-0089687e864d2e564", "requeue-after": 1672390093.6932368}
1.6723900337155874e+09	ERROR	controller.managed/instance.ec2.aws.crossplane.io	Reconciler error	{"reconciler group": "ec2.aws.crossplane.io", "reconciler kind": "Instance", "name": "sample-instance", "namespace": "", "error": "cannot update managed resource status: Instance.ec2.aws.crossplane.io \"sample-instance\" is invalid: status.atProvider.networkInterfaces[0].privateIpAddresses[0].privateDnsName: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

The instance seems to run fine in AWS
<img width="1039" alt="Screenshot 2022-12-30 at 2 20 55 PM" src="https://user-images.githubusercontent.com/11217399/210052164-2e22af1f-7a25-40b5-9d44-6e2330ef3229.png">

### What environment did it happen in?
Crossplane version: 1.10.1
```
helm list --namespace crossplane-system
NAME      	NAMESPACE        	REVISION	UPDATED                             	STATUS  	CHART            	APP VERSION
crossplane	crossplane-system	1       	2022-12-28 14:44:12.574999 +0530 IST	deployed	crossplane-1.10.1	1.10.1     
```
kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9+IKS", GitCommit:"6d09f5ecc83a8179cb6c28344fb842bdedad8e32", GitTreeState:"clean", BuildDate:"2022-12-09T04:27:53Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
```
Provider version: 0.34
```
kubectl get pkg
NAME                                      INSTALLED   HEALTHY   PACKAGE                                                   AGE
provider.pkg.crossplane.io/provider-aws   True        True      xpkg.upbound.io/crossplane-contrib/provider-aws:v0.34.0   47h
```
