### ISSUE TITLE
apigateway parentIdSelector by matchLabels isn't working

### ISSUE THREAD

**Issue by vispav** [crossplane-contrib/provider-aws#1635]
### What happened?
The API GW resource is not being created using parentIdSelector matchLabels. Creating resource under '/api/v1' getting an error.

`Error: cannot resolve references: mg.Spec.ForProvider.ParentID: cannot get referenced resource: RestAPI.apigateway.aws.upbound.io "test0" not found`

### How can we reproduce it?
```
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: RestAPI
metadata:
  labels:
    testing.upbound.io/name: test
  name: test
spec:
  forProvider:
    name: test
    region: eu-west-1
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Resource
metadata:
  labels:
    testing.upbound.io/resource: test0
  name: "test0"
spec:
  forProvider:
    parentIdSelector:
      matchLabels:
        testing.upbound.io/name: test
    pathPart: "api"
    region: eu-west-1
    restApiIdSelector:
      matchLabels:
        testing.upbound.io/name: test
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Resource
metadata:
  labels:
    testing.upbound.io/resource: test1  
  name: "test1"
spec:
  forProvider:
    parentIdSelector:
      matchLabels:
        testing.upbound.io/resource: test0
    pathPart: "v1"
    region: eu-west-1
    restApiIdSelector:
      matchLabels:
        testing.upbound.io/name: test
```

### What environment did it happen in?
Crossplane version: crossplane/crossplane:v1.10.1
AWS provider version: xpkg.upbound.io/upbound/provider-aws:v0.22.0
