### ISSUE TITLE
Neptune deployment incomplete

### ISSUE THREAD

**Issue by FlorianGerdes** [crossplane-contrib/provider-aws#1642]
Dear crossplane community,
I've been using the latest aws-provider (v0.36.0) to deploy a neptune dbcluster. There are a couple of things, I stumbled across which might be bug/feature request or things I have trouble to understand:

### Code I used:
```
apiVersion: neptune.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: neptune
  annotations:
    crossplane.io/external-name: xxxxxxxxxxxxxxxxxxxxxx-neptune-neptune
spec:
  forProvider:
    region: eu-central-1
    engine: neptune
    engineVersion: "1.2.0.2"
    skipFinalSnapshot: true
    applyImmediately: true
    #databaseName: "neptune"
    dbSubnetGroupName: xxxxxxxxxxxxxxxxxxxx-neptune-neptune-sng
    storageEncrypted: true
    vpcSecurityGroupIDs:
      - sg-0xxxxxxxxxxxxxxxxxxxxxx
    tags:
      - key: Name
        value:xxxxxxxxxxxxxxxx-neptune-neptune
  publishConnectionDetailsTo:
    name: neptune-details
  writeConnectionSecretToRef:
    name: neptune-secret
    namespace: default
```

### What i get:
![image](https://user-images.githubusercontent.com/122877070/213453719-8db87d12-0c59-4bdc-9501-bebb5230aaec.png)

### Questions:

- The parameter `databaseName` doesn't seem to work. When added to the confif:
![image](https://user-images.githubusercontent.com/122877070/213452943-62370612-e327-4db6-bd2b-67ab834de7db.png)
- I suppose the API: `neptune.aws.crossplane.io/v1alpha1` only creates the cluster without any instances. And there is no exsisting API for creating an instance?
- When reading the resulting secrets `neptune-secret`and `neptune-details`they appear to be empty? Is this because there is no instance/database being created?
- There is currently no possibility to specify a reference to a SubnetGroup or SecurityGroup being created via crossplane. I would expect something like: `dbSubnetGroupNameRef`and `vpcSecurityGroupIDRefs`

Thank you for you support. I'm looking forward to getting any insights regarding the current implementation and behavior of neptune.
