### ISSUE TITLE
Can't reference a configmap key in new k8s object

### ISSUE THREAD

**Issue by lum-DannyK** [crossplane-contrib/provider-aws#1650]
### What happened?

I Created a composite and CRD, now I want to use that to create a new K8S object (for example a Route 53 record). I have a configmap with a key and value, that I want to use. So to create the new K8S Object I want to reference to the key in the configmap, but when I do that with `configMapKeyRef` I get an error that It is a map and that It needs a string. 

### How can we reproduce it?

You can do it with composite or just create the Route 53 record resource:
1. Create a ResourceRecordSet like this:
``` YAML
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: ResourceRecordSet
metadata:
  name: test.test.com
  namespace: test1
spec:
  providerConfigRef:
    name: aws-provider
  forProvider:
    type: CNAME
    ttl: 300
    resourceRecords:
    - value:
        valueFrom:
          configMapKeyRef:
            name: "test"
            key: "hostname"
    zoneId: ZONEID
```

### What environment did it happen in?
Crossplane version: 1.10
AWS-Provider: 0.34
Kubernetes Version: 1.22
