### ISSUE TITLE
EFS: fileSystemId value is taken from volume name instead of ID

### ISSUE THREAD

**Issue by dkossako** [crossplane-contrib/provider-aws#1652]
### What happened?

I'm tried to setup EFS volume with no luck. Following issue is present. As you can see instead of ARN value with volume name is returned:
```
.6752522896976464e+09	DEBUG	events	Warning	{
   "object":{
      "kind":"FileSystem",
      "name":"testvolume-wscc7-ck644",
      "uid":"8b8dd8d2-07c9-4923-848a-96cf613994a4",
      "apiVersion":"efs.aws.crossplane.io/v1alpha1",
      "resourceVersion":"146359248"
   },
   "reason":"CannotObserveExternalResource",
   "message":"failed to describe FileSystem: ValidationException: 1 validation error detected: Value 'testvolume-wscc7' at 'fileSystemId' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(arn:aws[-a-z]*:elasticfilesystem:[0-9a-z-:]+:file-system/fs-[0-9a-f]{8,40}|fs-[0-9a-f]{8,40})$\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"\"\n  },\n  Message_: \"1 validation error detected: Value 'testvolume-wscc7' at 'fileSystemId' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(arn:aws[-a-z]*:elasticfilesystem:[0-9a-z-:]+:file-system/fs-[0-9a-f]{8,40}|fs-[0-9a-f]{8,40})$\"\n}"
}
```

### How can we reproduce it?

```
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
(...)
spec:
  group: efs.x
  names:
    kind: CompositeEFSVolume
    plural: compositeefsvolumes
  claimNames:
    kind: EFSVolume
    plural: efsvolumes
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  secretsToNamespace:
                    type: string
                  #throughputMode:
                  #  type: string
                required:
                  - secretsToNamespace
            required:
              - parameters
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
(...)
  resources:
    - name: filesystem
      base:
        apiVersion: efs.aws.crossplane.io/v1alpha1
        kind: FileSystem
        metadata:
          annotations:
            crossplane.io/external-name: placeholder
        spec:
          deletionPolicy: {{ .Values.efsVolume.deletionPolicy }}
          providerConfigRef:
            name: provider-aws
          forProvider:
            # required
            region: {{ .Values.global.aws_region }}
```

### What environment did it happen in?
Crossplane version: 1.9.0
Crossplane provider: provider-aws (0.31.0)
