### ISSUE TITLE
apigateway Integration is not being created

### ISSUE THREAD

**Issue by vispav** [crossplane-contrib/provider-aws#1678]
### What happened?

The integration of apigateway is not being created. No status or error message are printed either.
kubectl get integration.apigateway.aws.crossplane.io
```
NAME          READY   SYNCED   EXTERNAL-NAME
apigateway
apisoftware
```

### How can we reproduce it?

```
apiVersion: apigateway.aws.crossplane.io/v1alpha1
kind: Integration
metadata:
  name: apigateway
spec:
  providerConfigRef:
    name: my-aws
  forProvider:
    # httpMethod: OPTIONS
    httpMethod: "OPTIONS"
    region: eu-west-1
    resourceIdRef:
      name: apigateway
    restApiId: hs281xxxx
    # type_: MOCK
    type_: "MOCK"
```
### What environment did it happen in?
Crossplane version: 
image: crossplane/crossplane:v1.10.1
image: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.36.1
