### ISSUE TITLE
OpenSearch domain name mismatch

### ISSUE THREAD

**Issue by kd7lxl** [crossplane-contrib/provider-aws#1682]
### What happened?

I've noticed that OpenSearch Domains seem to use the `.metadata.name` of the `Domain` rather than than the `.spec.forProvider.name` when creating domains, then tries to reference it by the `.spec.forProvider.name` later during reconciles. This breaks down whenever the names don't match. This makes me wonder what the point of the `.spec.forProvider.name` field is -- everything could be driven off the `.metadata.name` to avoid this issue.

### How can we reproduce it?

```yaml
apiVersion: opensearchservice.aws.crossplane.io/v1alpha1
kind: Domain
metadata:
  name: sample-mydomain
spec:
  forProvider:
    name: mydomain
    region: us-east-1
    ebsOptions:
      ebsEnabled: true
      volumeType: gp2
      volumeSize: 10
  providerConfigRef:
    name: example
```
```
% kubectl get domains.opensearchservice.aws.crossplane.io sample-mydomain
NAME              READY   SYNCED   EXTERNAL-NAME
sample-mydomain           False    sample-mydomain
```
```
% kubectl describe domains.opensearchservice.aws.crossplane.io sample-mydomain | tail
Events:
  Type     Reason                        Age                  From                                                Message
  ----     ------                        ----                 ----                                                -------
  Normal   CreatedExternalResource       86s                  managed/domain.opensearchservice.aws.crossplane.io  Successfully requested creation of external resource
  Warning  CannotUpdateExternalResource  35s (x6 over 85s)    managed/domain.opensearchservice.aws.crossplane.io  ResourceNotFoundException: Domain not found: mydomain
```
```json
% aws opensearch list-domain-names
{
    "DomainNames": [
        {
            "DomainName": "sample-mydomain",
            "EngineType": "OpenSearch"
        }
    ]
}
```
Notice that `"DomainName": "sample-mydomain"` does not match
```yaml
spec:
  forProvider:
    name: mydomain
```

### What environment did it happen in?
Crossplane version: v1.11.0
provider-aws: v0.37.1
kubernetes: v1.24.8-eks-ffeb93d
