### ISSUE TITLE
Updates for Kafka cluster and configuration are not/ not always applied

### ISSUE THREAD

**Issue by Patrick-L** [crossplane-contrib/provider-aws#1683]
### What happened?
Updates for Kafka clusters and Kafka cluster configurations are successfully created in the cluster as CRD, but are not applied in AWS. This means for kafka-cluster they are not changed and for cluster-configurations no new revision is created.

### How can we reproduce it?
For Kafka cluster:
Add openMonitoring config to cluster crd. The changes are not visible in the aws management console. 

CRD excerpt:
```
   openMonitoring:
      prometheus:
        jmxExporter:
          enabledInBroker: true
        nodeExporter:
          enabledInBroker: true
```

For Cluster configuration:
Add new property like "delete.topic.enable=true". The changes are not visible in the aws management console. 

CRD excerpt:
```
    properties:
      - delete.topic.enable=true
```

### What environment did it happen in?
Crossplane version: v0.37.0
Cloud provider: AWS
