### ISSUE TITLE
Problem with create AmazonMQ rabbitmq

### ISSUE THREAD

**Issue by es1o** [crossplane-contrib/provider-aws#1691]
### What happened?
I'm trying to create AmazonMQ RabbitMQ broker but nothing happenes.
I get only information:

```cannot determine creation result - remove the crossplane.io/external-create-pending annotation if it is safe to proceed```

### How can we reproduce it?

My broker forProvider spec:

```
spec:
  deletionPolicy: Orphan
  forProvider:
    autoMinorVersionUpgrade: false
    deploymentMode: CLUSTER_MULTI_AZ
    engineType: RabbitMQ
    engineVersion: 3.10.10
    hostInstanceType: mq.m5.large
    publiclyAccessible: false
    region: eu-west-1
```

### What environment did it happen in?
Crossplane version: v1.9.0
Crossplane-aws version: v0.31.0
