### ISSUE TITLE
OpenSearch Creation in an existing VPC is failing

### ISSUE THREAD

**Issue by kushalhalder** [crossplane-contrib/provider-aws#1706]
### How can we reproduce it?
I am trying to create an OpenSearch Domain in an existing VPC. I am using the one from the examples: 
```
apiVersion: opensearchservice.aws.crossplane.io/v1alpha1
kind: Domain
metadata:
  name: sample2-domain
spec:
  forProvider:
    name: sample2-domain
    region: us-east-1
    ebsOptions:
      ebsEnabled: true
      volumeType: gp2
      volumeSize: 10
    clusterConfig:
      zoneAwarenessEnabled: true
      zoneAwarenessConfig:
        availabilityZoneCount: 2
      instanceCount: 2
    encryptionAtRestOptions:
      enabled: true
      kmsKeyIdRef:
        name: dev-key
    vpcOptions:
      securityGroupIdRefs:
        - name: sample-cluster-sg-2
      subnetIdRefs:
        - name: sample-subnet1
        - name: sample-subnet2
  writeConnectionSecretToRef:
    name: sample2-domain
    namespace: crossplane-system
  providerConfigRef:
    name: example
```
with my vpc subnet ids. Whenever I apply this, I get the following error: 
`cannot create Domain in AWS: ValidationException: Subnet must be specified for VPC domain`

When I try to create a Domain without the VPC options, it creates the Domain on AWS. 

Is there any other way to specify vpc id?

### What environment did it happen in?
I am using Crossplane installed in a local Kubes cluster, and applying the Crossplane YAML using ArgoCD.

Crossplane version: crossplane/crossplane:v1.11.2
Kubernetes version:
```
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.4",
    "gitCommit": "872a965c6c6526caa949f0c6ac028ef7aff3fb78",
    "gitTreeState": "clean",
    "buildDate": "2022-11-09T13:28:30Z",
    "goVersion": "go1.19.3",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.2",
    "gitCommit": "5835544ca568b757a8ecae5c153f317e5736700e",
    "gitTreeState": "clean",
    "buildDate": "2022-09-21T14:27:13Z",
    "goVersion": "go1.19.1",
    "compiler": "gc",
    "platform": "linux/arm64"
  }
}
```
