### ISSUE TITLE
rds/docdb: ParameterGroup in update loop bc of applyMethod

### ISSUE THREAD

**Issue by wotolom** [crossplane-contrib/provider-aws#1708]
### What happened?
affecting `RDS` + `DocDB`: resources `DBParameterGroup`, `DBClusterParametergroup`

AWS seems to only consider changes to the field `ApplyMethod`, if the `ParameterValue` changes too.
This results in the controller constantly doing update calls.

I will provide a PR shortly.

### How can we reproduce it?

example for `DBParameterGroup`:

```yaml
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBParameterGroup
metadata:
  name: example-dbparametergroup
spec:
  forProvider:
    region: us-east-1
    dbParameterGroupFamilySelector:
      engine: postgres
    description: "this applyMethod: immediate will not be set. AWS will only change it when parameterValue changes too "
    parameters:
      - applyMethod: immediate # immediate pending-reboot
        parameterName: rds.force_ssl
        parameterValue: "0"
  providerConfigRef:
    name: example
```

### What environment did it happen in?
* Crossplane version: 1.11.1
* Provider-aws version: v0.38.0
