### ISSUE TITLE
Aws provider pod crashing when applying an MSK cluster 

### ISSUE THREAD

**Issue by patjones** [crossplane-contrib/provider-aws#1743]
We've had no issues deploying kafka on previous provider versions, but in the process of migrating to a newer environment, we noticed msk cluster creation seems broken on version 0.38.

I believe I am seeing the same issue as #1391 but with aws provider version 0.38

### What happened?
I created an msk config with all the required values as defined in the[ provider spec](https://doc.crds.dev/github.com/crossplane/provider-aws/kafka.aws.crossplane.io/Cluster/v1alpha1@v0.38.0) 

Once applied, the object itself has the following event logged
`cannot determine creation result - remove the crossplane.io/external-create-pending annotation if it is safe to proceed`

Taking a look at the provider in crossplane-system the pod itself is erroring at cluster creation time with the following error

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x428a395]

goroutine 5580 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x5a8c220, 0x9d39d70})
	runtime/panic.go:838 +0x207
github.com/crossplane-contrib/provider-aws/pkg/controller/kafka/cluster.preCreate({0xc004481e00?, 0x0?}, 0xc004481e00, 0xc006b76240)
	github.com/crossplane-contrib/provider-aws/pkg/controller/kafka/cluster/setup.go:127 +0xf5
github.com/crossplane-contrib/provider-aws/pkg/controller/kafka/cluster.(*external).Create(0xc00664c9a0, {0x6faf740, 0xc006b1e180}, {0x6fe6950?, 0xc004481e00})
	github.com/crossplane-contrib/provider-aws/pkg/controller/kafka/cluster/zz_controller.go:109 +0x404
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc0006480b0, {0x6faf778, 0xc0065afb60}, {{{0x0?, 0x0?}, {0xc006b00390?, 0xd?}}})
	github.com/crossplane/crossplane-runtime@v0.19.0/pkg/reconciler/managed/reconciler.go:899 +0x642b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x6faf778?, {0x6faf778?, 0xc0065afb60?}, {{{0x0?, 0x554f200?}, {0xc006b00390?, 0x413fb4?}}})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005b1540, {0x6faf6d0, 0xc000a955c0}, {0x5d3b9c0?, 0xc006590940?})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x386
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005b1540, {0x6faf6d0, 0xc000a955c0})
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:231 +0x32
```

### How can we reproduce it?
We are using the following cluster configuration and the problem behavior is seen immediately at creation time.
```
apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: roadhog-kafka
spec:
  deletionPolicy: Orphan
  forProvider:
    brokerNodeGroupInfo:
      clientSubnets:
        - 
        - 
      instanceType: kafka.t3.small
    clusterName: kafka-cluster-dev-rosa
    kafkaVersion: 2.6.1
    numberOfBrokerNodes: 2
    region: us-west-2
  providerConfigRef:
    name: provider-aws
 ```

### What environment did it happen in?
Crossplane version: 1.11.0
aws provider version 0.38.0

**Comment by chlunde** [comment]
We should fix this, in the meantime, try

```yaml
      storageInfo: 
        ebsStorageInfo:
          volumeSize: 10
```
