### ISSUE TITLE
Provider version 0.39.0 fails to install

### ISSUE THREAD

**Issue by junglie85** [crossplane-contrib/provider-aws#1745]
### What happened?
Deploying the provider-aws with IRSA using the [provided instructions](https://github.com/crossplane-contrib/provider-aws/blob/master/AUTHENTICATION.md#steps) fails with the following error:
```
Error: aws-provider failed to create kubernetes rest client for update of resource: resource [aws.crossplane.io/v1beta1/ProviderConfig] isn't valid for cluster, check the APIVersion and Kind fields are valid
```
Describing the `Provider` manifest shows that v0.39.0 is an unknown tag ([the last tag was v0.32.0 and was pushed over 7 months ago](https://hub.docker.com/r/crossplane/provider-aws/tags) at the time of writing):
```
Warning  UnpackPackage  2m38s (x23 over 43m)   packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: HEAD https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.39.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details): GET https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.39.0: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v0.39.0
```
It's also really not clear which of https://github.com/crossplane-contrib/provider-aws or https://github.com/upbound/provider-aws should be used!

### How can we reproduce it?
```
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
IAM_ROLE_NAME=provider-aws
VERSION=0.39.0
cat <<EOF | kubectl apply -f -
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$AWS_ACCOUNT_ID:role/$IAM_ROLE_NAME
spec:
  podSecurityContext:
    fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:v${VERSION}
  controllerConfigRef:
    name: aws-config
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
spec:
  credentials:
    source: InjectedIdentity
EOF
```

### What environment did it happen in?
Crossplane version: 1.12.1
