### ISSUE TITLE
Can't install few providers at once.

### ISSUE THREAD

**Issue by mykhailokoliadko** [crossplane-contrib/provider-aws#1749]
Hi, guys.
I trying to install a couple of providers in my cluster with Helm.
If this is just one of then it installed with no problems, but as soon as I tried to install two of them then either no one healthy or just one healthy.
Below are values.yaml that I used and a couple of screenshots of my k9s.
As you can see in the first screenshot, at first the revision is normal, then when I install the second provider, it changes to unhealthy, then after removing one of the providers, it becomes healthy.

![Screenshot 2023-05-03 at 17 18 51](https://user-images.githubusercontent.com/18448584/235961214-46ef2533-52ad-41a3-b6c9-61f8226f1a3d.png)

![Screenshot 2023-05-03 at 17 20 03](https://user-images.githubusercontent.com/18448584/235961755-cdc40a3c-1702-43d8-a70f-cec902b62360.png)

```
replicas: 1

deploymentStrategy: RollingUpdate

image:
  repository: crossplane/crossplane
  tag: v1.12.1
  pullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic

nodeSelector: {}
tolerations: []
affinity: {}

hostNetwork: false

# -- Custom labels to add into metadata
customLabels: {}

# -- Custom annotations to add to the Crossplane deployment and pod
customAnnotations: {}

# -- Custom annotations to add to the serviceaccount of Crossplane
serviceAccount:
  customAnnotations: {}

leaderElection: true
args: []

provider:
  packages: [
     xpkg.upbound.io/upbound/provider-aws:v0.34.0,
     xpkg.upbound.io/upbound/provider-azure:v0.31.0,
  ]

configuration:
  packages: []

imagePullSecrets: {}

registryCaBundleConfig: {}

webhooks:
  enabled: false

rbacManager:
  deploy: true
  skipAggregatedClusterRoles: false
  replicas: 1
  managementPolicy: All
  leaderElection: true
  args: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

priorityClassName: ""

resourcesCrossplane:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

packageCache:
  medium: ""
  sizeLimit: 20Mi
  pvc: ""
  configMap: ""

resourcesRBACManager:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContextRBACManager:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

metrics:
  enabled: false

extraEnvVarsCrossplane: {}

extraEnvVarsRBACManager: {}

podSecurityContextCrossplane: {}

podSecurityContextRBACManager: {}

extraVolumesCrossplane: {}

extraVolumeMountsCrossplane: {}

# The alpha xfn sidecar container that runs Composition Functions. Note you also
# need to run Crossplane with --enable-composition-functions for it to call xfn.
xfn:
  enabled: false
  image:
    repository: crossplane/xfn
    tag: v1.12.1
    pullPolicy: IfNotPresent
    revisionActivationPolicy: Automatic
  args: []
  extraEnvVars: {}
  securityContext:
    runAsUser: 65532
    runAsGroup: 65532
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    # These capabilities allow xfn to create better user namespaces. It drops
    # them after creating a namespace.
    capabilities:
      add: ["SETUID", "SETGID"]
    # xfn needs the unshare syscall, which most RuntimeDefault seccomp profiles
    # do not allow.
    seccompProfile:
      type: Unconfined
  cache:
    medium: ""
    sizeLimit: 1Gi
    pvc: ""
    configMap: ""
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
```
