### ISSUE TITLE
AutoScalingGroups not working with the vpcZoneIdentifier attribute

### ISSUE THREAD

**Issue by rudimk** [crossplane-contrib/provider-aws#1752]
### What happened?

According to the documentation for `AutoScalingGroup.spec.forProvider.vpcZoneIdentifier`, one needs to provide a comma-separated list of subnets for the autoscaling group to spin up VMs in. My use case involves configuring an autoscaling group to spin up machines inside a particular VPC's private subnets. Unfortunately, specifying a list of private subnet IDs doesn't seem to work, because CrossPlane throws the following error in the `AutoScalingGroup`'s events:

```
cannot create AutoScalingGroup in AWS: ValidationError: The security group 'rudimk-testbed20230306153306326400000009' does not exist in default VPC 'vpc-d2e33caf'
```

This is what my manifest looks like:

```yaml
apiVersion: autoscaling.aws.crossplane.io/v1beta1
kind: AutoScalingGroup
metadata:
  name: rudimk-testbed-worker-group-22023030615442825080000001xp
spec:
  deletionPolicy: Orphan
  forProvider:
    availabilityZones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    minSize: 0
    maxSize: 0
    desiredCapacity: 0
    desiredCapacityType: units
    launchTemplate:
      launchTemplateName: rudimk-testbed-worker-group-220230306154427811400000023
      version: "$Latest"
    region: us-east-1
    tags:
      - key: 'kubernetes.io/cluster/rudimk-testbed'
        propagateAtLaunch: true
        value: 'owned'
      - key: 'porter.run/manager'
        propagateAtLaunch: true
        value: 'p3s-xp-hub'
      - key: 'porter.run/manager/p3s-xp-hub/cluster'
        propagateAtLaunch: true
        value: 'rudimk-testbed'
    vpcZoneIdentifier: "subnet-0ee3177e5fb7f5ce9, subnet-06df8c78483c47b02, subnet-0dfb6eae2fa7e7c0e"
  providerConfigRef:
    name: rudimk-2591-creds
```

The security group referenced in that error is a security group specified in the launch template mentioned in the manifest, and it exists in the VPC I've created - as do those subnets. But it seems like `vpcZoneIdentifier` is being ignored, and Crossplane's always attempting to use the default VPC. I've tried a bunch of variations - removing `availabilityZones`, removing spaces between the subnet IDs, not quoting the string containing the subnet IDs - all to no avail. At any rate, I don't think the problem lies with the string itself; this works out with the Python and Golang AWS SDKs.

On a side note - the example manifest at https://github.com/crossplane-contrib/provider-aws/blob/master/examples/autoscale/autoscalinggroup.yaml#L67 is rather inaccurate, since it references a subnet name instead of the ID; I tried that too, to no avail:

```
managed/autoscalinggroup.autoscaling.aws.crossplane.io  cannot create AutoScalingGroup in AWS: ValidationError: The subnet ID 'rudimk-testbed-vpc-private-us-east-1c' does not exist
```
Any pointers here would be much appreciated!

### How can we reproduce it?

1. Ensure you have a VPC with private subnets set up(this can be created through Crossplane or outside)
2. Create an `AutoScalingGroup` where the private subnet IDs are added as a comma-separated list to `AutoScalingGroup.spec.forProvider.vpcZoneIdentifier`, and apply it.
3. Watch the events for said `AutoScalingGroup`.

### What environment did it happen in?
Crossplane version: `v1.12.1`
Provider version: `xpkg.upbound.io/crossplane-contrib/provider-aws:v0.39.0`
Kubernetes version: `v1.24.10`
Kubernetes distribution: K3s
Base OS: Ubuntu 20.04
