### ISSUE TITLE
Creating an S3 bucket is failing due to missing security header

### ISSUE THREAD

**Issue by itaimalek** [crossplane-contrib/provider-aws#1767]
Hi all, I'm very new to Crossplane and I'm trying to create an S3 bucket on my AWS EKS cluster.
I'm using `crossplanecontrib/provider-aws:v0.40.0` and deployed Crossplane using Helm chart `crossplane-1.12.1`
mu bucket manifest is as follows:
```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: itai-xp-bucket-otier
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: us-east-1
  providerConfigRef:
    name: aws-provider-config
```
and for the life of me I can't get it to work properly, the bucket is created in my AWS account but it show:
```
NAME                     READY   SYNCED   AGE
itai-xp-bucket-otier   False   False    6m13s
```
and on describe it shows:
```
Warning  CannotObserveExternalResource  12s   managed/bucket.s3.aws.crossplane.io  operation error S3: PutBucketAcl, https response error StatusCode: 400, RequestID: QHTZ1Q2PPPBFVNEA, HostID: c8vdotjdA4lof0RbBrumE8HlnC/UKGpClviBuOeflNOAHpePhTLXLU4ib1mTDvk4mHu18ZU2ZHw=, api error MissingSecurityHeader: Your request was missing a required header
```
can anyone hint on what am I missing, I've been working on this for an entire day now with no luck :disappointed:

on a sidenote I've tried the official Upbound provider and `provider-jet-aws:v0.5.0` both worked as expected but I'm keen on using this provider.
