### ISSUE TITLE
Modifying DBInstance on every apply

### ISSUE THREAD

**Issue by okgolove** [crossplane-contrib/provider-aws#1770]
### What happened?

RDS instance is modified by provider every time I apply the same manifest.

Provider diff log (the same every time):
```
2023/06/07 13:08:14 Found observed difference in dbinstance
  &v1alpha1.DBInstanceParameters{
        ... // 4 ignored and 31 identical fields
        NcharCharacterSetName:              nil,
        NetworkType:                        nil,
-       OptionGroupName:                    nil,
+       OptionGroupName:                    &"test-internal-dev-aa543a",
        PerformanceInsightsKMSKeyID:        nil,
        PerformanceInsightsRetentionPeriod: nil,
        ... // 3 ignored and 11 identical fields
  }
```

kubectl diff:
```
   creationTimestamp: "2023-06-07T07:47:56Z"
   finalizers:
   - finalizer.managedresource.crossplane.io
-  generation: 35
+  generation: 36
   name: test-internal-dev-aa543a
   resourceVersion: "3558141"
   uid: 8ef0d661-741c-4fed-ac0f-ec3f9d9f9aee
@@ -35,7 +35,7 @@
     enableIAMDatabaseAuthentication: false
     enablePerformanceInsights: false
     engine: sqlserver-ex
-    engineVersion: 15.00.4236.7.v1
+    engineVersion: "15.00"
     finalDBSnapshotIdentifier: test-internal-dev-aa543a
     iops: 3000
     licenseModel: license-included
@@ -51,6 +51,7 @@
     preferredMaintenanceWindow: thu:05:36-thu:06:06
     publiclyAccessible: true
     region: eu-north-1
+    skipFinalSnapshot: false
     storageEncrypted: false
     storageThroughput: 125
     storageType: gp3
```

### How can we reproduce it?

* Apply yaml and wait until created.
* Apply again.
```yaml
---
# Source: wit-server/templates/aws/rds.yaml
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: test-internal-dev-aa543a
spec:
  forProvider:
    allocatedStorage: 100
    applyImmediately: true
    autogeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    dbInstanceClass: "db.t3.small"
    deletionProtection: true
    engine: sqlserver-ex
    engineVersion: "15.00"
    dbParameterGroupNameRef:
      name: test-internal-dev-aa543a
    optionGroupName: test-internal-dev-aa543a
    masterUserPasswordSecretRef:
      key: password
      name: rds-master-password
      namespace: test
    publiclyAccessible: true
    dbSubnetGroupName: test-dev
    region: eu-north-1
    skipFinalSnapshot: false
    finalDBSnapshotIdentifier: test-internal-dev-aa543a
    storageEncrypted: false
    storageType: gp3
    masterUsername: wit
    vpcSecurityGroupIDRefs:
      - name: test-internal-dev-rds-aa543a
  writeConnectionSecretToRef:
    name: rds-connection-settings
    namespace: test
---
# Source: wit-server/templates/aws/rds.yaml
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBParameterGroup
metadata:
  name: test-internal-dev-aa543a
spec:
  forProvider:
    description: test-internal-dev-aa543a
    dbParameterGroupFamily: "sqlserver-ex-15.0"
    region: eu-north-1
---
# Source: wit-server/templates/aws/rds.yaml
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: OptionGroup
metadata:
  name: test-internal-dev-aa543a
spec:
  forProvider:
    engineName: sqlserver-ex
    majorEngineVersion: "15.00"
    optionGroupDescription: test-internal-dev-aa543a
    region: eu-north-1
---
# Source: wit-server/templates/aws/rds.yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: test-internal-dev-rds-aa543a
  namespace: test
spec:
  forProvider:
    description: RDS MSSQL for wit-server
    groupName: test-internal-dev-rds-aa543a
    ingress:
      - fromPort: 1433
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 0.0.0.0/0
        toPort: 1433
    region: eu-north-1
    vpcId: vpc-xxxx
```

### What environment did it happen in?
Crossplane version: v1.12.1
aws-provider version: 0.40.0
