### ISSUE TITLE
ElasticCache replicasPerNodeGroup not updating do not trigger resizing

### ISSUE THREAD

**Issue by fabioaraujopt** [crossplane-contrib/provider-aws#1788]
### What happened?
Changing parameter "replicasPerNodeGroup" in the cache.aws.crossplane.io ReplicationGroup does not creates/deletes replicas to each of the shards (in cluster mode enabled).
Although it creates the correct number of shards and replicas, it does not update (add/remove replicas) after the cluster is created.

### How can we reproduce it?
We are using the following configuration:
```
apiVersion: cache.aws.crossplane.io/v1beta1
kind: ReplicationGroup
spec:
  deletionPolicy: Delete
  forProvider:
    applyModificationsImmediately: true
    atRestEncryptionEnabled: true
    authEnabled: true
    automaticFailoverEnabled: true
    cacheNodeType: cache.t4g.micro
    cacheParameterGroupName: default.redis7.cluster.on
    cacheSubnetGroupName: some-cache
    cacheSubnetGroupNameSelector:
      matchLabels:
        cacheName: some-cache
    engine: redis
    engineVersion: '7.0'
    numNodeGroups: 2
    port: 6379
    region: eu-west-2
    replicasPerNodeGroup: 2
    replicationGroupDescription:  some-description
    securityGroupIdRefs:
      - name:  some-security-group
    securityGroupIdSelector:
      matchLabels:
        cacheName: some-security-group
    snapshotRetentionLimit: 0
    transitEncryptionEnabled: true
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: some-secret
    namespace: some-namespace
```
### What environment did it happen in?
Crossplane version: v1.10.1
provider-aws version: v0.36.1
