### ISSUE TITLE
EC2 instances getting constant "refresh failed"

### ISSUE THREAD

**Issue by avinakollu** [crossplane-contrib/provider-aws#1791]
### What happened?

We are trying to create EC2 instances using the aws provider. The instance does get created, but after it is up, there are constant error events in the resource.

``` 
Message:               observe failed: cannot run refresh: refresh failed: Conflicting configuration arguments: "cpu_threads_per_core": conflicts with cpu_options.0.threads_per_core
Conflicting configuration arguments: "cpu_core_count": conflicts with cpu_options.0.core_count
Conflicting configuration arguments: "cpu_options.0.core_count": conflicts with cpu_core_count
Conflicting configuration arguments: "cpu_options.0.threads_per_core": conflicts with cpu_threads_per_core
```
This doesn't let us update or remove the VM. We have to do it manually.

### How can we reproduce it?
This is the manifest we are using:
```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: test
spec:
  forProvider:
    ami: ami-07c781a9ff16018ea
    keyName: test-key
    instanceType: t3.medium
    subnetId: subnet-0b61449cc93c48841
    region: us-west-2
    vpcSecurityGroupIdRefs:
      - name: test-security-group
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version: 1.12.2
provider-aws: v0.36.0
kubernetes: 1.26
distro: EKS
