### ISSUE TITLE
Unable to upgrade AWS EKS Cluster K8s version - "InvalidParameterException: Encryption is already enabled on the cluster"

### ISSUE THREAD

**Issue by evgeny-goldin** [crossplane-contrib/provider-aws#1794]
### What happened?

We have the following EKS Cluster resource:

```
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
    ..
spec:
  deletionPolicy: Delete
  forProvider:
    encryptionConfig:
    - provider:
        keyArn: arn:aws:kms:us-west-2:<id>:key/<id>
      resources:
      - secrets
    region: us-west-2
    resourcesVpcConfig:
      ..
    version: "1.24"
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: 518b6783-dda8-4833-aa33-a3e9da0c12d0-ekscluster
    namespace: crossplane-system
```

Attempting to update `"spec.forProvider.version"` from `1.24` to `1.25` triggers provider error - `"cannot update EKS cluster version: InvalidParameterException: Encryption is already enabled on the cluster"`:

```
crossplane-provider-aws-0092ddeac705-659b9d7b8-rkwnl provider-aws 2023-06-29T05:30:56.340Z	DEBUG	events	cannot update EKS cluster version: InvalidParameterException: Encryption is already enabled on the cluster	{"type": "Warning", "object": {"kind":"Cluster","name":"..","uid":"b329aa19-ee33-4ab5-a04c-55375f4be179","apiVersion":"eks.aws.crossplane.io/v1beta1","resourceVersion":"1477122"}, "reason": "CannotUpdateExternalResource"}
```

The workaround is to update the K8s cluster version manually in the AWS Console.
What looks like the same issue that was opened last year - https://github.com/crossplane-contrib/provider-aws/issues/1520 - offers to use a KMS keyARN which we already use. 

### How can we reproduce it?

* Create an EKS `Cluster` with `encryptionConfig` enabled and `version`:

```
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
spec:
  forProvider:
    encryptionConfig:
    - provider:
        keyArn: arn:aws:kms:us-west-2:<id>:key/<id>
    ..
    version: "1.24"
```
* Update `spec.forProvider.version` from `1.24` to `1.25`

### What environment did it happen in?

* AWS, us-west-2, EKS
* Crossplane version: 

```
crossplane                                    1/1     1            1           2d18h   crossplane            crossplane/crossplane:v1.12.2                                   app=crossplane,release=crossplane
crossplane-rbac-manager                       1/1     1            1           2d18h   crossplane            crossplane/crossplane:v1.12.2                                   app=crossplane-rbac-manager,release=crossplane
crossplane-provider-helm-503c3591121b         1/1     1            1           2d18h   provider-helm         xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0        pkg.crossplane.io/provider=provider-helm,pkg.crossplane.io/revision=crossplane-provider-helm-503c3591121b
crossplane-provider-kubernetes-fd7ab5be249e   1/1     1            1           2d18h   provider-kubernetes   xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.9.0   pkg.crossplane.io/provider=provider-kubernetes,pkg.crossplane.io/revision=crossplane-provider-kubernetes-fd7ab5be249e
crossplane-provider-aws-0092ddeac705          1/1     1            1           2d18h   provider-aws          xpkg.upbound.io/crossplane-contrib/provider-aws:v0.41.1         pkg.crossplane.io/provider=provider-aws,pkg.crossplane.io/revision=crossplane-provider-aws-0092ddeac705
```
