### ISSUE TITLE
[RDS Instance] EngineVersion parameter is not being sent to AWS during creation in latest version of crossplane

### ISSUE THREAD

**Issue by WolfGanGeRTech** [crossplane-contrib/provider-aws#1798]
### What happened?
After upgrading from 0.40.0 to 0.41.1 we noticed that when creating a new RDS Instance (Postgres) the parameter "Engine Version" is not being sent. The value is correctly defined in the composition since the DB ParameterGroup is correctly created, only the RDS Instance is not sending the engineVersion.
This is probably related with the changes performed in RDS from version 0.40.0 to 0.41.0

### How can we reproduce it?
Create a crossplane manifest to create a new RDS Instance (DBInstance) and define "engineVersion" to a version different from the latest one.
Apply the manifest and check Cloudtrail logs (it will not contain the "engineVersion" and will launch the latest version).

This will create a mismatch between the creation of the parameter group that is receiving the correct engineVersion and the DBInstance that will launch with the latest version.

ERROR: The parameter group <name> with DBParameterGroupFamily postgres13 can't be used for this instance. Use a parameter group with DBParameterGroupFamily postgres14.

### What environment did it happen in?
Crossplane AWS version: 0.41.1
Crossplane version: 1.12.1 

Cloudtrail logs for version 0.40.0:

```json
  "requestParameters": {
        "dBName": "databasename",
        "allocatedStorage": 20,
        "dBInstanceClass": "db.t3.micro",
        "engine": "postgres",
        "preferredMaintenanceWindow": "sat:08:00-sat:11:00",
        "backupRetentionPeriod": 2,
        "preferredBackupWindow": "07:00-08:00",
        "multiAZ": false,
        "engineVersion": "13.7",
        ...
        }
```
        
Cloudtrail logs for version 0.41.1  (engineVersion is missing):

```json

  "requestParameters": {
        "dBName": "databasename",
        "allocatedStorage": 20,
        "dBInstanceClass": "db.t3.micro",
        "engine": "postgres",
        "preferredMaintenanceWindow": "sat:08:00-sat:11:00",
        "backupRetentionPeriod": 2,
        "preferredBackupWindow": "07:00-08:00",
        "multiAZ": false,
        ...
        }
```

**Comment by WolfGanGeRTech** [comment]
Hello @MisterMX ,

It seems the issue is related with the commit https://github.com/crossplane-contrib/provider-aws/commit/8d5f1f0e88a4ba8f23c6571318d6008c91f3c961 I tried to investigate where the issue was in the code but I couldn't.

**Comment by MisterMX** [comment]
@WolfGanGeRTech can you please provide the full YAML to reproduce this issue?

**Comment by WolfGanGeRTech** [comment]
Sure!

**In version 0.40.0.**
I use the following manifest file:

```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-dbinstance
spec:
  forProvider:
    region: eu-central-1
    dbInstanceClass: db.t3.micro 
    dbName: example
    engine: postgres
    allocatedStorage: 20
    engineVersion: "13.7"
    masterUsername: adminuser
    masterUserPasswordSecretRef:
      key: password
      name: example-dbinstance
      namespace: default
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: default
  providerConfigRef:
    name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: example-dbinstance
  namespace: default
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
  ```

Database is created with **correct version (13.7)** and Cloudtrail request is:

```
"requestParameters": {
        "dBInstanceIdentifier": "example-dbinstance",
        "engine": "postgres",
        "masterUsername": "adminuser",
        "allocatedStorage": 20,
        "dBName": "example",
        "engineVersion": "13.7",  <------------------------ Engine Version is present
        "dBInstanceClass": "db.t3.micro",
        "masterUserPassword": "HIDDEN_DUE_TO_SECURITY_REASONS"
},
```

---

**Using version 0.41.1**
I use the following manifest file:

```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-dbinstance2
spec:
  forProvider:
    region: eu-central-1
    dbInstanceClass: db.t3.micro 
    dbName: example
    engine: postgres
    allocatedStorage: 20
    engineVersion: "13.7"
    masterUsername: adminuser
    masterUserPasswordSecretRef:
      key: password
      name: example-dbinstance2
      namespace: default
  writeConnectionSecretToRef:
    name: example-dbinstance-out2
    namespace: default
  providerConfigRef:
    name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: example-dbinstance2
  namespace: default
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123 
  ```
  
Database is created with **incorrect version (14.7)** and Cloudtrail request is:

     "requestParameters": {
        "dBName": "example",
        "dBInstanceIdentifier": "example-dbinstance2",
        "allocatedStorage": 20,
        "dBInstanceClass": "db.t3.micro",
        "engine": "postgres",
                                                  <------------------------  (engineVersion is not present)
        "masterUsername": "adminuser",
        "masterUserPassword": "HIDDEN_DUE_TO_SECURITY_REASONS"
    },
