### ISSUE TITLE
DBCluster: writeConnectionSecretToRef doesn't output the read replica

### ISSUE THREAD

**Issue by dhumphries-sainsburys** [crossplane-contrib/provider-aws#1808]
### What happened?
When outputting the connection information from a DBCluster we do not get an endpoint for the read replicas in an aurora database only the write endpoint

### How can we reproduce it?
Create a DBCluster like so
```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  name: example-aurora-postgres-cluster
spec:
  forProvider:
    region: eu-west-1
    engine: aurora-postgresql
    engineVersion: '13.6'
    allowMajorVersionUpgrade: true
    backupRetentionPeriod: 14
    copyTagsToSnapshot: true
    masterUsername: masteruser
    manageMasterUserPassword: false
    port: 5432
    autogeneratePassword: true
    autoMinorVersionUpgrade: false
    masterUserPasswordSecretRef:
      name: example-aurora-mysql-cluster
      namespace: crossplane-system
      key: password
    storageEncrypted: true
    databaseName: auroradb
    dbClusterParameterGroupName: example-clusterparametergroup13
    dbSubnetGroupName: lab-data
    skipFinalSnapshot: true
    applyImmediately: true
    finalDBSnapshotIdentifier: test-dan-humphries-lab-aurora-dantest-psql-final
    vpcSecurityGroupIDRefs:
      - name: 'lab-rds-sg'
  providerConfigRef:
    name: aws
  providerRef:
    name: aws
  writeConnectionSecretToRef:
    name: test-dan-humphries-rds-dantest-psql-auroracluster
    namespace: crossplane-system
```
Navigate to the secret `test-dan-humphries-rds-dantest-psql-auroracluster` in the crossplane-system and you get something like the below that has a single endpoint rather than the 2 that the GUI shows
```
apiVersion: v1
kind: Secret
metadata:
  name: test-dan-humphries-rds-dantest-psql-auroracluster
  namespace: crossplane-system
data:
  endpoint: >-
ZXhhbXBsZS1hdXJvcmEtcG9zdGdyZXMtY2x1c3Rlci5jbHVzdGVyLWNmbmE5cnZkYjNuNC5ldS13ZXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  password: VGVzdHBhc3N3b3JkMTIzIQ==
  port: NTQzMg==
  username: bWFzdGVydXNlcg==
type: connection.crossplane.io/v1alpha1
```

### What environment did it happen in?
Crossplane version: v1.12.1
AWS Provider version: v0.40.0
EKS version: 1.25.11
