### ISSUE TITLE
Can not create self-referencing SG ingress rule.

### ISSUE THREAD

**Issue by rodrigodelmonte** [crossplane-contrib/provider-aws#1819]
### What happened?

Can not create Security Group ingress rule self referencing the same security group.

Reconcile error, update failed: failed to authorize ingress rules: api error MissingParameter: Source group ID missing.

### How can we reproduce it?

Create VPC and SecurityGroup

```yaml
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: my-vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-west-2
    tags:
      - key: Name
        value: self-reference-test
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: self-referential
spec:
  forProvider:
    groupName: self-referential
    description: "Allow all communication between instances"
    vpcIdRef:
      name: my-vpc
    ingress:
      - ipProtocol: "-1"
        fromPort: 0
        toPort: 56535
        userIdGroupPairs:
        - description: Allowing Cache port Inbound Access
          groupIdSelector:
            matchControllerRef: true
            policy:
              resolution: Optional
              resolve: Always
    egress:
      - fromPort: 0
        toPort: 56535
        ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
            description: everywhere
    region: us-west-2
    tags:
      - key: Name
        value: self-referential
```

```sh
❯ kubectl describe securitygroup/self-referential
Name:         self-referential
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2023-07-31T13:22:42Z
              crossplane.io/external-create-succeeded: 2023-07-31T13:22:43Z
              crossplane.io/external-name: sg-04de49106bb65ed05
API Version:  ec2.aws.crossplane.io/v1beta1
Kind:         SecurityGroup
Metadata:
  Creation Timestamp:  2023-07-31T13:22:10Z
  Finalizers:
    finalizer.managedresource.crossplane.io
  Generation:  3
  Managed Fields:
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:description:
          f:egress:
          f:groupName:
          f:ingress:
          f:region:
          f:tags:
          f:vpcIdRef:
            .:
            f:name:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-07-31T13:22:10Z
    API Version:  ec2.aws.crossplane.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-create-pending:
          f:crossplane.io/external-create-succeeded:
          f:crossplane.io/external-name:
        f:finalizers:
          .:
          v:"finalizer.managedresource.crossplane.io":
      f:spec:
        f:forProvider:
          f:vpcId:
      f:status:
        .:
        f:atProvider:
          .:
          f:ownerId:
          f:securityGroupID:
        f:conditions:
    Manager:         crossplane-aws-provider
    Operation:       Update
    Time:            2023-07-31T13:22:43Z
  Resource Version:  13381
  UID:               51628ce2-d7ca-48c6-bf8e-49ddf688f59c
Spec:
  Deletion Policy:  Delete
  For Provider:
    Description:  Allow all communication between instances
    Egress:
      From Port:    0
      Ip Protocol:  -1
      Ip Ranges:
        Cidr Ip:      0.0.0.0/0
        Description:  everywhere
      To Port:        56535
    Group Name:       self-referential
    Ingress:
      From Port:    0
      Ip Protocol:  -1
      To Port:      56535
      User Id Group Pairs:
        Description:  Allowing Cache port Inbound Access
        Group Id Selector:
          Match Controller Ref:  true
          Policy:
            Resolution:  Optional
            Resolve:     Always
    Region:              us-west-2
    Tags:
      Key:    Name
      Value:  self-referential
    Vpc Id:   vpc-09650a27b9639d041
    Vpc Id Ref:
      Name:  my-vpc
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
    Owner Id:           966122790603
    Security Group ID:  sg-04de49106bb65ed05
  Conditions:
    Last Transition Time:  2023-07-31T13:22:45Z
    Message:               update failed: failed to authorize ingress rules: api error MissingParameter: Source group ID missing.
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
    Last Transition Time:  2023-07-31T13:22:42Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
Events:
  Type     Reason                           Age                    From                                         Message
  ----     ------                           ----                   ----                                         -------
  Warning  CannotResolveResourceReferences  4m17s (x5 over 4m32s)  managed/securitygroup.ec2.aws.crossplane.io  cannot resolve references: mg.Spec.ForProvider.VPCID: cannot get referenced resource: VPC.ec2.aws.crossplane.io "MY-vpc" not found
  Warning  CannotResolveResourceReferences  4m15s                  managed/securitygroup.ec2.aws.crossplane.io  cannot resolve references: mg.Spec.ForProvider.VPCID: referenced field was empty (referenced resource may not yet be ready)
  Normal   CreatedExternalResource          3m59s                  managed/securitygroup.ec2.aws.crossplane.io  Successfully requested creation of external resource
  Warning  CannotUpdateExternalResource     55s (x4 over 3m57s)    managed/securitygroup.ec2.aws.crossplane.io  failed to authorize ingress rules: api error MissingParameter: Source group ID missing.
```

### What environment did it happen in?
Crossplane version:  v1.12.2
Provider AWS version: v0.41.1
Kubernetes version: v1.21.1
Kubernetes distribution: kind
OS: Ubuntu
Kernel: 5.19.0-50-generic
