### ISSUE TITLE
DynamoDB observe failed on isUpToDate function

### ISSUE THREAD

**Issue by kelvinwijaya** [crossplane-contrib/provider-aws#1823]
### What happened?
DynamoDB observe failed on isUpToDate function
I believe this happens for newer implemented function like postUpdate as well

Error:
```
status:
  atProvider:
    creationDateTime: "2023-08-01T13:36:54Z"
    itemCount: 0
    tableARN: arn:aws:dynamodb:us-east-1:123456789012:table/mytable
    tableID: {masked}
    tableName: mytable
    tableSizeBytes: 0
    tableStatus: ACTIVE
  conditions:
  - lastTransitionTime: "2023-08-01T13:36:54Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-08-01T13:37:00Z"
    message: 'observe failed: isUpToDate check failed: TableNotFoundException: Table
      not found: mytable-447bc-dgx5t'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?
Create manifest via Claim Resource to compose Table object. 
While observe the Table object, it is reference via Composite name rather then using External name

### What environment did it happen in?
Crossplane version: v0.42.0
