### ISSUE TITLE
HostedZone  0.42.0 1.13.1 resourceId Member must have length less than or equal to 32

### ISSUE THREAD

**Issue by fixdigitalinc** [crossplane-contrib/provider-aws#1826]
### What happened?
I tried today for a verry long time to get a route53 zone to work and i ran into several problems.

I created a new HostedZone and applied the crd via argo the result was the zone was created but was never synced. Thje zone id matched the one it was complaing that it cannot find.

```
Cannot observe external resource	{"controller": "managed/hostedzone.route53.aws.crossplane.io", "request": "/iac-r53-fixdigitalinc", "uid": "50fc6911-73a2-4877-9108-2f5ddbe6d493", "version": "2485475", "external-name": "Z0492315G9Y5I36O1E7O", "error": "cannot list tags: NoSuchHostedZone: No hosted zone found with ID: /hostedzone/Z0492315G9Y5I36O1E7O", "errorVerbose": "NoSuchHostedZone: No hosted zone found with ID:
```

After a few atempts after argo+crossplane manged to create 5-6 zones now i'm getting this error.

```
2023-08-03T01:29:42.379Z	DEBUG	events	cannot list tags: InvalidInput: 1 validation error detected: Value '/hostedzone/Z09546752YPG9QI64P1DF' at 'resourceId' failed to satisfy constraint: Member must have length less than or equal to 32	{"type": "Warning", "object": {"kind":"HostedZone","name":"iac-r53-fixdigitalinc","uid":"75a35828-e3cb-44a9-80ce-41edd1176f8f","apiVersion":"route53.aws.crossplane.io/v1alpha1","resourceVersion":"2497014"}, "reason": "CannotObserveExternalResource"}
```

```yaml
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: iac-r53-fixdigitalinc
  namespace: crossplane-system
spec:
  deletionPolicy: Orphan
  forProvider:
    name: fixdigitalinc.com
  providerConfigRef:
    name: aws-ff-dev
```

### What environment did it happen in?
Crossplane version:  1.13.1

**Comment by igorvinnicius** [comment]
Hi,

I'm facing the same issue after migrating to v0.42.0.

The Hosted Zone never gets Synced with this error:

```
observe failed: cannot list tags: InvalidInput: 1 validation error detected: Value '/hostedzone/Z07380063M8FHLN05CID6' at 'resourceId' failed to satisfy constraint: Member must have length less than or equal to 32
``` 

![image](https://github.com/crossplane-contrib/provider-aws/assets/5315511/570e7d9c-c13b-4e40-b9ed-675f22c8169f)

![image](https://github.com/crossplane-contrib/provider-aws/assets/5315511/bc8f4fde-4e00-4f73-be71-fa6e9af9d2ca)

I want to add also that you can introduce tags to your Hosted Zone, but they are not added in AWS:

```
apiVersion: route53.aws.crossplane.io/v1alpha1
kind: HostedZone
metadata:
  name: test-internal
spec:
  forProvider:
    name: test.internal
    vpc:
      vpcId: <vpc>
      vpcRegion: <region>
    tags:
      name: "test"
``` 

![image](https://github.com/crossplane-contrib/provider-aws/assets/5315511/97b894dc-2436-4ac6-9409-ba134bfa317d)

Thank you.
