### ISSUE TITLE
[DBInstance] Needs namespace "crossplane-system" to store values in cache (version 0.42)

### ISSUE THREAD

**Issue by WolfGanGeRTech** [crossplane-contrib/provider-aws#1834]
### What happened?
After the upgrade for version 0.42 I am not able to create new RDS due to error:

```
    "Message: create failed: pre-create failed: cannot cache password: cannot create object: namespaces "crossplane-system" not found"
```

This is probably due to the refactor of the password cache ( https://github.com/crossplane-contrib/provider-aws/pull/1756 ) cc. @schroeder-paul / @MisterMX . It seems the Cache namespace is not fetching the namespace from "masterUserPasswordSecretRef", so the fix seems to be something simple. 

I am using:

```
    masterUserPasswordSecretRef:
      key: password
      name: example-dbinstance
      namespace: default
```
So, I guess Crossplane should use that namespace for caching.

### How can we reproduce it?

Here is the manifest applied

```
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: example-dbinstance
spec:
  forProvider:
    region: eu-central-1
    allocatedStorage: 20
    dbName: example
    engine: postgres
    engineVersion: "12.9"
    dbInstanceClass: db.t3.micro
    masterUsername: adminuser
    masterUserPasswordSecretRef:
      key: password
      name: example-dbinstance
      namespace: default
  writeConnectionSecretToRef:
    name: example-dbinstance-out
    namespace: default
  providerConfigRef:
    name: example

---
apiVersion: v1
kind: Secret
metadata:
  name: example-dbinstance
  namespace: default
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
```

### What environment did it happen in?
Crossplane version: 0.42

Thanks for the help! :)
