### ISSUE TITLE
EFS can't update tags if backups are enabled

### ISSUE THREAD

**Issue by denniskorbginski** [crossplane-contrib/provider-aws#1847]
### What happened?
I'm creating an EFS Filesystem with backups enabled. AWS will then automatically apply the tag "aws:elasticfilesystem:default-backup" to the file system (https://docs.aws.amazon.com/efs/latest/ug/awsbackup.html#automatic-backups).

When I'm now trying to update my tags, I get this error:
```
cannot remove tags: ValidationException: 1 validation error detected: Value '[Application, Environment, Name, aws:elasticfilesystem:default-backup]' at 'tagKeys' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 128, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: ^(?![aA]{1}[wW]{1}[sS]{1}:)([\p{L}\p{Z}\p{N}_.:/=+\-@]+)$]
```

I guess we need to exclude aws's internal tags from the [DiffTags function](https://github.com/crossplane-contrib/provider-aws/blob/release-0.42/pkg/controller/efs/tags.go#L92) so they don't end up in the add/remove arrays.

### How can we reproduce it?
Create a Filesystem with automatic backups enabled like the one below. Afterwards, update one of its tags.
```yaml
apiVersion: efs.aws.crossplane.io/v1alpha1
kind: FileSystem
spec:
  forProvider:
    region: eu-central-1
    encrypted: true
    backup: true
    tags:
      - key: Name
        value: my-efs
```

### What environment did it happen in?
Crossplane version: 0.42.0
