### ISSUE TITLE
IAM Role creation fails when tags are being patched through

### ISSUE THREAD

**Issue by jpgrego** [crossplane-contrib/provider-aws#1854]
### What happened?

I have a composition that creates an IAM role. This IAM role has some tags patched in the following way:
```
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example-composition
spec:
(...)
  resources:
  - name: iam-default-role
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Role
      forProvider:
        tags:
        - key: company.org/location
          value: to_be_patched
        - key: company.org/namespace
          value: to_be_patched
        - key: company.org/cost-center
          value: fdz
        - key: company.org/product
          value: to_be_patched
        - key: company.org/owner
          value: to_be_patched
        - key: company.org/managed-by
          value: crossplane
        - key: company.org/component
          value: s3
    patches:
    - type: FromEnvironmentFieldPath
      fromFieldPath: location
      toFieldPath: spec.forProvider.tags[0].value
    - type: FromEnvironmentFieldPath
      fromFieldPath: xpCombine.namespace
      toFieldPath: spec.forProvider.tags[1].value
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[xp-combine/cost-center]
      toFieldPath: spec.forProvider.tags[2].value
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.product
      toFieldPath: spec.forProvider.tags[3].value
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.annotations[xp-combine/tenant]
      toFieldPath: spec.forProvider.tags[4].value
```

The IAM role creation fails. Upon describing the composite object I can see the following event being spewed out.
```
  Warning  ComposeResources         13s                defined/compositeresourcedefinition.apiextensions.crossplane.io  composed resource "iam-default-role": cannot use dry-run create to name composed resource: Role.iam.aws.crossplane.io "test-grego-n7nn8-5xlcp" is invalid: [spec.forProvider.tags[0].key: Required value, spec.forProvider.tags[1].key: Required value, spec.forProvider.tags[2]: Invalid value: "null": spec.forProvider.tags[2] in body must be of type object: "null", spec.forProvider.tags[3].key: Required value]
```

Upon some investigation I have discovered this managed resource has some default tags being applied, and I suspect this is somehow messing with my patching, probably because the order is changed around. But even so I'd expect to see wrong values in the wrong keys, not keys apparently being unset.

I already have a workaround: patching the whole `tags` field from another source (for example, an `EnvironmentConfig`) allows me to set the keys in place - with bogus `to_be_patched` values -  and patch the values in the composition. The default tags go to the end of the array.

But am I wrong in having the expectation that something like I described above should work correctly, and merge with the default tags? Is there a different way I should proceed in adding these tags?

### How can we reproduce it?

Simply attempt to create a IAM role in a composition and patching some custom tag values.

### What environment did it happen in?
Crossplane version: v1.12.2
provider-aws version: v0.42.0
Kubernetes version: 1.23
Kubernetes distribution: EKS
OS: Amazon Linux 2
Kernel: 5.10.186-179.751.amzn2.x86_64

**Comment by MisterMX** [comment]
@jpgrego can you give us the YAML of the actual managed resource that fails to create?

**Comment by jpgrego** [comment]
Hi @MisterMX ! Apologies for the late response.

Not sure if I understood your request. No managed resource for IAM role and policies are ever created.
When I describe the composed resource, I get no references for those. I get them for others though, like the bucket itself.

```
  Resource Refs:
    API Version:  s3.aws.crossplane.io/v1beta1
    Kind:         Bucket
    Name:         test-grego-68x7m-bdbl5
    API Version:  iam.aws.crossplane.io/v1beta1
    Kind:         Role
    API Version:  iam.aws.crossplane.io/v1beta1
    Kind:         Policy
    API Version:  iam.aws.crossplane.io/v1beta1
    Kind:         Policy
```

**Comment by MisterMX** [comment]
Looking at the error message above this does not seem like a provider problem to me. It looks more like the passed tags don't match the expected API schema: `key` and `value` are required and the tag object must not be null.

**Comment by jpgrego** [comment]
But that's the thing. As far as I'm aware I'm respecting the schema. I place the keys in the body of the resource and then just patch the values. These very same patches work perfectly if, instead of placing the keys here...
```
      forProvider:
        tags:
        - key: company.org/location
          value: to_be_patched
```
... I instead patch them from an `EnvironmentConfig` (that essentially includes exactly the same information) and then patch the values the very same way as I'm doing here.

Thank you very much for your questions. Let me know if I'm being confusing, I can try to clarify better what I'm facing and what I was expecting to occur.

**Comment by MisterMX** [comment]
The error you have comes from K8s which checks your object against the schema.

I just had another look at your code and in your base you put `forProvider` into top level instead inside `spec`:

```yaml
  resources:
  - name: iam-default-role
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Role
      forProvider:
        tags:
        - key: company.org/location
          value: to_be_patched
        - key: company.org/namespace
          value: to_be_patched
        - key: company.org/cost-center
          value: fdz
        - key: company.org/product
          value: to_be_patched
        - key: company.org/owner
          value: to_be_patched
        - key: company.org/managed-by
          value: crossplane
        - key: company.org/component
          value: s3
```

It should be:

```yaml
  resources:
  - name: iam-default-role
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Role
      spec:   # <------- This is missing
        forProvider:
          tags:
          - key: company.org/location
            value: to_be_patched
          - key: company.org/namespace
            value: to_be_patched
          - key: company.org/cost-center
            value: fdz
          - key: company.org/product
            value: to_be_patched
          - key: company.org/owner
            value: to_be_patched
          - key: company.org/managed-by
            value: crossplane
          - key: company.org/component
          value: s3
```

Because of that only the info from the patches is copied into the right location but you are missing everything else. And due to that your object does not match the expected schema.
