### ISSUE TITLE
ECR ReplicationConfiguration not working as expected

### ISSUE THREAD

**Issue by invalidred** [crossplane-contrib/provider-aws#1877]
### What happened?

I am using `provider-aws-ecr` and having issues with **ReplicationConfiguration** where when I add _repositoryFilter_ array, I get the following error

> CannotObserveExternalResource  38s (x16 over 12m)  managed/ecr.aws.upbound.io/v1beta1, kind=replicationconfiguration  cannot run refresh: refresh failed: Insufficient destination blocks: A │
│ t least 1 "destination" blocks are required.   

I am following the [ReplicationConfiguration Schema](https://marketplace.upbound.io/providers/upbound/provider-aws-ecr/v0.40.0/resources/ecr.aws.upbound.io/ReplicationConfiguration/v1beta1) and I should be able to have `rule` with `destination` and `reposityFilter`. However whenever I add `respositoryFilter` I get the error above.

```
apiVersion: ecr.aws.upbound.io/v1beta1
kind: ReplicationConfiguration
metadata:
  name: peo-server-repo
spec:
  forProvider:
    region: us-west-2
    replicationConfiguration:
      - rule:
          - destination:
              - region: us-west-2
                registryId: '757190845455'
          - repositoryFilter:
              - filter: peo-server-repo-prod
                filterType: PREFIX_MATCH
  providerConfigRef:
    name: aws-provider
```

### How can we reproduce it?

```
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ecr
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ecr:v0.40.0
  controllerConfigRef:
    name: aws-config
---
apiVersion: ecr.aws.upbound.io/v1beta1
kind: Repository
metadata:
  name: peo-server-repo
spec:
  forProvider:
    imageScanningConfiguration:
      - scanOnPush: false
    imageTagMutability: IMMUTABLE
    region: us-west-2
    tags:
      team: peo
      env: dev
  providerConfigRef:
    name: aws-provider
---
apiVersion: ecr.aws.upbound.io/v1beta1
kind: ReplicationConfiguration
metadata:
  name: peo-server-repo
spec:
  forProvider:
    region: us-west-2
    replicationConfiguration:
      - rule:
          - destination:
              - region: us-west-2
                registryId: '757190845455'
          - repositoryFilter:
              - filter: peo-server-repo-prod
                filterType: PREFIX_MATCH
  providerConfigRef:
    name: aws-provider
---
```

### What environment did it happen in?
Crossplane version: 1.13

* Cloud provider or hardware configuration: EKS m5.large
* Kubernetes version: 1.27
* Kubernetes distribution: EKS
* OS: bottlerocket
* Kernel: latest bottlerocket os
-->
