### ISSUE TITLE
securityGroupIdRefs ignored on ReplicationGroup

### ISSUE THREAD

**Issue by andy-townsend** [crossplane-contrib/provider-aws#1878]
### What happened?

Initially created a ReplicationGroup CR with a single security group configured. This was created successfully. An additional SecurityGroup CR was then created/applied and then the ReplicationGroup CR was then updated to have a second securityGroupIdRefs (of the newly created group) and applied. The security group was created successfully but it was not attached to the ReplicationGroup.

### How can we reproduce it?

Here's the ReplicationGroup CR that was first applied. 

```
apiVersion: 'cache.aws.crossplane.io/v1beta1'
kind: 'ReplicationGroup'
metadata:
  name: 'atownsend-test-redis'
spec:
  deletionPolicy: 'Delete'
  providerConfigRef:
    name: 'aws'
  providerRef:
    name: 'aws'
  writeConnectionSecretToRef:
    name: 'atownsend-test-redis'
    namespace: 'flux-system'
  forProvider:
    replicationGroupDescription: 'atownsend-test-redis'
    applyModificationsImmediately: true
    authEnabled: true
    transitEncryptionEnabled: true
    atRestEncryptionEnabled: true
    cacheNodeType: 'cache.t3.micro'
    engine: 'redis'
    engineVersion: '6.x'
    cacheSubnetGroupName: 'dev-data'
    numCacheClusters: 1
    automaticFailoverEnabled: false
    region: 'eu-west-1'
    securityGroupIdRefs:
      - name: 'dev-elasticache-sg'
```

Here's the CR for the SecurityGroup.
```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: custom-rules-atownsend-test-redis
spec:
  deletionPolicy: Delete
  forProvider:
    description: rds access from custom ip ranges
    groupName: custom-rules-atownsend-test-redis
    ingress:
    - fromPort: 6379
      ipProtocol: tcp
      ipRanges:
      - cidrIp: 10.1.0.0/24
        description: testing additional rules
      toPort: 6379
  providerConfigRef:
    name: aws
  providerRef:
    name: aws
```

And then the ReplicationGroup CR was updated to read. (the securityGroupIds had been auto-populated). 

```
    securityGroupIdRefs:
    - name: dev-elasticache-sg
    - name: customer-trial-andy-townsend-dev-test-redis
    securityGroupIds:
    - sg-0f6d83b89b51af649
```

If I edit the ReplicationGroup CR and remove the securityGroupIds but leave the 2 entries for securityGroupIdRefs then it goes ahead and attaches both security groups. 

### What environment did it happen in?
Crossplane version: crossplanecontrib/provider-aws:v0.42.0
Kubernetes Version: v1.25.12

**Comment by MisterMX** [comment]
> If I edit the ReplicationGroup CR and remove the securityGroupIds but leave the 2 entries for securityGroupIdRefs then it goes ahead and attaches both security groups.

This is the default behaviour of referencers: `securityGroupIds` is only updated if it is nil.
To change this behaviour you have to set the resolve policy to `Always`:

```yaml
    securityGroupIdRefs:
    - name: dev-elasticache-sg
      policy:
        resolve: Always
    - name: customer-trial-andy-townsend-dev-test-redis
      policy:
        resolve: Always
```

Closing this as it is not a bug but intended behaviour.
