### ISSUE TITLE
SecurityGroupRule prefixListId is ignored

### ISSUE THREAD

**Issue by LCaparelli** [crossplane-contrib/provider-aws#1880]
### What happened?

When attempting to create a SecurityGroupRule, `.spec.forProvider.prefixListId` is never used and runs into 400:
```
  - lastTransitionTime: "2023-09-28T19:34:06Z"
    message: 'create failed: operation error EC2: AuthorizeSecurityGroupIngress, https
      response error StatusCode: 400, RequestID: 0000,
      api error MissingParameter: Missing source specification: include source security
      group or CIDR information'
    reason: ReconcileError
    status: "False"
    type: Synced
```

### How can we reproduce it?

Apply the following, replacing region and VPC ID with valid ones:
```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: cloudfront
spec:
  deletionPolicy: Delete
  forProvider:
    description: SG to allow traffic from origin-facing CloudFront instances
    groupName: cloudfront
    vpcId: <some VPC id>
    tags:
      - key: Name
        value: Cloudfront
---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: cloudfront-ingress
spec:
  deletionPolicy: Delete
  forProvider:
    description: Allow access from origin-facing cloufront instances
    type: ingress
    region: <a valid region>
    fromPort: 443
    toPort: 443
    protocol: tcp
    prefixListId: pl-3b927c52 # origin-facing cloufront prefix list
    securityGroupIdRef:
      name: cloudfront
      policy:
        resolution: Required
        resolve: Always
```

### What environment did it happen in?
Crossplane version: v1.13
provider-aws version: v0.41.1

PS: looks like we really don't check this field at all when creating or updating:
https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/controller/ec2/securitygrouprule/controller.go
```
❯ grep -i prefix pkg/controller/ec2/securitygrouprule/controller.go -c
0
```
