### ISSUE TITLE
Unable to update MSK cluster policy after creation

### ISSUE THREAD

**Issue by aleicher** [crossplane-contrib/provider-aws#1920]
### What happened?

You create a new AWS MSK Kafka Cluster using the `Cluster.kafka.aws.crossplane.io` resource and set a valid clusterPolicy in `.spec.forProvider.clusterPolicy`, then the clusterPolicy will be properly applied to the Cluster. Then you proceed and make a small update to the clusterPolicy, the update will fail and cannot be applied with the error message:

```
            update failed: cannot put cluster policy: BadRequestException: Current cluster policy version needed for Update
            {
              RespMetadata: {
                StatusCode: 400,
                RequestID: "31d2c790-fd65-43d1-a27a-3ea6e733f953"
              },
              Message_: "Current cluster policy version needed for Update"
            }

```
The expected behaviour would be that the change in the clusterPolicy can be applied to the cluster without issues.

The same/similar issue already existed in the terraform aws-provider (https://github.com/hashicorp/terraform-provider-aws/issues/33107). AWS expects the current policy version when updating an existing clusterPolicy (while it is optional to provide the currentVersion parameter when it is first created).

### How can we reproduce it?

1. Create a new AWS MSK Cluster which has a clusterPolicy attached:

manifests based on the examples from https://github.com/crossplane-contrib/provider-aws/tree/v0.44.0/examples/kafka
```
apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    clusterName: example
    clusterPolicy:
      version: "2012-10-17"
      statements:
        - action:
          - kafka-cluster:Connect
          - kafka-cluster:AlterCluster
          - kafka-cluster:DescribeCluster
          effect: Allow
          principal:
            awsPrincipals:
            - iamRoleArn: arn:aws:iam::xxxxxxxxx:role/example
          resource:
          - arn:aws:kafka:eu-central-1:xxxxxx:cluster/example.....
    region: eu-central-1
    brokerNodeGroupInfo:
      clientSubnetRefs:
        - name: sample-subnet1
        - name: sample-subnet2
      securityGroupRefs:
        - name: sample-cluster-sg
      instanceType: kafka.t3.small
      storageInfo: 
        ebsStorageInfo:
          volumeSize: 1
    kafkaVersion: 2.6.1
    configurationInfo:
      arnRef:
        name: example-configuration
      revision: 1
    numberOfBrokerNodes: 2
    tags:
      myKey: myValue
  providerConfigRef:
    name: example
---
apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: example-configuration
spec:
  forProvider:
    region: eu-central-1
    kafkaVersions:
      - 2.6.1
    properties: 
      - auto.create.topics.enable=false
      - default.replication.factor=3
      - min.insync.replicas=2
      - num.io.threads=8
      - num.network.threads=5
      - num.partitions=1
      - num.replica.fetchers=2
      - replica.lag.time.max.ms=30000
      - socket.receive.buffer.bytes=102400
      - socket.request.max.bytes=104857600
      - socket.send.buffer.bytes=102400
      - unclean.leader.election.enable=true
      - zookeeper.session.timeout.ms=18000
  providerConfigRef:
    name: example
```

2. After rollout of the Cluster and Configuration, both are created fine, and the clusterPolicy is set on the MSK Cluster.
3. modify the `spec.forProvider.clusterPolicy`, e.g. by removing an action from the statement:

```
apiVersion: kafka.aws.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    clusterName: example
    clusterPolicy:
      version: "2012-10-17"
      statements:
        - action:
          - kafka-cluster:Connect
          effect: Allow
          principal:
            awsPrincipals:
            - iamRoleArn: arn:aws:iam::xxxxxxxxx:role/example
          resource:
          - arn:aws:kafka:eu-central-1:xxxxxx:cluster/example.....
    region: eu-central-1
    brokerNodeGroupInfo:
      clientSubnetRefs:
        - name: sample-subnet1
        - name: sample-subnet2
      securityGroupRefs:
        - name: sample-cluster-sg
      instanceType: kafka.t3.small
      storageInfo: 
        ebsStorageInfo:
          volumeSize: 1
    kafkaVersion: 2.6.1
    configurationInfo:
      arnRef:
        name: example-configuration
      revision: 1
    numberOfBrokerNodes: 2
    tags:
      myKey: myValue
  providerConfigRef:
    name: example
```

4. Apply the modified manifest
5. The Cluster cannot be updated, and the error will be shown that the current version needs to be provided

```
            update failed: cannot put cluster policy: BadRequestException: Current cluster policy version needed for Update
            {
              RespMetadata: {
                StatusCode: 400,
                RequestID: "31d2c790-fd65-43d1-a27a-3ea6e733f953"
              },
              Message_: "Current cluster policy version needed for Update"
            }
```

### What environment did it happen in?
Crossplane version: v0.44.1
K8S version: v1.24.16-eks-2d98532
