### ISSUE TITLE
Support the ability to create the same ECR Repository in multiple regions

### ISSUE THREAD

**Issue by brandocomando** [crossplane-contrib/provider-aws#1977]
### What problem are you facing?
Currently it is not possible to manage ECR repositories in multiple regions with the same name from a single k8s cluster.
I feel it is a very common configuration for teams operating in multiple aws regions to have ECR replication enabled so that images pushed to one region get replicated to other regions.

Because the name of the ECR repo is tied to the name of the k8s object I cant create the same repo in multiple regions. 

### How could Crossplane help solve your problem?
I'm thinking the best path forward would be to add a new property to the forProvider object called something like awsName.

This would allow you to have 2 objects with different names and regions, but the same awsName resulting in the same repository being created in multiple regions.

for example:
```
apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: repo1-us-east-2
spec:
  forProvider:
    awsName: repo1
    region: us-east-2
---
apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: repo1-us-west-2
spec:
  forProvider:
    awsName: repo1
    region: us-west-2   
```
