### ISSUE TITLE
Secret MR does not get deleted directly anymore

### ISSUE THREAD

**Issue by wotolom** [crossplane-contrib/provider-aws#1978]
### What happened?

Due to this change to the ACK generated controllers https://github.com/crossplane-contrib/provider-aws/pull/1924,
MR `Secrets` stay in cluster after deletion, until `recoveryWindowInDays` (default 30 days) is passed. Also during this time the controller seems to keep sending deletion-calls.

Previously this was handled by this code block in `postObserve()` by looking if the secret is delete in AWS "frontend":
https://github.com/crossplane-contrib/provider-aws/blob/6e24fa15610961378e22aeddd0dbd148909e0c39/pkg/controller/secretsmanager/secret/setup.go#L125-L130

But now `postObserve()` is skipped through this change in the generated controller:
https://github.com/crossplane-contrib/provider-aws/blob/6e24fa15610961378e22aeddd0dbd148909e0c39/pkg/controller/secretsmanager/secret/zz_controller.go#L92-L97

### How can we reproduce it?
```yaml
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: example-secret
spec:
  forProvider:
    region: eu-central-1
    # forceDeleteWithoutRecovery: true # default is false
    # recoveryWindowInDays: 7 # AWS default is apparently 30 (https://doc.crds.dev/github.com/crossplane-contrib/provider-aws/secretsmanager.aws.crossplane.io/Secret/v1beta1@v0.45.2)
    stringSecretRef:
      key: password
      name: example-secret-manager
      namespace: crossplane-system
    tags:
      - key: secret
        value: "secret"
  providerConfigRef:
    name: example
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret-manager
  namespace: crossplane-system
type: Opaque
data:
  password: dGVzdFBhc3N3b3JkITEyMw== # testPassword!123
```

### What environment did it happen in?
Crossplane version: v1.14.4
provider-aws v0.45.2 + master
