### ISSUE TITLE
Update-Loop when setting `awsAccountId` to just account ID

### ISSUE THREAD

**Issue by wotolom** [crossplane-contrib/provider-aws#1984]
### What happened?

Potentially not only affecting `kafka.Cluster`, but also other resources using the same inline policy format

When setting a `clusterPolicy` with a statement using `clusterPolicy.statements.principal.awsPrincipals.awsAccountId` AWS seems to accept either just the account ID ("123456789012") or the full account ARN ("arn:aws:iam::123456789012:root").
However the controller does not see these as identical, resulting in an update-loop, if the user sets `awsAccountId` to just the account ID

same update-loop behaviour is probably to be expected for equivalent under `notPrincipal`

### How can we reproduce it?

example `spec.forProvider.clusterPolicy` for a `kafka.Cluster`:

```
...
clusterPolicy:
      version: '2012-10-17'
      statements:
        - sid: 'AccountAccess'
          action:
            - "kafka:CreateVpcConnection"
            - "kafka:GetBootstrapBrokers"
            - "kafka:DescribeCluster"
            - "kafka:DescribeClusterV2"
          effect: 'Allow'
          resource:
            - 'arn:aws:kafka:eu-central-1:123456789012:cluster/<cluster-name>/<cluster-uiid>'
          principal:
            awsPrincipals:
              - awsAccountId: 'arn:aws:iam::123456789012:root' # only id 123456789012 works but results in update-loop
...
``` 

### What environment did it happen in?
Crossplane version: v1.14.5
provider-aws: v0.46.0
