### ISSUE TITLE
Cannot create RDS DBInstance when autogeneratePassword - clean instance

### ISSUE THREAD

**Issue by JaniszM** [crossplane-contrib/provider-aws#1997]
### What happened?

Using ArgoCD.

Creating a clean DB, without a restoration point, and with the master password being generated.

Got error:

```
cannot create DBInstance in AWS: InvalidParameterValue: Invalid master password status code: 400, request id: 
```

Seems the problem might be the silent error ignorance for missing k8s Secrets (masterUserPasswordSecretRef).
https://github.com/crossplane-contrib/provider-aws/blob/f759905dcba680015d0a3689a7afc58ac09abf7c/pkg/controller/docdb/dbcluster/setup.go#L229
(thanks @sysradium for that check)

Creating the secret and the key didn't solve the problem, the password was not generated. I have provided a password by hand.

To get the Instance I had to create the secret and put a valid password over there.

### How can we reproduce it?

This can help, my resource params:

```
forProvider:
    allocatedStorage: 20
    allowMajorVersionUpgrade: false
    autogeneratePassword: true
    dbInstanceClass: db.t3.micro
    dbParameterGroupName: db-mysql-group
    dbParameterGroupNameRef:
      name: db-mysql-group
    dbSubnetGroupName: db-mysql-sng
    dbSubnetGroupNameRef:
      name: db-mysql-sng
    dbSubnetGroupNameSelector:
      matchControllerRef: true
      matchLabels:
        environment: dev
        instance: db-mysql
    enableIAMDatabaseAuthentication: true
    engine: mysql
    engineVersion: 5.7.42
    masterUserPasswordSecretRef:
      key: password
      name: db-mysql-pass
      namespace: dev
    masterUsername: admin
    multiAZ: false
    region: eu-central-1
    skipFinalSnapshot: true
    storageType: gp2
    tags:
      - key: Creator
        value: Crossplane
      - key: Name
        value: db-mysql
      - key: Environment
        value: dev
    vpcSecurityGroupIDRefs:
      - name: db-mysql-sg
    vpcSecurityGroupIDSelector:
      matchControllerRef: true
      matchLabels:
        environment: dev
        instance: db-mysql
    vpcSecurityGroupIDs:
      - sg-
```

### What environment did it happen in?
Crossplane version: helm.sh/chart=crossplane-1.13.2
provider-aws: v0.43.1
EKS/k8s: v1.28

**Comment by sysradium** [comment]
We tried different combinations of secrets. No data:
```
apiVersion: v1
kind: Secret
metadata:
  name: db-mysql-somedb-demo-master-pass
  namespace: environments
type: Opaque
```
Empty data object:
```
apiVersion: v1
kind: Secret
data:
metadata:
  name: db-mysql-somedb-demo-master-pass
  namespace: environments
type: Opaque
```
Null password:
```
apiVersion: v1
kind: Secret
data:
  password:
metadata:
  name: db-mysql-somedb-demo-master-pass
  namespace: environments
type: Opaque
```
Empty password:
```
apiVersion: v1
kind: Secret
data:
  password: ""
metadata:
  name: db-mysql-somedb-demo-master-pass
  namespace: environments
type: Opaque
```
Nothing worked till we actually set it to some base64 representation of a pw.
