### ISSUE TITLE
s3 bucket settings not defined in the MR are removed after upgrade to v0.46.0

### ISSUE THREAD

**Issue by mprochnicki** [crossplane-contrib/provider-aws#1998]
### What happened?

I upgraded provider-aws from version 0.45.2 to version 0.46.0, this resulted in removal of s3 bucket settings that were not defined in MR manifest.

Unfortunately part of s3 bucket settings (notificationConfiguration) must be managed by separate tool outside of Crossplane, and this worked in previous versions.

Enabling management policies and using `["Observe", "Create", "Update", "Delete"]` didn't resolved the issue.

### How can we reproduce it?

1. Create s3 bucket using below manifest and provider-aws v0.45.2 (or older): 
``` yml
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bucket-name
spec:
  deletionPolicy: Delete
  forProvider:
    locationConstraint: us-east-1
    objectOwnership: BucketOwnerEnforced
    paymentConfiguration:
      payer: BucketOwner
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            kmsMasterKeyId: kms-key-id
            kmsMasterKeyIdRef:
              name: kms-key-name
            sseAlgorithm: aws:kms
          bucketKeyEnabled: true
    tagging:
      tagSet:
        - key: key
          value: value

```

2. Manually configure "Event Notifications" (notificationConfiguration)
3. Upgrade provider-aws to v0.46.0
4. Observe "Event Notifications" settings being removed

### What environment did it happen in?
Crossplane version: 1.14.5
