### ISSUE TITLE
Validation error updating Cloudfront distribution

### ISSUE THREAD

**Issue by djimenez-savi** [crossplane-contrib/provider-aws#2007]
### What happened?

Having created successfully a Cloudfront distribution and then trying to update the Distribution I am getting multiple validation errors.

> - missing required field, UpdateDistributionInput.DistributionConfig.Aliases.Quantity.
> - missing required field, UpdateDistributionInput.DistributionConfig.CacheBehaviors.Quantity.                                                                                                                                                                                     
> - missing required field, UpdateDistributionInput.DistributionConfig.CustomErrorResponses.Quantity.                                                                                                                                                                               
> - missing required field, UpdateDistributionInput.DistributionConfig.DefaultCacheBehavior.ForwardedValues.QueryStringCacheKeys.Quantity.                                                                                                                                          
> - missing required field, UpdateDistributionInput.DistributionConfig.DefaultCacheBehavior.FunctionAssociations.Quantity.                                                                                                                                                          
> - missing required field, UpdateDistributionInput.DistributionConfig.DefaultCacheBehavior.LambdaFunctionAssociations.Quantity.                                                                                                                                                    
> - missing required field, UpdateDistributionInput.DistributionConfig.DefaultCacheBehavior.TrustedKeyGroups.Quantity.                                                                                                                                                              
> - missing required field, UpdateDistributionInput.DistributionConfig.DefaultCacheBehavior.TrustedSigners.Quantity.                                                                                                                                                                
> - missing required field, UpdateDistributionInput.DistributionConfig.OriginGroups.Quantity.                                                                                                                                                                                       
> - missing required field, UpdateDistributionInput.DistributionConfig.Origins.Items[1].CustomHeaders.Quantity.                                                                                                                                                                     
> - missing required field, UpdateDistributionInput.DistributionConfig.Restrictions.GeoRestriction.Quantity.

### How can we reproduce it?

Create a Distribution applying the following manifest:

```
apiVersion: cloudfront.aws.crossplane.io/v1alpha1
kind: Distribution
metadata:
  name: distribution-example
spec:
  deletionPolicy: Delete
  forProvider:
    distributionConfig:
      comment: distribution-example
      defaultCacheBehavior:
        allowedMethods:
          cachedMethods:
            items:
              - GET
              - HEAD
          items:
            - DELETE
            - GET
            - POST
            - HEAD
            - OPTIONS
            - PATCH
            - PUT
        compress: false
        defaultTTL: 86400
        fieldLevelEncryptionID: ""
        forwardedValues:
          cookies:
            forward: all
          queryString: true
        maxTTL: 31536000
        minTTL: 0
        smoothStreaming: false
        targetOriginID: S3-coupon-templates
        viewerProtocolPolicy: redirect-to-https
      defaultRootObject: ""
      enabled: true
      httpVersion: http2
      isIPV6Enabled: true
      logging:
        bucket: ""
        enabled: false
        includeCookies: false
        prefix: ""
      origins:
        items:
          - connectionAttempts: 3
            connectionTimeout: 10
            domainName: valassis-sandbox-coupon-templates.s3.eu-west-1.amazonaws.com
            id: S3-coupon-templates
            originPath: ""
            originShield:
              enabled: false
            s3OriginConfig:
              originAccessIdentity: ""
      priceClass: PriceClass_All
      viewerCertificate:
        certificateSource: cloudfront
        cloudFrontDefaultCertificate: true
        minimumProtocolVersion: TLSv1
        sslSupportMethod: vip
      webACLID: ""
    region: eu-west-1
  providerConfigRef:
    name: default


```

Then modify any field, for example the comments field, reapply the manifest and see that the CR is not Synced and the errors are shown in the events.

### What environment did it happen in?
* Crossplane version: 1.15.0
* Provider-aws: 0.46.0
* Cloud provider AWS
* Kubernetes version 1.27.0
* Kubernetes distribution Kind
