### ISSUE TITLE
Elasticache provider does not populate connection secret

### ISSUE THREAD

**Issue by lefredlebel** [crossplane-contrib/provider-aws#2050]
### What happened?
While creating a new resource of kind `Cluster` with apiVersion `elasticache.aws.upbound.io/v1beta1`, the provider does not populate the secret from the `writeConnectionSecretToRef` section. The secret is created but is empty.

### How can we reproduce it?
```yaml
apiVersion: elasticache.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta1/cluster
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: redis-cluster
  name: redis-cluster
spec:
  forProvider:
    engine: redis
    engineVersion: "7.1"
    maintenanceWindow: sun:05:00-sun:09:00
    nodeType: cache.t3.micro
    numCacheNodes: 1
    parameterGroupName: default.redis7
    port: 6379
    region: eu-west-1
    securityGroupIds:
      - "sg-XXXXXXXXXXXX"
    subnetGroupName: "vpc-elasticache-subnet-group"
  writeConnectionSecretToRef:
    name: redis-cluster-connection
    namespace: sandbox
```

```
kubectl describe secret redis-cluster-connection --namespace sandbox
Name:         redis-cluster-connection
Namespace:    sandbox
Labels:       <none>
Annotations:  <none>

Type:  connection.crossplane.io/v1alpha1

Data
====
```

```
NAME                       TYPE                              DATA   AGE
redis-cluster-connection   connection.crossplane.io/v1alpha1   0      19h
```

### What environment did it happen in?
Crossplane version: 1.15.1

* Cloud provider : AWS
* Kubernetes version : 1.28
* Kubernetes distribution : AWS EKS
* ArgoCD version : v2.10.6+d504d2b
