### ISSUE TITLE
RDS aurora-postgresql Serverless Required Fields Bug

### ISSUE THREAD

**Issue by gl-af** [crossplane-contrib/provider-aws#2070]
Hey! I'm trying to create an RDS aurora-postgresql instance and am running into what I think is a bug. Here's a snippet of my composition:
```
- name: instantiate-db
  base:
    apiVersion: rds.aws.upbound.io/v1beta1
    kind: Instance
    spec:
      forProvider:
        #allocatedStorage: 20
        dbName: backstage
        engine: aurora-postgresql
        instanceClass: db.serverless
        storageEncrypted: true
        username: root
        manageMasterUserPassword: false
        passwordSecretRef:
           key: password
           name: backstage-postgres-secret
           namespace: orchestration
        autoGeneratePassword: true
        monitoringInterval: 60
        applyImmediately: true
        skipFinalSnapshot: true
        region: eu-west-1
        dbSubnetGroupNameSelector:
          matchControllerRef: true
        vpcSecurityGroupIDSelector:
          matchControllerRef: true
      writeConnectionSecretToRef:
        name: example-dbinstance-out
        namespace: orchestration
```

When I create a claim for this composition my instance fails to create with the following error: `{0 \"allocated_storage\": required field is not set  []}`
My understanding is this field should not be necessary given I'm using  instanceClass: `db.serverless`, so this seems like a bug to me.

In any case, if I do uncomment this field above, I then get this error: `InvalidParameterCombination: Invalid storage size for engine name aurora-postgresql and storage type aurora: 20`

Can anyone confirm this is a bug?

Thanks.
