### ISSUE TITLE
Subscriptions with filterPolicy set are in a SetSubscriptionAttributes loop

### ISSUE THREAD

**Issue by offzale** [crossplane-contrib/provider-aws#2071]
### What happened?
When creating a Subscription with the field `spec.forProvider.filterPolicy` set, the provider gets in a loop of SetSubscriptionAttributes AWS API calls trying to update that attribute. The resources are ready and synced.

All the API calls have the following requestParameters:
```
"requestParameters": {
        "subscriptionArn": "arn:aws:sns:eu-west-1:000123456789:example-subscription:<aws-resource-id>",
        "attributeName": "FilterPolicy",
        "attributeValue": "{ \"status\": [\"EXAMPLE\"] }\n"
    },
```

### How can we reproduce it?
Create a topic and a queue, then subscribe the queue to the topic setting the filterPolicy below.
```
apiVersion: sns.aws.crossplane.io/v1beta1
kind: Subscription
metadata:
  name: example
spec:
  deletionPolicy: Delete
  forProvider:
    endpoint: arn:aws:sqs:eu-west-1:000123456789:example-queue
    filterPolicy: |
      { "status": ["EXAMPLE"] }
    filterPolicyScope: MessageAttributes
    protocol: sqs
    rawMessageDelivery: "false"
    region: eu-west-1
    topicArn: arn:aws:sns:eu-west-1:000123456789:example-topic
  managementPolicies:
  - '*'
  providerConfigRef:
    name: aws
```

### What environment did it happen in?
Crossplane version: 1.16.0
Provider version: 0.9.0
