### ISSUE TITLE
can't create secondary Aurora DBCluster in Global Database

### ISSUE THREAD

**Issue by mlubanski** [crossplane-contrib/provider-aws#2072]
### What happened?
I would like to use crossplane to create RDS Aurora Global Database with primary and secondary Clusters

I was able to create Primary Global Database with Primary Cluster but having problem with secondary cluster:
- if I set a password in secondary DBCluster I am getting Warning Event `cannot create DBCluster in AWS: InvalidParameterCombination: Cannot specify password for cross region replication cluster`
- if password is not set I am getting Warning Event `pre-create failed: neither a masterUserPasswordSecretRef is given, nor password autogeneration was enabled, not a restore is performed`

### How can we reproduce it?

**Global Database & Primary Cluster**

```yaml
---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: GlobalCluster
metadata:
  annotations:
    crossplane.io/external-name: us1tst-eks001-crossplane-system-mysql-1-global
  name: mysql-1-d7gps-z9vv6
spec:
  deletionPolicy: Delete
  forProvider:
    deletionProtection: false
    region: us-east-1
    sourceDBClusterIdentifier: arn:aws:rds:us-east-1:xxxxxxxxxxxx:cluster:us1tst-eks001-crossplane-system-mysql-1
  managementPolicies:
  - '*'
  providerConfigRef:
    name: crossplane-provider-aws
---
kind: DBCluster
metadata:
  annotations:
    crossplane.io/external-name: us1tst-eks001-crossplane-system-mysql-1
  name: mysql-1-d7gps-nlv88
spec:
  deletionPolicy: Delete
  forProvider:
    applyImmediately: true
    autoMinorVersionUpgrade: true
    autogeneratePassword: true
    backupRetentionPeriod: 1
    copyTagsToSnapshot: true
    dbClusterParameterGroupName: us1tst-eks001-crossplane-system-mysql-1
    dbSubnetGroupName: private_subnets_vpc-xxxxxxxx
    deletionProtection: false
    enableCloudwatchLogsExports:
    - audit
    enableIAMDatabaseAuthentication: false
    engine: aurora-mysql
    globalClusterIdentifier: ""
    masterUsername: root
    preferredBackupWindow: 14:00-16:00
    preferredMaintenanceWindow: Mon:11:00-Mon:14:00
    region: us-east-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: aurora
    vpcSecurityGroupIDs:
    - sg-099ace154xxxxxxxx
  managementPolicies:
  - '*'
  providerConfigRef:
    name: crossplane-provider-aws
    name: crossplane-system-mysql-1-mysqlcluster
---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  annotations:
    crossplane.io/external-name: us1tst-eks001-crossplane-system-mysql-1-0
  name: mysql-1-d7gps-jq6gm
spec:
  deletionPolicy: Delete
  forProvider:
    applyImmediately: true
    autoMinorVersionUpgrade: true
    availabilityZone: us-east-1a
    caCertificateIdentifier: rds-ca-rsa2048-g1
    dbClusterIdentifier: us1tst-eks001-crossplane-system-mysql-1
    dbClusterIdentifierRef:
      name: mysql-1-d7gps-nlv88
    dbClusterIdentifierSelector:
      matchControllerRef: true
    dbInstanceClass: db.r6g.large
    dbSubnetGroupName: private_subnets_vpc-xxxxxxxx
    enableCloudwatchLogsExports:
    - audit
    enablePerformanceInsights: true
    engine: aurora-mysql
    kmsKeyID: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/51c9aca5-61e0-4b55-a3f0-xxxxxxxxxxxx
    licenseModel: general-public-license
    masterUsername: root
    multiAZ: false
    performanceInsightsKMSKeyID: arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/51c9aca5-61e0-4b55-a3f0-xxxxxxxxxxxx
    performanceInsightsRetentionPeriod: 7
    port: 3306
    preferredMaintenanceWindow: Mon:11:00-Mon:14:00
    promotionTier: 1
    publiclyAccessible: false
    region: us-east-1
    skipFinalSnapshot: true
    storageThroughput: 0
  managementPolicies:
  - '*'
  providerConfigRef:
    name: crossplane-provider-aws
```

**Secondary Cluster**
```yaml
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBCluster
metadata:
  annotations:
    crossplane.io/external-name: eu1tst-eks001-crossplane-system-mysql-1
  name: mysql-1-hnfjm-lszrh
spec:
  deletionPolicy: Delete
  forProvider:
    applyImmediately: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 1
    copyTagsToSnapshot: true
    dbClusterParameterGroupName: eu1tst-eks001-crossplane-system-mysql-1
    dbSubnetGroupName: private_net_vpc-xxxxxxxx
    deletionProtection: false
    enableCloudwatchLogsExports:
    - audit
    enableIAMDatabaseAuthentication: false
    engine: aurora-mysql
    globalClusterIdentifier: us1tst-eks001-crossplane-system-mysql-1-global
    masterUsername: ""
    preferredBackupWindow: 14:00-16:00
    preferredMaintenanceWindow: Mon:11:00-Mon:14:00
    region: eu-west-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: aurora
    vpcSecurityGroupIDs:
    - sg-0a92f8495xxxxxxxx
  managementPolicies:
  - '*'
  providerConfigRef:
    name: crossplane-provider-aws
```

**Status of Global Database & Primary Cluster**
```bash
$ crossplane beta trace --context us1tst-eks001 mysqlclusters -n crossplane-system mysql-1                                                                                                                                       NAME                                                       SYNCED   READY   STATUS
MySQLCluster/mysql-1 (crossplane-system)                   True     True    Available
└─ XMySQLCluster/mysql-1-d7gps                             True     True    Available
   ├─ LogGroup/mysql-1-d7gps-d9v9f                         True     True    Available
   ├─ SubscriptionFilter/mysql-1-d7gps-fvmwg               True     True    Available
   ├─ SecurityGroup/mysql-1-d7gps-lx72l                    True     True    Available
   ├─ Object/crossplane-system-mysql-1                     True     True    Available
   ├─ Database/crossplane-system-mysql-1-db1               True     True    Available
   ├─ Grant/crossplane-system-mysql-1-db1-ro-user          True     True    Available
   ├─ Grant/crossplane-system-mysql-1-db1-ro-user-global   True     True    Available
   ├─ Grant/crossplane-system-mysql-1-db1-rw-user          True     True    Available
   ├─ User/crossplane-system-mysql-1-db1-ro-user           True     True    Available
   ├─ User/crossplane-system-mysql-1-db1-rw-user           True     True    Available
   ├─ DBClusterParameterGroup/mysql-1-d7gps-nlzf2          True     True    Available
   ├─ DBCluster/mysql-1-d7gps-nlv88                        True     True    Available
   ├─ DBInstance/mysql-1-d7gps-jq6gm                       True     True    Available
   ├─ DBInstance/mysql-1-d7gps-zrg4z                       True     True    Available
   └─ GlobalCluster/mysql-1-d7gps-z9vv6                    True     True    Available
```
**Status of Secondary Cluster**
```bash
$ crossplane beta trace --context eu1tst-eks001 mysqlclusters -n crossplane-system mysql-1                                                                                                                                       NAME                                                SYNCED   READY   STATUS
MySQLCluster/mysql-1 (crossplane-system)            True     False   Waiting: Claim is waiting for composite resource to become Ready
└─ XMySQLCluster/mysql-1-hnfjm                      True     False   Creating: Unready resources: dbcluster, rds-ro, and rds-rw
   ├─ LogGroup/mysql-1-hnfjm-fdqnk                  True     True    Available
   ├─ SubscriptionFilter/mysql-1-hnfjm-tbwrr        True     True    Available
   ├─ SecurityGroup/mysql-1-hnfjm-nxqwl             True     True    Available
   ├─ DBClusterParameterGroup/mysql-1-hnfjm-9jjcv   True     True    Available
   ├─ DBCluster/mysql-1-hnfjm-lszrh                 False    False   ReconcileError: ...cross region replication cluster
                                                    status code: 400, request id:
   ├─ DBInstance/mysql-1-hnfjm-jcws2                False    False   ReconcileError: ...eks001-crossplane-system-mysql-1
                                                    status code: 404, request id:
   └─ DBInstance/mysql-1-hnfjm-qd7vh                False    False   ReconcileError: ...eks001-crossplane-system-mysql-1
                                                    status code: 404, request id:

kubectl --context eu1tst-eks001 describe dbclusters.rds.aws.crossplane.io mysql-1-hnfjm-lszrh
...
Events:
  Type     Reason                        Age                    From                                     Message
  ----     ------                        ----                   ----                                     -------
  Warning  CannotCreateExternalResource  6m58s (x251 over 57m)  managed/dbcluster.rds.aws.crossplane.io  pre-create failed: neither a masterUserPasswordSecretRef is given, nor password autogeneration was enabled, not a restore is performed
```

### What environment did it happen in?
Crossplane version: `1.16.0`
Crossplane AWS Provider: `crossplane-contrib/provider-aws:v0.48.1`

* Cloud provider: `AWS`
* Kubernetes version: `1.28.x`
* Kubernetes distribution: `EKS`
