### ISSUE TITLE
Nodegroup taints are not getting applied or removed

### ISSUE THREAD

**Issue by IonitaCatalin** [crossplane-contrib/provider-aws#2128]
### What happened?

We have an entire EKS cluster created via a Composition. This composition creates a specialised nodegroup which is meant to run Karpenter  controller's replicas, this nodegroup was supposed to be tainted but due to an error the nodegroup was not tainted  when creating. 
In an attempt to fix this issue we created a new version of the composition in which the nodegroup has the taints like so:

```
 spec:
   forProvider:   
      taints:
        - effect: NO_SCHEDULE
          key: karpenter
          value: owned
```

This applied the taints for the cluster-local nodegroup.eks.aws.crossplane.io but the cloud counterpart was not updated accordingly.

### How can we reproduce it?

Create a new nodegroup, and try to taint it post creation. The new taints are not applied.

### What environment did it happen in?

Crossplane version: 1.16.2
provider-aws version: 0.48.1
Kubernetes version: 1.31.2
