### ISSUE TITLE
Error reconciling RabbitMQ configuration

### ISSUE THREAD

**Issue by MatthiasDrews** [crossplane-contrib/provider-aws#2166]
### What happened?

I want to provision a configuration for AWS RabbitMQ, with additional configuration options in the "data" field. The configuration was correctly created, initially without the options specified in the "data" field.
Then there are errors while observing:

`Cannot observe external resource	{"controller": "managed/configuration.mq.aws.crossplane.io", "request": {"name":"elysium-rabbitmq-3-13-configuratation"}, "uid": "a06cbeca-6450-4582-9963-f77f9f9dd2a1", "version": "9437279", "external-name": "c-1e3427a2-5fde-4e89-8cd8-335d09f3d147", "error": "isUpToDate check failed: EOF", "errorVerbose": "EOF\nisUpToDate check failed\ngithub.com/crossplane-contrib/provider-aws/pkg/controller/mq/configuration.(*external).Observe\n\tgithub.com/crossplane-contrib/provider-aws/pkg/controller/mq/configuration/zz_controller.go:97\ngithub.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile\n\tgithub.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go:914\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1700"}`

We did a deep dive into the code, and found out that it most likely is cause by this line:
```
diffDataAtAndForProviderConfig, err := mqconfutils.DiffXMLConfigs(atProviderConfig, forProviderConfig)
```

The provider is expecting an XML configuration, which would be valid and can be seen from the examples for ActiveMQ. However for RabbitMQ we have no XML config, but essentially a multiline string like this:
```
data: |
      quorum_queue.property_equivalence.relaxed_checks_on_redeclaration = true
```

### How can we reproduce it?

```
apiVersion: mq.aws.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: rabbitmq-3-13-configuration
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    crossplane.io/external-name: rabbitmq-3-13-configuration
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: aws-provider-config
  forProvider:
    description: "Default configuration for rabbitmq 3.13"
    engineType: rabbitmq
    engineVersion: "3.13"
    name: rabbitmq-3-13-configuration
    region: eu-central-1
    data: |
      quorum_queue.property_equivalence.relaxed_checks_on_redeclaration = true

```

### What environment did it happen in?
Crossplane version: v0.51.4
