### ISSUE TITLE
Unable to access connection information from CacheCluster.

### ISSUE THREAD

**Issue by justinabrahms** [crossplane-contrib/provider-aws#2167]
### What happened?

I created a CacheCluster which worked just fine. Unfortunately, it published a 0 byte secret as mentioned in #2050. Unlike the poster of that issue... I don't have a solution, nor do the people in the comments.

### How can we reproduce it?

If you use this config (`writeConnectionSecretToRef`), you'll get the zero byte secret.

```yaml
apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheCluster
metadata:
  name: redis-cache-cluster
  namespace: productivity-team
spec:
  forProvider:
    cacheNodeType: cache.t2.micro
    engine: redis
    engineVersion: 6.2.6
    numCacheNodes: 1
    port: 6379
    region: us-east-1
    tags:
      - key: team
        value: productivity
      - key: application
        value: crossplane-test
    writeConnectionSecretToRef:
      name: connection-secret
      namespace: productivity-team
```

If you use `publishConnectionDetailsTo`, you just get... nothing.

```yaml
apiVersion: secrets.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: productivity-crossplane-store
  namespace: productivity-team
spec:
  type: Kubernetes
  defaultScope: productivity-team
---
apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheCluster
metadata:
  name: redis-cache-cluster
  namespace: productivity-team
spec:
  forProvider:
    cacheNodeType: cache.t2.micro
    engine: redis
    engineVersion: 6.2.6
    numCacheNodes: 1
    port: 6379
    region: us-east-1
    tags:
      - key: team
        value: productivity
      - key: application
        value: crossplane-test
  publishConnectionDetailsTo:
    name: conn-details-name
    configRef:
      name: productivity-crossplane-store
```

### What environment did it happen in?
Crossplane version: 1.18.2
EKS Auto on AWS.

k8s:
```
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.4-eks-2d5f260
```
