### ISSUE TITLE
`newerNoncurrentVersions` will result in XML not well-formed error

### ISSUE THREAD

**Issue by schaschko** [crossplane-contrib/provider-aws#2181]
Applying

```yaml
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketLifecycleConfiguration
metadata:
  name: my-bucket-lifecycle-conf
spec:
  forProvider:
    bucketRef:
      name: my-bucket
    region: my-region
    rule:
      - noncurrentVersionExpiration:
          - noncurrentDays: 1
            # `newerNoncurrentVersions` will result in an error
            newerNoncurrentVersions: "2"
        status: Enabled
        id: non-current-version-expiration
  providerConfigRef:
    name: my-providerconfig
```

will result in this error:

```text
    message: 'async create failed: failed to create the resource: [{0 creating S3
      Bucket (my-bucket) Lifecycle Configuration: operation error S3:
      PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID:
      ..., HostID: ...,
      api error MalformedXML: The XML you provided was not well-formed or did not
      validate against our published schema  []}]'
```

Some issues point in the direction that it would be required to manually set in the `rule` array:

```
        filter:
          - prefix: ""
```

but it's automatically set by the provider. Provider version is `xpkg.upbound.io/upbound/provider-aws-s3:v1.19.0`.

If `newerNoncurrentVersions: "2"` is removed, everything works. Can you please look into that?
