### ISSUE TITLE
S3 Bucket Policy Constantly being updated

### ISSUE THREAD

**Issue by brandocomando** [crossplane-contrib/provider-aws#2183]
### What happened?
After creating an S3 bucket it never becomes ready (synced=true, no ready state at all)
cloudtrail shows putBucketPolicy constantly being called, and object events show updatedExternalResource over and over

### How can we reproduce it?
create a bucket like:
```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    crossplane.io/external-name: my-bucket
  name: my-bucket
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: my-region
    policy:
      id: policy
      statements:
        - action:
            - s3:*
          condition:
            - conditions:
                - key: aws:SourceVpc
                  stringValue: my-vpc-id
              operatorKey: StringEquals
          effect: Allow
          principal:
            allowAnon: true
          resource:
            - arn:aws:s3:::my-bucket
            - arn:aws:s3:::my-bucket/*
      version: '2012-10-17'
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    tagging:
      tagSet:
        - key: crossplane.io/owned
          value: 'true'
    versioningConfiguration:
      status: Enabled
    websiteConfiguration:
      indexDocument:
        suffix: index.html
  managementPolicies:
    - '*'
  providerConfigRef:
    name: aws-provider-config
```
Observe that it does not become ready and is constantly updating the bucket policy

### What environment did it happen in?
Crossplane version: v1.19.0
aws provider:
package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.51.5"
EKS:
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.2-eks-bc803b4

**Comment by brandocomando** [comment]
Could be similar to: https://github.com/crossplane-contrib/provider-aws/issues/2013

**Comment by karaktaka** [comment]
We're facing the same issue. I also noticed that new Buckets now always set 
```yaml
paymentConfiguration:
  payer: BucketOwner
```
while older ones don't have this.

This is the deployed manifest by ArgoCD:

```yaml
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm,Delete=confirm
    argocd.argoproj.io/tracking-id: >-
      <app>:s3.aws.crossplane.io/Bucket:<ns>/<bucket_name>-eu-central-1
    crossplane.io/external-create-pending: '2025-07-04T08:21:01Z'
    crossplane.io/external-create-succeeded: '2025-07-04T08:21:02Z'
    crossplane.io/external-name: <bucket_name>-eu-central-1
  creationTimestamp: '2025-07-04T08:21:01Z'
  finalizers:
    - finalizer.managedresource.crossplane.io
  name: <bucket_name>-eu-central-1
spec:
  deletionPolicy: Delete
  forProvider:
    corsConfiguration:
      corsRules:
        - allowedHeaders:
            - '*'
          allowedMethods:
            - GET
          allowedOrigins:
            - '*'
          exposeHeaders:
            - x-amz-server-side-encryption
    lifecycleConfiguration:
      rules:
        - abortIncompleteMultipartUpload:
            daysAfterInitiation: 1
          filter: {}
          id: abort-incomplete-multipart-upload
          status: Enabled
        - filter: {}
          id: archive-after-90-and-deep-archive-after-180-days
          status: Enabled
          transitions:
            - days: 90
              storageClass: GLACIER
            - days: 180
              storageClass: DEEP_ARCHIVE
    locationConstraint: eu-central-1
    objectLockEnabledForBucket: false
    objectOwnership: BucketOwnerEnforced
    paymentConfiguration:
      payer: BucketOwner
    policy:
      statements:
        - action:
            - s3:*
          condition:
            - conditions:
                - booleanValue: false
                  key: aws:SecureTransport
              operatorKey: Bool
          effect: Deny
          principal:
            awsPrincipals:
              - iamRoleArn: '*'
          resource:
            - arn:aws:s3:::<bucket_name>-eu-central-1/*
            - arn:aws:s3:::<bucket_name>-eu-central-1
        - action:
            - s3:GetObject
            - s3:GetBucketAcl
            - s3:GetBucketLocation
          effect: Allow
          principal:
            awsPrincipals:
              - awsAccountId: '<id>'
          resource:
            - arn:aws:s3:::<bucket_name>-eu-central-1/*
            - arn:aws:s3:::<bucket_name>-eu-central-1
      version: '2012-10-17'
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    tagging:
      tagSet: [] # removed for privacy reasons
    versioningConfiguration:
      status: Enabled
  managementPolicies:
    - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:s3:::<bucket_name>-eu-central-1
  conditions:
    - lastTransitionTime: '2025-07-04T08:21:02Z'
      reason: Creating
      status: 'False'
      type: Ready
    - lastTransitionTime: '2025-07-04T08:21:02Z'
      reason: ReconcileSuccess
      status: 'True'
      type: Synced
```
