### ISSUE TITLE
RDSInstance - constant CloudWatch Logs Export changes

### ISSUE THREAD

**Issue by mlubanski** [crossplane-contrib/provider-aws#2186]
### What happened?
Patched `provider-aws` from `v0.49.2` to `v0.51.5`
Afterwards we noticed that crossplane constantly updates  CloudWatch Logs Export configuration

![Image](https://github.com/user-attachments/assets/1c7c2e6b-aa19-4d0a-b0b8-e87c5d44bc38)

Example MR:

```yaml
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  annotations:
    crossplane.io/composition-resource-name: rds
    crossplane.io/external-name: eu1lab-eks001-crossplane-demo-hello-crossplane
  name: hello-crossplane-97w47-x5pr8
spec:
  deletionPolicy: Delete
  forProvider:
    allocatedStorage: 20
    applyModificationsImmediately: false
    autoMinorVersionUpgrade: true
    availabilityZone: eu-west-1c
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-rsa2048-g1
    copyTagsToSnapshot: true
    dbInstanceClass: db.t4g.small
    dbParameterGroupName: eu1lab-eks001-crossplane-demo-hello-crossplane
    dbSubnetGroupName: private_net_vpc-xxxxx
    deletionProtection: false
    enableCloudwatchLogsExports:
    - audit
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    engineVersion: 8.0.40
    iops: 3000
    kmsKeyId: arn:aws:kms:eu-west-1:xxxxx:key/xxxxx
    licenseModel: general-public-license
    masterUsername: root
    maxAllocatedStorage: 1000
    multiAZ: false
    optionGroupName: custom-default-mysql-8-0
    port: 3306
    preferredBackupWindow: 14:00-16:00
    preferredMaintenanceWindow: Mon:11:00-Mon:14:00
    publiclyAccessible: false
    region: eu-west-1
    skipFinalSnapshotBeforeDeletion: true
    storageEncrypted: true
    storageThroughput: 125
    storageType: gp3
    vpcSecurityGroupIds:
    - sg-xxxxx
    - sg-yyyyy
  managementPolicies:
  - '*'
  providerConfigRef:
    name: crossplane-provider-aws
  publishConnectionDetailsTo:
    configRef:
      name: default
    metadata:
      labels:
        secret.crossplane.io/owner-uid: 57e96ad8-d6de-40ff-841e-c73118827f2a
    name: crossplane-demo-hello-crossplane-rdsinstance
```

### What environment did it happen in?

* Crossplane version: `1.19.0`
* Provider version: `xpkg.upbound.io/crossplane-contrib/provider-aws:v0.51.5`
* Cloud provider: `AWS`
* Kubernetes version (use `kubectl version`)
* Kubernetes distribution: `EKS`
