### ISSUE TITLE
AWS Secret - Ignore Secret Changes

### ISSUE THREAD

**Issue by ConnorGraham** [crossplane-contrib/provider-aws#2188]
### What problem are you facing?

When creating a AWS Secret, it would be helpful to be able to have its metadata managed by crossplane, but not the secret value itself.
https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.51.5/resources/secretsmanager.aws.crossplane.io/Secret/v1beta1

### How could Crossplane help solve your problem?

I am aware of `initProvider` which could potentially solve for this issue, but at this time does not appear to be supported by this community aws provider.

```
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: my-secret
spec:
  initProvider:
    stringSecretRef:
      name: hello-world-secret
      namespace: default
  forProvider:
    region: us-east-1
```

I know that the terraform equivilant supports a `ignore_secret_changes` variable. The same could in theory be done with crossplane
https://github.com/terraform-aws-modules/terraform-aws-secrets-manager?tab=readme-ov-file#input_ignore_secret_changes

```
apiVersion: secretsmanager.aws.crossplane.io/v1beta1
kind: Secret
metadata:
  name: my-secret
spec:
  forProvider:
    stringSecretRef:
      name: hello-world-secret
      namespace: default
    region: us-east-1
    ignore_secret_changes: true
```
