### ISSUE TITLE
AWS ECS Service never gets Ready

### ISSUE THREAD

**Issue by bmartins-unit** [crossplane-contrib/provider-aws#2197]
### What happened?

After upgrading from version 0.49.2 to 0.52.0 we've detected that the ECS Service started updating non-stop.

We've been troubleshooting and debugging and the `cmp.Diff` https://github.com/crossplane-contrib/provider-aws/blob/e02a4c2de22c21f188f5a514297b54e9bd7677cc/pkg/controller/ecs/service/setup.go#L100 returns something like that
```
   &v1alpha1.ServiceParameters{
    ... // 1 ignored field
    CapacityProviderStrategy: nil,
    DeploymentConfiguration: &v1alpha1.DeploymentConfiguration{
      Alarms:                   nil,
-     DeploymentCircuitBreaker: &v1alpha1.DeploymentCircuitBreaker{Enable: &false, Rollback: &false},
+     DeploymentCircuitBreaker: nil,
      MaximumPercent:           &200,
      MinimumHealthyPercent:    &100,
    },
    DeploymentController:          &{Type: &"ECS"},
    DesiredCount:                  &1,
    EnableECSManagedTags:          &false,
-   EnableExecuteCommand:          &false,
+   EnableExecuteCommand:          nil,
    HealthCheckGracePeriodSeconds: &0,
    LaunchType:                    &"FARGATE",
    ... // 1 ignored and 8 identical fields
    CustomServiceParameters: v1alpha1.CustomServiceParameters{
      ... // 4 ignored fields
      LoadBalancers:        {},
      NetworkConfiguration: &{AWSvpcConfiguration: &{AssignPublicIP: &"DISABLED", SecurityGroups: {&"sg-00596f794f531eba6", &"sg-019e5f90ce77627c0"}, Subnets: Inverse(cmpopts.SortSlices, []*string{&"subnet-049314e576f9fc73e", &"subnet-07b64daff65507d45"})}},
-     TaskDefinition:       &"arn:aws:ecs:us-east-1:00000000000:task-definition/task-def-service:26",
+     TaskDefinition:       &"task-def-service:26",
      ... // 2 ignored fields
    },
  }
```

The fields `DeploymentCircuitBreaker` and `EnableExecuteCommand` we can easily fix them
In the `TaskDefinition` field, only he name should be validated instead the complete ARN

### How can we reproduce it?

Create an ECS CR with `service.Spec.ForProvider.TaskDefinition = "task-def-service:26"`
We are not creating the TaskDefinition with Crossplane, so we are not using the `TaskDefinitionRef`

### What environment did it happen in?
Crossplane version: 0.52.0
Cloud provider: AWS EKS 1.30

**Comment by bmartins-unit** [comment]
@MisterMX will you take a look at this?

**Comment by anagarlau** [comment]
As specified in the issue template, providing an example to reproduce the bug would be greatly appreciated as it speeds up the process. @bmartins-unit

**Comment by bmartins-unit** [comment]
here is an example:
```
apiVersion: ecs.aws.crossplane.io/v1alpha1
kind: Service
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-01-15T10:18:03Z"
    crossplane.io/external-create-succeeded: "2025-01-15T10:18:04Z"
    crossplane.io/external-name: ecs-service-0b69fcbd-f8ad-48d7-881f-a91153049d00
    managed-operator.xpto.net/owner: 0b69fcbd-f8ad-48d7-881f-a91153049d00/0b69fcbd-f8ad-48d7-881f-a91153049d00
    managed-operator.xpto.net/owner-uuid: 97f4c0eb-ab33-451b-ab52-f28dc3b7eaab
  creationTimestamp: "2025-01-15T10:18:03Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 7
  name: ecs-service-0b69fcbd-f8ad-48d7-881f-a91153049d00
  uid: 49125964-183c-4059-82ec-6f7aeb91bffa
spec:
  deletionPolicy: Delete
  forProvider:
    cluster: ecs-cluster
    deploymentConfiguration:
      maximumPercent: 200
      minimumHealthyPercent: 100
    deploymentController:
      type_: ECS
    desiredCount: 1
    enableECSManagedTags: false
    forceDeletion: true
    healthCheckGracePeriodSeconds: 0
    launchType: FARGATE
    networkConfiguration:
      awsvpcConfiguration:
        assignPublicIP: DISABLED
        securityGroupRefs:
        - name: ec2-security-group-ecs-a-0b69fcbd-f8ad-48d7-881f-a91153049d00
        - name: ec2-security-group-ecs-b-0b69fcbd-f8ad-48d7-881f-a91153049d00
        securityGroups:
        - sg-095ca8f3841cff447
        - sg-0f44eca64bfd4cac4
        subnetRefs:
        - name: ec2-subnet-a-0b69fcbd-f8ad-48d7-881f-a91153049d00
        - name: ec2-subnet-b-0b69fcbd-f8ad-48d7-881f-a91153049d00
        subnets:
        - subnet-04174924b429cf111
        - subnet-0cbea8a9b3dd77999
    platformVersion: LATEST
    propagateTags: NONE
    region: us-east-1
    schedulingStrategy: REPLICA
    serviceRegistries:
    - registryARN: arn:aws:servicediscovery:us-east-1:00000000000:service/srv-qwopjyjuavgrtzzz
    tags:
    - key: key1
      value: "value1"
    taskDefinition: task-def-service:26
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
```
