### ISSUE TITLE
Not able to import ecs taskdefinition revision

### ISSUE THREAD

**Issue by saiharsha-plivo** [crossplane-contrib/provider-aws#2198]
I was trying to import a ecs task definition , I have mentioned the external name annotation and management policy as ['Observe'] , I am getting this error 

`spec.managementPolicies is set to a non-default value but the feature is not enabled: [Observe]`

### How can we reproduce it?
1. Create a taskdefinition manually in aws and get the resource arn
2. Apply the manifest below

```
apiVersion: ecs.aws.crossplane.io/v1alpha1
kind: TaskDefinition
metadata:
  annotations:
    crossplane.io/external-name: <ARN OF TASK DEFINITION REVISION>
  name: crossplane-test-revision-3
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-west-1
  managementPolicies:
    - Observe
  providerConfigRef:
    name: providerconfig-aws
```

Crossplane version: v1.17.0
provider version: v.0.52.0
Kind version : v0.27.0 go1.24.0 darwin/arm64
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.32.2
Kernel : 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:49 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8103 arm64

**Comment by saiharsha-plivo** [comment]
Solved this by attaching deployment runtime config 

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-aws
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            args:
            - --debug
            - --enable-management-policies
```
