### ISSUE TITLE
RDS Aurora PostgreSQL Cluster with restoreToPointInTime Fails to Create ClusterInstance Since v1.19.0

### ISSUE THREAD

**Issue by farzanSmd** [crossplane-contrib/provider-aws#2200]
### What happened?
Since provider-aws-rds version v1.19.0, creating an RDS Cluster using the restoreToPointInTime option results in only the Cluster being created, but no ClusterInstance is provisioned.

This functionality worked correctly until v1.18.5, where both the Cluster and ClusterInstance were successfully created.

### How can we reproduce it?

Create Aurora PostgreSQL DBCluster with restoreToPointInTime:

```
apiVersion: rds.aws.upbound.io/v1beta2
kind: Cluster
spec:
  forProvider:
    engine: aurora-postgresql
    engineVersion: "16.4"
    region: eu-west-1
    restoreToPointInTime:
      sourceClusterIdentifier: source-cluster-1
      restoreType: full-copy
      useLatestRestorableTime: true
    ...
```

### What environment did it happen in?
Crossplane version: 1.19.0
Provider version: xpkg.upbound.io/upbound/provider-aws-rds:v1.19.0 (also doesn't work in v1.20.0, 1.21.1)
Kubernetes version 1.32.0
