### ISSUE TITLE
Support structured fields for IAM policies

### ISSUE THREAD

**Issue by mcavoyk** [crossplane-contrib/provider-aws#315]
### What problem are you facing?

Today the `IAMPolicy` type supports a `Document` string field for the IAM policy. This expects a [json document](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#access_policies-json) for the policy definition. My use case is I would like to create IAM policy within a composition and have fields within the document patched based on other resources within the composition.

### How could Crossplane help solve your problem?

https://github.com/crossplane/provider-aws/pull/289 for s3 bucket policy offers well defined policy fields which are serialized into the json document. `IAMPolicy` should offer something similiar. The json string field `Document`  would still be preferred if non-empty, but otherwise a structured `PolicyStatement` field could be used.

Example with document:
```yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: somepolicy  
spec:
  forProvider:
    name: external-name
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
  providerRef:
    name: example
  reclaimPolicy: Delete
```

Example with statement:

```yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: somepolicy  
spec:
  forProvider:
    name: external-name
    statement:
    - effect: "Allow"
      action: elastic-inference:Connect
      resource: "*"
  providerRef:
    name: example
  reclaimPolicy: Delete
```
