### ISSUE TITLE
Enable DynamoDB TTL

### ISSUE THREAD

**Issue by JasP19** [crossplane-contrib/provider-aws#481]
### What problem are you facing?

I have defined a DynamoDB Table using the [Crossplane documentation](https://doc.crds.dev/github.com/crossplane/provider-aws/dynamodb.aws.crossplane.io/Table/v1alpha1). I would like to enable TTL based on a certain attribute as per the [AWS documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-how-to.html). I have provided my YAML below, for reference.

```yaml
apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: testTable
spec:
  deletionPolicy: Orphan
  forProvider:
    attributeDefinitions:
      - attributeName: testCol
        attributeType: S
    keySchema:
      - attributeName: testCol
        keyType: HASH
    provisionedThroughput: 
      readCapacityUnits: 1
      writeCapacityUnits: 1
    region: eu-west-1
    tags:
      - key: environment
        value: dev
      - key: provisionedBy
        value: Crossplane
```

### How could Crossplane help solve your problem?

Please could you add an attribute to the Table custom resource which allows TTL to be enabled and allows the user to specify which column the TTL should be measured against. I believe this may be achieved using this [API call](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTimeToLive.html).
