### ISSUE TITLE
Force Delete Flag for some resources 

### ISSUE THREAD

**Issue by enderv** [crossplane-contrib/provider-aws#495]
### What problem are you facing?
Some resources do not allow deletion if they have dependent resources (s3 bucket with items, vpc with resources, etc). This can cause the provider reconciler to fail to delete resources. Our use case revolves around s3 and vpc's. We want users to be able to create and cleanup buckets and vpcs even if they have items created in them from outside crossplane. 

### How could Crossplane help solve your problem?
Was thinking for these resources add a force delete flag in the spec and logic to controller to do the cleanup. Similar to [force_destroy option for s3 buckets in terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#force_destroy).

**Comment by negz** [comment]
Thanks for this feature request @enderv! I agree this would be good functionality to have, but we need to think about how it should work.

Architecturally we try to ensure that our managed resources map cleanly to a cloud provider API object or at least concept to keep our implementation granular and predictable. Terraform et al achieve this "force delete" functionality by listing and deleting all objects in the bucket being deleted, which blends concepts a little more than I'd like - i.e. ideally when you operate on a Crossplane "bucket" you could could be confident that you're only ever exercising code that operates on AWS buckets, and not objects.

**Comment by muvaf** [comment]
I think I'm in the same boat with @negz . It's a very useful feature for sure, but with the high fidelity goal, I'm not sure if it fits in the bucket controller. Maybe a small webhook or controller could do what you want; `if <bucket cr>.deletion { list and delete every object }` or maybe you could incorporate this functionality into your uninstall/removal process of the application if possible.

**Comment by enderv** [comment]
Agree not really a fan of flag but wanted to throw it out there. Something we are thinking about doing is using a helm release that just uses pre-delete hook to run a job that does the cleanup and just include that in the composition.

Which makes me think a handy pre-delete job hook somewhere would be nice.

**Comment by chlunde** [comment]
@ulucinar / @muvaf asked me on slack to list some examples of stuck-on-deletion issues I had seen. As there already is an issue I'll write them here:

# Patched invalid external-name
```yaml
apiVersion: ecr.aws.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: delete-demo1
spec:
  forProvider:
    imageScanningConfiguration:
      scanOnPush: true
    imageTagMutability: MUTABLE
    region: eu-north-1

```

```
Status:
  At Provider:
    Created At:       2021-06-17T16:20:31Z
    Registry Id:      123
    Repository Arn:   arn:aws:ecr:eu-north-1:123:repository/delete-demo1
    Repository Name:  delete-demo1
    Repository Uri:   123.dkr.ecr.eu-north-1.amazonaws.com/delete-demo1
  Conditions:
    Last Transition Time:  2021-06-17T16:20:31Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2021-06-17T16:20:31Z
    Reason:                ReconcileSuccess
    Status:                True
    Type:                  Synced
```


```
k annotate -f repo1.yaml --overwrite 'crossplane.io/external-name=foo/$USER/bar'
k delete -f repo1.yaml  
repository.ecr.aws.crossplane.io "delete-demo1" deleted
# hangs
k get -f repo1.yaml -o yaml
```
```yaml
...
status:
  atProvider:
    createdAt: "2021-06-17T16:20:31Z"
    registryId: "123"
    repositoryArn: arn:aws:ecr:eu-north-1:123:repository/delete-demo1
    repositoryName: delete-demo1
    repositoryUri: 123.dkr.ecr.eu-north-1.amazonaws.com/delete-demo1
  conditions:
  - lastTransitionTime: "2021-06-17T16:20:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-06-17T16:23:03Z"
    message: 'observe failed: failed to describe repository with id: InvalidParameterException:
      Invalid parameter at ''repositoryName'' failed to satisfy constraint: ''must
      satisfy regular expression ''(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*'''''
    reason: ReconcileError
    status: "False"
    type: Synced
```

This is a special corner case - I believe. If a webhook refused the invalid external name patch (there are two issues here - 1) what is a valid name for this specific resource 2) What should we do when someone patches the external name of a provisioned resource) I believe this would never happen. So it might be better to prevent the possibility of this issue happening, instead of handling this specific issue.
