### ISSUE TITLE
Implement User Creation for ElasticCache

### ISSUE THREAD

**Issue by linuxbsdfreak** [crossplane-contrib/provider-aws#548]
### What problem are you facing?
We would like to create an initial user for an ElasticCache Instance, similar to the steps given below via CrossPlane 

https://docs.aws.amazon.com/cli/latest/reference/elasticache/create-user.html

### How could Crossplane help solve your problem?
Implementing within the provider-aws  could help us providing a user per customer when an elasticcache  instance is provisioned under AWS with CrossPlane

**Comment by muvaf** [comment]
Hi @linuxbsdfreak ! I have just tested whether our code generation pipeline is able to work with this resource and it seems it does. If you're open to contributing, [here is the guide](https://github.com/crossplane/provider-aws/blob/master/CODE_GENERATION.md) you can follow and implement this pretty quickly. As `apis/elasticache/v1alpha1/generator-config.yaml`, you can use the following to get only the `User` resource generated:
```yaml
ignore:
  resource_names:
    - CacheCluster
    - CacheParameterGroup
    - CacheSecurityGroup
    - CacheSubnetGroup
    - GlobalReplicationGroup
    - ReplicationGroup
    - Snapshot
    - UserGroup
```
