### ISSUE TITLE
CacheCluster does not create a k8s secret 

### ISSUE THREAD

**Issue by Dkaykay** [crossplane-contrib/provider-aws#551]
### What happened?
When creating a CacheCluster CRD for redis, no kubernetes secret is created containing the details required for establishing a connection to redis, e.g.
- endpoint url
- port
- authtoken or username+password

This issue also correlates to https://github.com/crossplane/provider-aws/issues/548

### How can we reproduce it?

```yml
apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheCluster
metadata:
  name: redis
spec:
  forProvider:
    region: eu-central-1
    engine: Redis 
    engineVersion: 5.0.6
    port: 6379
    cacheNodeType: cache.t2.micro
    numCacheNodes: 1
    authToken: initial1234567890 # this does not seem to have any effect, because transit encryption cannot be enabled
   providerRef:
    name: aws-provider
```
### What environment did it happen in?

crossplane/provider-aws:v0.16.0
