### ISSUE TITLE
S3 replication configuration shouldn't require optional fields such as priority, prefix or deleteMarkerReplication

### ISSUE THREAD

**Issue by yshu2017** [crossplane-contrib/provider-aws#554]
### What happened?

When we create a S3 bucket with replication configuration, if without the block of non-required fields such as
priority, deleteMarker, filter, the replication rules are not applied with following error:

```
update failed: cannot create or update: cannot put Bucket replication: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
status code: 400, request id: 64CFFAC56D920C2E, host id: Q1BvF6RSIkH7bBPe/HCw4tYRXlw3UMrCUPnrh34wz4wKaHLH1tjSoIWr8lvDSgFUTnm/WwZpQ/g=
```

### How can we reproduce it?

Apply the following yaml to apply the replication rules. However, if you remove the "priority", "filter" and "deleteMarkerReplication" section from the yaml, the replication rules will not be applied.

```
replicationConfiguration:
      role: "arn:aws:iam::00000000:role/crossplane-s3-test-warrior"
      rules:
        - destination:
            bucket: arn:aws:s3:::test-bucket-warrior-crossplane-yl
            storageClass: "STANDARD_IA"
          status: Enabled
          id: "test"
          priority: 10
          deleteMarkerReplication:
            Status: Disabled
          filter:
            prefix: ""
```

### What environment did it happen in?
Crossplane version: 
crossplane/provider-aws-controller:v0.16.0
