### ISSUE TITLE
Composite VPC resource gets updated many times in kube even when no changes. 

### ISSUE THREAD

**Issue by enderv** [crossplane-contrib/provider-aws#566]
### What happened?
Was digging into an issue on VPC and saw the generation was an outrageously high number

```
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/external-name: vpc-id
  creationTimestamp: "2021-02-19T15:49:02Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: c-dev-knfjr-
  generation: 35067
```

### How can we reproduce it?
Create a simple composite with vpc resource and patch a tag in the composition. Go and check the yaml after a few minutes and view the generation.

Need the xrd still but sample composition I was using to debug
```
apiVersion: apiextensions.crossplane.io/v1beta1
kind: Composition
metadata:
  name: vpc-aws-v1
  labels:
    provider: aws
    platformVersion: v1
spec:
  compositeTypeRef:
    apiVersion: network.example.com/v1alpha1
    kind: CompositeVPC
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            tags:
              - key: Name
            cidrBlock: 172.16.0.0/16
            enableDnsSupport: true
            enableDnsHostNames: true
            deletionPolicy: Delete
            region: us-east-2
      patches:
        - fromFieldPath: "spec.providerRef.name"
          toFieldPath: "spec.providerConfigRef.name"
        - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
          toFieldPath: "spec.forProvider.tags[0].value"
  ```

### What environment did it happen in?
Crossplane version: 
provider-aws: v0.17.0-rc.0.71.gc8b95eb1

**Comment by enderv** [comment]
Pretty sure this is due to `tagger.Initialize` function which I'm guessing is just supposed to make sure the tags are in a set order. Was going to add a check before doing kube update and see a few other resources with the same function

- replicationgroup
- rdsinstance
- dynamodbtable
- elasticip
- repository
- eks
- fargateprofile
- nodegroup
- secretsmanager

**Comment by hasheddan** [comment]
@enderv this seems like it could be causing the frequent updates. The purpose of the `tagger.Initialize` method is to add common Crossplane tags to all resources in addition to any defined by the user. I would expect this operation to be a no-op after they have been added the first time, but it is worth investigating if that is actually true. I'm not sure we even need to ensure that they are in a certain order as long as the `ExternalTags` are present.

/cc @muvaf

**Comment by enderv** [comment]
@hasheddan thanks for the info! Will see what I can do to make it a no-op if all the `ExternalTags` are present.

**Comment by enderv** [comment]
Oops did some more looking this seems to be with composition based resources only. I was looking at the wrong VPC :( 

If standalone VPC seems to be fine but composition based one I think is fighting with the crossplane controller, need to do some more digging though.

**Comment by enderv** [comment]
Alright this was fun. Did some more digging and its because in our composition we patch a tag to get the vpc name to show up correctly in the console. Looks like the main crossplane controller is changing it to what it thinks the patch should be and then aws controller is adding back in external tags...repeat forever. Updated the title and description to match better.

Grabbed snippets of the yaml output just keeps rotating

```
 spec:
   forProvider:
     cidrBlock: 172.16.0.0/16
     enableDnsHostNames: true
     enableDnsSupport: true
     instanceTenancy: default
     region: us-east-2
     tags:
     - key: Name
       value: test-composite-vpc



spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: us-east-2
    tags:
    - key: Name
      value: test-composite-vpc
    - key: crossplane-kind
      value: vpc.ec2.aws.crossplane.io
    - key: crossplane-name
      value: test-composite-vpc-9r496-sglfx
    - key: crossplane-providerconfig
      value: aws-cloud-dev
```

**Comment by muvaf** [comment]
Hmm I believe this is because we reconstruct, sort and compare in each reconcile so the list of tags has to be sorted, otherwise it will change. In this specific instance, I believe you can work around this by patching the `spec.forProvider.tags[4].value` instead of `spec.forProvider.tags[0].value`. I think `tagger.Initialize` should return early with no-op after scanning the array and seeing the tags it wants to add already exist. Would you be interested in implementing this?

**Comment by enderv** [comment]
sorry forgot to circle back on this. Was able to work around this but looks like `tagger.Initialize` is fine its just that the composition controller is constantly stripping the tags added by `tagger.Initialize` when its doing the patching of the name tag. So next time `tagger.Initialize` is called it has to re-add them.

I used bidirectional patching to get some of the info and just added the tags by default in the composition

```
resources:
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            tags:
              - key: Name
              - key: crossplane-kind
                value: vpc.ec2.aws.crossplane.io
              - key: crossplane-name
                value: temp
              - key: crossplane-providerconfig
                value: temp
            cidrBlock: 172.16.0.0/16
            enableDnsSupport: true
            enableDnsHostNames: true
            deletionPolicy: Delete
      patches:
        - type: PatchSet
          patchSetName: providerRef
        - type: PatchSet
          patchSetName: region
        - fromFieldPath: metadata.name
          toFieldPath: status.vpc.name
          type: ToCompositeFieldPath
        - fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.vpc.id
          type: ToCompositeFieldPath
        - fromFieldPath: "spec.providerRef.name"
          toFieldPath: "spec.providerConfigRef.name"
        - fromFieldPath: "metadata.labels[crossplane.io/claim-name]"
          toFieldPath: "spec.forProvider.tags[0].value"
        - fromFieldPath: "status.vpc.name"
          toFieldPath: "spec.forProvider.tags[2].value"
        - fromFieldPath: "spec.providerRef.name"
          toFieldPath: "spec.forProvider.tags[3].value"
```

With all that not sure if there is an easy fix in `tagger.Initialize` seems like we would need to track the crossplane tags elsewhere so its not constantly fighting with the composition.
