### ISSUE TITLE
Look into tightening the schemas based on the AWS schema (string patterns etc.)

### ISSUE THREAD

**Issue by chlunde** [crossplane-contrib/provider-aws#572]
### What problem are you facing?
The AWS SDK contains a more fine grained schema than what is currently implemented in the CRDs.

For example, a path in IAM must end with a slash:

https://github.com/aws/aws-sdk-go/blob/v1.34.32/models/apis/iam/2010-05-08/api-2.json#L5534-L5539

This information is not known by the k8s control plane, so a user is allowed to create an object which AWS considers malformed.

The user has to run `kubectl describe` to discover such issues, and crossplane will uselessly send the object to AWS in a loop.

### How could Crossplane help solve your problem?
Consider if more of the schema could be implemented.

OpenAPI/CRDs supports patterns: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting
example:
```yaml
              properties:
                cronSpec:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                  default: "5 0 * * *"
```
