### ISSUE TITLE
Propagate SecurityGroupIDs from SecurityGroup to AWS CNI SecurityGroupPolicy object

### ISSUE THREAD

**Issue by larhauga** [crossplane-contrib/provider-aws#593]
### What problem are you facing?
To use a `SecurityGroups` created by Crossplane we need to create an AWS CNI `SecurityGroupPolicy` object.

[Security Groups for Pods](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)

This object contains generated SG IDs generated by AWS on provider object creation.

```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: appname-sg-policy
spec:
  podSelector: {}
  securityGroups:
    groupIds:
    - sg-0xxxxxxxxxxxxxxxx # app specific policy
    - sg-0xxxxxxxxxxxxxxxx # generic eks pod2pod communication 
```

### How could Crossplane help solve your problem?
We would like to be able to automatically ensure that the `SecurityGroupPolicy` is updated with the `SecurityGrouIDs` that are returned when creating a `SecurityGroup`.

For us an optimal workflow would be a new  `provider.aws.crossplane.io` object that we can use to reference the `SecurityGroup` objects with a selector similar to https://github.com/crossplane/provider-aws/issues/592. 

Or there another way of doing this?

A gotcha here is that ordering of the creation of `SecurityGroupPolicy` and `Deployment` has an effect. The pods selected needs to be restarted for SGPs to be attached. We do not want to create Deployments before the SecurityGroup and SecurityGroupPolicy is ready. (However this is a issue with AWS CNI, fyi).
