### ISSUE TITLE
Route53 HostedZone delegationSet not in use-full format for ResourceRecordSet

### ISSUE THREAD

**Issue by martin-ducar-gd** [crossplane-contrib/provider-aws#628]
### What problem are you facing?
Consider 2 nested domains `example.com` and `test.example.com`
Now either both or at least `test.example.com` is created via Crossplane.
The `HostedZone` domain record has in `status.atProvider.delegationSet.nameServers` a array of strings:

```yaml
          status:
            description: HostedZoneStatus represents the observed state of a HostedZone.
            properties:
              atProvider:
                description: HostedZoneObservation keeps the state for the external
                  resource.
                properties:
                  delegationSet:
                    description: DelegationSet describes the name servers for this
                      hosted zone.
                    properties:
                      callerReference:
                        description: The value that you specified for CallerReference
                          when you created the reusable delegation set.
                        type: string
                      id:
                        description: The ID that Amazon Route 53 assigns to a reusable
                          delegation set.
                        type: string
                      nameServers:
                        description: NameServers contains a list of the authoritative
                          name servers for a hosted Hostedzone.
                        items:
                          type: string
```

Now you want to delegate that `test.example.com` from `example.com` via `ResourceRecordSet`
which input for `NS` type of records has this specification:
```
                  resourceRecords:
                    description: "Information about the resource records to act upon.
                      \n If you're creating an alias resource record set, omit ResourceRecords."
                    items:
                      description: ResourceRecord holds the DNS value to be used for
                        the record.
                      properties:
                        value:
                          description: "The current or new DNS record value, not to
                            exceed 4,000 characters. In the case of a DELETE action,
                            if the current value does not match the actual value,
                            an error is returned. For descriptions about how to format
                            Value for different record types, see Supported DNS Resource
                            Record Types (https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html)
                            in the Amazon Route 53 Developer Guide. \n You can specify
                            more than one value for all record types except CNAME
                            and SOA. \n If you're creating an alias resource record
                            set, omit Value."
                          type: string
                      required:
                      - value
                      type: object
```
As you can see in example they are not the same:
```
status:
  atProvider:
    delegationSet:
      nameServers:
      - ns-example1.awsdns-1.net
      - ns-example2.awsdns-2.com
      - ns-example3.awsdns-3.co.uk
      - ns-example4.awsdns-4.org
```
vs
```
  spec:
    forProvider:
      resourceRecords:
      - value: ns-example1.awsdns-1.net
      - value: ns-example2.awsdns-2.com
      - value: ns-example3.awsdns-3.co.uk
      - value: ns-example4.awsdns-4.org
      ttl: 300
      type: NS
      zoneId: ZexampleZ
```

Now when I look at `CompositeResourceDefinition` and `Composition` and its transform capabilities: https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.1.0 I can't seam to find any which would be able to transform the values.

### How could Crossplane help solve your problem?

3 options:
1. Add nested transform function to apply on each array entry another transform
2. Change `HostedZone` `status.atProvider.delegationSet.nameServers` to be an output in same format as `ResourceRecordSet` `spec.forProvider.resourceRecords`
3. Change `ResourceRecordSet` definition `spec.forProvider.resourceRecords` to be same format as `HostedZone` `status.atProvider.delegationSet.nameServers`
options 2,3 are backwards incompatible, but would make to me most sense as simplest approach

**Comment by martin-ducar-gd** [comment]
Thinking of option 2. It might be possible to introduce compatibility status field which would just reformat output, example crds field:
```
              atProvider:
                description: HostedZoneObservation keeps the state for the external resource.
                properties:
                  delegationSet:
                    description: DelegationSet describes the name servers for this hosted zone.
                    properties:
                      callerReference:
                        description: The value that you specified for CallerReference when you created the reusable delegation set.
                        type: string
                      id:
                        description: The ID that Amazon Route 53 assigns to a reusable delegation set.
                        type: string
                      nameServers:
                        description: NameServers contains a list of the authoritative name servers for a hosted Hostedzone.
                        items:
                          type: string
                        type: array
                      compatibility: # Compatibility layer fields with other crossplane resources
                        properties:
                          resourceRecordSet:
                            properties:
                              nameservers:
                                items:
                                  properties:
                                    value:
                                      type: string
                                  type: object
                                type: array
                            type: object
                        type: object  
                    type: object
```

**Comment by muvaf** [comment]
Please let me know if my understanding is correct. You have an array like the following:
```yaml
status:
  atProvider:
    delegationSet:
      nameServers:
      - ns-example1.awsdns-1.net
      - ns-example2.awsdns-2.com
      - ns-example3.awsdns-3.co.uk
      - ns-example4.awsdns-4.org
```

And you'd like to use this `status.atProvider.delegationSet.nameServers` entries as input to another `ResourceRecordSet` by patching in `Composition`. So, in the end it'd look like the following:
```yaml
spec:
    forProvider:
      resourceRecords:
      - value: ns-example1.awsdns-1.net
      - value: ns-example2.awsdns-2.com
      - value: ns-example3.awsdns-3.co.uk
      - value: ns-example4.awsdns-4.org
```

You're not able to do this because input is a string array while the target field is `object` array.
