### ISSUE TITLE
Extremely slow reconcilliation of Managed Resource

### ISSUE THREAD

**Issue by mf-lit** [crossplane-contrib/provider-aws#706]
### What happened?

We're seeing very long reconcilliation times with an MR that depends on other MRs in the same composition.

In this case the composition is built from an IAMRole, IAMPolicy and IAMRolePolicyAttachment. The IAMRole and Policy MRs reconcile in a matter of seconds as expected, but the IAMRolePolicyAttachment can take 45 minutes to reconcile.

The IAMRolePolicyAttachment uses the attributes of the IAMRole and IAMPolicy for it's configuration:
```
        forProvider:
          policyArnSelector:
            matchControllerRef: true
          roleNameSelector:
            matchControllerRef: true
```

After making a claim, we notice that it doesn't reach a Ready state after several minutes and so we check the events on the IAMRolePolicyAttachment and we see this:
```
Warning  CannotResolveResourceReferences  6m2s (x2 over 6m2s)  managed/iamrolepolicyattachment.identity.aws.crossplane.io  cannot resolve references: spec.forProvider.policyArn: referenced field was empty (referenced resource may not yet be ready)
```
That seems to imply that no further attempts to reconcille have taken place for over six minutes!

We then wait, and wait, and eventually it reconciles and we see the following events:
```
  Warning  CannotResolveResourceReferences  38m (x2 over 38m)  managed/iamrolepolicyattachment.identity.aws.crossplane.io  cannot resolve references: spec.forProvider.policyArn: referenced field was empty (referenced resource may not yet be ready)
  Normal   CreatedExternalResource          1m36s              managed/iamrolepolicyattachment.identity.aws.crossplane.io  Successfully requested creation of external resource
```

These event messages imply that Crossplane wasn't even attempting to reconcille for some 38 minutes!? Not good.

I enabled debug mode via the ControllerConfig, but this just corroborates the events above. I see a log message starting:
`Cannot resolve managed resource references`
Then there is nothing for several minutes regarding that iamrolepolicyattachment until eventually this:
`Reconciling {"controller": "managed/iamrolepolicyattachment.identity.aws.crossplane.io"`
immediately followed by
`Successfully requested creation of external resource {"controller": managed/iamrolepolicyattachment.identity.aws.crossplane.io"`

Further, the issue seems to go away when we don't set the `crossplane.io/external-name` annotation on the XRC. Then the XRC and all the MRs are reconcilled successfully in a matter of seconds.

Here's the config we're using:

<details>
<summary><code>xrc</code></summary>

```yaml
apiVersion: crossplane.example/v1alpha1
kind: IRSA
metadata:
  name: datasync
  labels:
    foo: bar
  annotations:
    crossplane.io/external-name: datasync
spec:
  parameters:
    description: "Data Sandbox S3 Sync"
    policyname: datasync
    policydoc: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetBucket"
            ],
            "Resource": "*"
          }
        ]
      }
  writeConnectionSecretToRef:
    name: datasync-irsa
```
</details>

<details>
<summary><code>xrd</code></summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: irsacomposites.crossplane.example
spec:
  claimNames:
    kind: IRSA
    plural: irsas
  connectionSecretKeys:
  - roleArn
  defaultCompositionRef:
    name: irsacomposite
  group: crossplane.example
  names:
    kind: IRSAComposite
    plural: irsacomposites
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              parameters:
                properties:
                  description:
                    description: Description to attach to IAM Resources
                    type: string
                  policydoc:
                    description: Policy Document
                    type: string
                  policyname:
                    description: IAM Policy Name
                    type: string
                  tags:
                    description: AWS resource tags
                    items:
                      properties:
                        key:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                required:
                - policydoc
                - policyname
                - description
                type: object
            required:
            - parameters
            type: object
        type: object
    served: true
```
</details>

<details>
<summary><code>composition</code></summary>

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: irsacomposite
spec:
  compositeTypeRef:
    apiVersion: crossplane.example/v1alpha1
    kind: IRSAComposite
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.annotations
      type: FromCompositeFieldPath
  resources:
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRole
      spec:
        deletionPolicy: Delete
        forProvider:
          tags:
          - key: managed_by
            value: crossplane
        providerConfigRef:
          name: crossplane-provider-aws
        writeConnectionSecretToRef:
          namespace: crossplane
    connectionDetails:
    - fromFieldPath: status.atProvider.arn
      name: roleArn
      type: FromFieldPath
    patches:
    - patchSetName: Metadata
      type: PatchSet
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.description
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      type: FromCompositeFieldPath
    - fromFieldPath: spec.claimRef.namespace
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.assumeRolePolicyDocument
      transforms:
      - string:
          fmt: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "",
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::123456789:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/XXX"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                  "StringLike": {
                    "oidc.eks.eu-west-1.amazonaws.com/id/XXX:sub": "system:serviceaccount:%s:*"
                  }
                  }
                }
              ]
            }
        type: string
      type: FromCompositeFieldPath
  - base:
      apiVersion: identity.aws.crossplane.io/v1alpha1
      kind: IAMPolicy
      spec:
        deletionPolicy: Delete
        forProvider: {}
        providerConfigRef:
          name: crossplane-provider-aws
        writeConnectionSecretToRef:
          namespace: crossplane
    patches:
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.description
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.policydoc
      toFieldPath: spec.forProvider.document
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.policyname
      toFieldPath: spec.forProvider.name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-iampolicy'
        type: string
      type: FromCompositeFieldPath
  - base:
      apiVersion: identity.aws.crossplane.io/v1beta1
      kind: IAMRolePolicyAttachment
      spec:
        deletionPolicy: Delete
        forProvider:
          policyArnSelector:
            matchControllerRef: true
          roleNameSelector:
            matchControllerRef: true
        providerConfigRef:
          name: crossplane-provider-aws
        writeConnectionSecretToRef:
          namespace: crossplane
    patches:
    - patchSetName: Metadata
      type: PatchSet
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-iamattach'
        type: string
      type: FromCompositeFieldPath
  writeConnectionSecretsToNamespace: crossplane
```
</details>

Crossplane: 1.1.0

AWS Provider: 0.18

Kubernetes: 1.19 (EKS)

**Comment by mf-lit** [comment]
Related, I already opened this issue against crossplane core, but it does appear to be a provider issue so have raised here instead.
https://github.com/crossplane/crossplane/issues/2303

**Comment by janwillies** [comment]
we hit the same issue (and I believe @benagricola as well)

**Comment by chlunde** [comment]
I'm looking into this - it might be the assume role policy comparison going wrong, I have a local fix for this and with crossplane 1.3 rc  + provider-aws 0.18 w/ this patch I don't have any issue. Related to #704 - if you have comments on package structure there it would be awesome :)

**Comment by Monska85** [comment]
We had a very similar issue. We use the simple resources without the `Compositing` mediation.

We have a IAM user, a IAM policy and a IAM policy attachment: IAM user and IAM policy take about 4 seconds to be ready and synced, the IAM policy attachment resource tries 2/3 times to create itself on AWS in the first second and after this the process hangs for about 20 minutes. Of course this amount of time is too much and using helm release standard wait time causes a failed deployment.

This behaviour is not always reproducible, and sometimes it happens for one release and not for the immediately subsequent one.

**Comment by RafalMaleska** [comment]
that's blocking me as well. one can test with: 

```
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: cnp-example-4746m
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::1234567890:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/F62ABAD7D90D310485955C799BD64CE4"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEqualsIfExists": {
                "oidc.eks.eu-central-1.amazonaws.com/id/F62ABAD7D90D310485955C799BD64CE4:sub": "system:serviceaccount:cnp-example:cnp-example"
              }
            }
          }
        ]
      }
    description: '[CROSSPLANE] [DYNAMODB] cnp-example-4746m'
    maxSessionDuration: 3600
    path: /cnp/cnp-example/
    tags:
    - key: CostReference
      value: F-330951-51-05
  providerConfigRef:
    name: iat-1234567890
---
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: cnp-example-4746m
spec:
  deletionPolicy: Delete
  forProvider:
    description: '[CROSSPLANE] [DYNAMODB] cnp-example-4746m'
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Sid": "ListAndDescribe",
                  "Effect": "Allow",
                  "Action": [
                      "dynamodb:List*",
                      "dynamodb:DescribeReservedCapacity*",
                      "dynamodb:DescribeLimits",
                      "dynamodb:DescribeTimeToLive"
                  ],
                  "Resource": "*"
              },
              {
                  "Sid": "SpecificTable",
                  "Effect": "Allow",
                  "Action": [
                      "dynamodb:BatchGet*",
                      "dynamodb:DescribeStream",
                      "dynamodb:DescribeTable",
                      "dynamodb:Get*",
                      "dynamodb:Query",
                      "dynamodb:Scan",
                      "dynamodb:BatchWrite*",
                      "dynamodb:CreateTable",
                      "dynamodb:Delete*",
                      "dynamodb:Update*",
                      "dynamodb:PutItem"
                  ],
                  "Resource": "arn:aws:dynamodb:eu-central-1:1234567890:table/cnp-example-4746m"
              }
          ]
      }
    name: cnp-example-4746m
  providerConfigRef:
    name: iat-1234567890
---
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRolePolicyAttachment
metadata:
  name: cnp-example-4746m
spec:
  deletionPolicy: Delete
  forProvider:
    policyArnRef:
      name: cnp-example-4746m
    roleNameRef:
      name: cnp-example-4746m
  providerConfigRef:
    name: iat-1234567890
```

last 3 tests took in my case: 46min, 30min, 41min

workaround: combining the policyARN from other strings

**Comment by mithie** [comment]
we are facing the same issue when we try to create mounttargets for a filesystem. had to wait almost 50 mins before the mounttargets were provisioned. is there a chance that this issue will be fixed soon?

**Comment by ezgidemirel** [comment]
Hey @mf-lit, I tried to reproduce the issue with a slightly modified version of your files. But all three resources became ready in less than a minute. 
```
NAME                                              READY   SYNCED   AGE
role.iam.aws.crossplane.io/datasync-tg8zp-tv8hb   True    True     34s

NAME                                                              READY   SYNCED   ROLENAME   POLICYARN                                   AGE
rolepolicyattachment.iam.aws.crossplane.io/datasync-tg8zp-k7f7g   True    True     datasync   arn:aws:iam::609897127049:policy/datasync   34s

NAME                                                ARN                                         READY   SYNCED   AGE
policy.iam.aws.crossplane.io/datasync-tg8zp-m8jnx   arn:aws:iam::609897127049:policy/datasync   True    True     34s
```

I needed to update `apiVersion` and `kind` fields to match the latest CRDs. Here is the `composition.yaml` file I used: 
```
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: irsacomposite
spec:
  compositeTypeRef:
    apiVersion: crossplane.example/v1alpha1
    kind: IRSAComposite
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.annotations
      type: FromCompositeFieldPath
  resources:
  - base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Role
      spec:
        deletionPolicy: Delete
        forProvider:
          tags:
          - key: managed_by
            value: crossplane
        writeConnectionSecretToRef:
          namespace: crossplane
    connectionDetails:
    - fromFieldPath: status.atProvider.arn
      name: roleArn
      type: FromFieldPath
    patches:
    - patchSetName: Metadata
      type: PatchSet
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.description
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.tags
      toFieldPath: spec.forProvider.tags
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-iamrole'
        type: string
      type: FromCompositeFieldPath
    - fromFieldPath: spec.claimRef.namespace
      policy:
        fromFieldPath: Required
      toFieldPath: spec.forProvider.assumeRolePolicyDocument
      transforms:
      - string:
          fmt: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "",
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "arn:aws:iam::123456789:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/XXX"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                  "StringLike": {
                    "oidc.eks.eu-west-1.amazonaws.com/id/XXX:sub": "system:serviceaccount:%s:*"
                  }
                  }
                }
              ]
            }
        type: string
      type: FromCompositeFieldPath
  - base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: Policy
      spec:
        deletionPolicy: Delete
        forProvider: {}
        writeConnectionSecretToRef:
          namespace: crossplane
    patches:
    - fromFieldPath: spec.parameters.description
      toFieldPath: spec.forProvider.description
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.policydoc
      toFieldPath: spec.forProvider.document
      type: FromCompositeFieldPath
    - fromFieldPath: spec.parameters.policyname
      toFieldPath: spec.forProvider.name
      type: FromCompositeFieldPath
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-iampolicy'
        type: string
      type: FromCompositeFieldPath
  - base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: RolePolicyAttachment
      spec:
        deletionPolicy: Delete
        forProvider:
          policyArnSelector:
            matchControllerRef: true
          roleNameSelector:
            matchControllerRef: true
        writeConnectionSecretToRef:
          namespace: crossplane
    patches:
    - patchSetName: Metadata
      type: PatchSet
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-iamattach'
        type: string
      type: FromCompositeFieldPath
  writeConnectionSecretsToNamespace: crossplane

```

If anyone else has a recent example, I'm more than happy to try :)
