### ISSUE TITLE
Ability to create IAM OIDC provider for an EKS cluster automatically

### ISSUE THREAD

**Issue by doubliez** [crossplane-contrib/provider-aws#796]
### What problem are you facing?
When creating an EKS cluster with Crossplane, I need to create the corresponding OpenIDConnectProvider as documented here: https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

`eksctl` does this automatically when provisioning a cluster with the `withOIDC` option.

However the current [OpenIDConnectProvider](https://doc.crds.dev/github.com/crossplane/provider-aws/identity.aws.crossplane.io/OpenIDConnectProvider/v1alpha1@v0.19.0) resource in Crossplane doesn't allow to reference the OIDC URL and thumbprint of the EKS cluster. It looks like I need to supply it manually which is a problem since the URL and thumbprint aren't known in advance.

### How could Crossplane help solve your problem?
I'm still getting started with Crossplane so I'm not sure what the best solution is, but I would imagine something like that:
```yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: OpenIDConnectProvider
metadata:
  name: eks-provider
spec:
  forProvider:
    clientIDList:
      - sts.amazonaws.com
    thumbprintList:
      - eksClusterOIDCThumbprintRef:
          name: my-eks-cluster
    url:
      eksClusterOIDCIssuerRef:
        name: my-eks-cluster
  providerConfigRef:
    name: example
```

Although the thumbprint is not directly exposed by EKS, I think Crossplane would need to do extra work to get it.
