### ISSUE TITLE
SNSTopic Naming Conflict

### ISSUE THREAD

**Issue by mf-lit** [crossplane-contrib/provider-aws#798]
### What happened?

I've noticed that the SNSTopic MR names the target resource based on the (required) value of `forProvider.name`. This is a break from convention isn't it? Normally the target resource is named according to `metadata.name` or the `crossplane.io/external-name` annotation if provided.

This has a couple of nasty side effects:

1. Multiple SNSTopic MRs with different names but the same value for `forProvider.name` can be created. These will all sync successfully but will endlessly reconcile over the top of one another. That is, just one target resource will be created and then it will be modified by each conflicting MR over-and-over.
2. Deleting any of those MRs will immediately delete the target resource completely. The target resource will then be recreated when the next MR comes around the reconcilliation loop.

### How can we reproduce it?

Apply the following, then watch the AWS API (or console) and see the DisplayName of the topic change every few seconds.
```
apiVersion: notification.aws.crossplane.io/v1alpha1
kind: SNSTopic
metadata:
  name: sns1
spec:
  deletionPolicy: Delete
  forProvider:
    deliveryPolicy: ""
    displayName: name1
    name: topicname
    region: eu-west-1
  providerConfigRef:
    name: <yourrefhere>
---

apiVersion: notification.aws.crossplane.io/v1alpha1
kind: SNSTopic
metadata:
  name: sns2
spec:
  deletionPolicy: Delete
  forProvider:
    deliveryPolicy: ""
    displayName: name2
    name: topicname
    region: eu-west-1
  providerConfigRef:
    name: <yourrefhere>
---
```

### What environment did it happen in?
Crossplane version: 1.3.0
AWS provider: 0.19
Kubernetes: 1.20 (EKS)
