### ISSUE TITLE
Include ApiGatewayDomainName and HostedZoneId in apigatewayv2 DomainName status

### ISSUE THREAD

**Issue by aolvictim** [crossplane-contrib/provider-aws#826]
### What problem are you facing?
After creating a `DomainName` in `apigatewayv2.aws.crossplane.io`, the `status` of the created resource does not contain `ApiGatewayDomainName` and `HostedZoneId` from AWS. Those fields are needed in order to add records in Route 53 for the `DomainName`

I created a `DomainName` with the following template:

```yaml
apiVersion: apigatewayv2.aws.crossplane.io/v1alpha1
  kind: DomainName
    metadata:
      name: foo.example.com
    spec:
      forProvider:
        region: us-west-2
        domainNameConfigurations:
        - certificateARN: 'arn:YYYYYYY'
          endpointType: REGIONAL
          securityPolicy: TLS_1_2
```

The resulting resource only has part of the info returned from AWS:
```yaml
...
status:
  atProvider:
    apiMappingSelectionExpression: $request.basepath
    domainName: foo.example.com
...
```

When you use aws cli to get the domain names, the result is like:

```json
{
    "Items": [
        {
            "ApiMappingSelectionExpression": "$request.basepath",
            "DomainName": "foo.example.com",
            "DomainNameConfigurations": [
                {
                    "ApiGatewayDomainName": "d-xxxxxxxx.execute-api.eu-west-2.amazonaws.com",   <-- Need this
                    "CertificateArn": "arn:YYYYYYY",
                    "DomainNameStatus": "AVAILABLE",
                    "EndpointType": "REGIONAL",
                    "HostedZoneId": "ZABCDEFG",   <-- and this
                    "SecurityPolicy": "TLS_1_2"
                }
            ]
        }
    ]
}
```

### How could Crossplane help solve your problem?
Include those fields in the resource so it's like

```yaml
...
status:
  atProvider:
    apiMappingSelectionExpression: $request.basepath
    domainName: foo.example.com
    apiGatewayDomainName: d-xxxxxxxx.execute-api.eu-west-2.amazonaws.com  # Add this
    hostedZoneId: ZABCDEFG # and this
...
```

Then I can create `ResourceRecordSet` in `route53.aws.crossplane.io` with those info.
