### ISSUE TITLE
RDSInstance is in synced:false state because `Cannot upgrade postgres from 12.7 to 12.5`

### ISSUE THREAD

**Issue by shubhindia** [crossplane-contrib/provider-aws#832]
### What happened?

We are using crossplane to manage our RDSInstances in AWS. We use argo-cd to get the objects synced. Now when we deployed RDSInstance in crossplane we used posgres `engineVersion: 12` and (`autoMinorVersionUpgrade: true`) we didn't mention this value because according to the documetation, its default value is true,  so the expected behaviour is, it will upgrade the RDS to the latest available minor version. But after upgrading, crossplane replaced engineVersion with 12.5 which is the version on which the RDS instance was initially on. We are unable to pinpoint why crossplane is trying to downgrade the instance version.
P.S. - I don't think crossplane should update the minor-version in spec. That might cause unnecessary reconciliations 

### How can we reproduce it?
```
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: some-rdsinstance
spec:
  deletionPolicy: Orphan
  forProvider:
    allocatedStorage: 100
    availabilityZone: us-west-2b
    backupRetentionPeriod: 7
    dbInstanceClass: db.m5.large
    dbParameterGroupName: default
    dbSubnetGroupName: XXXX-XXXX-XXXX
    deletionProtection: true
    enablePerformanceInsights: true
    engine: postgres
    engineVersion: '12'
    masterUsername: master_user
    multiAZ: false
    performanceInsightsRetentionPeriod: 7
    preferredBackupWindow: '06:21-06:51'
    preferredMaintenanceWindow: 'mon:00:00-mon:01:00'
    publiclyAccessible: true
    region: us-west-2
    storageEncrypted: true
    storageType: gp2
    tags:
      - key: crossplane-kind
        value: rdsinstance.database.aws.crossplane.io
      - key: crossplane-name
        value: master-postgres-instance
      - key: crossplane-providerconfig
        value: default
    vpcSecurityGroupIds:
      - XXXX-XXXX
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: master.rds-admin-connection
    namespace: master

```

### What environment did it happen in?
Crossplane version:  crossplane-1.3.1
Kubernetes version: v1.19.7
