### ISSUE TITLE
IAMRole diff is to picky which results in unnecessary reconciling

### ISSUE THREAD

**Issue by eloo** [crossplane-contrib/provider-aws#932]
### What happened?

When a IAMRole is created with a assumePolicyDocument which is transformed by AWS crossplane will reconcile it the whole time. 

### How can we reproduce it?

Deploy a role like this
```
apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  annotations:
    crossplane.io/external-name: test-role
  name: test-role
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Federated":"arn:aws:iam::account-id:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/oidc-id"},"Action":["sts:AssumeRoleWithWebIdentity"],"Condition":{"StringLike":{"oidc.eks.eu-central-1.amazonaws.com/id/oidc-id:sub":"system:serviceaccount:dev:config-server"}}}]}'
    maxSessionDuration: 3600
    path: /
    permissionsBoundary: arn:aws:iam::account-id:policy/acs/acs-boundary-policy
  providerConfigRef:
    name: aws-provider-config
```

Then you will see in the logs that this role is reconciled the whole time. 
If you check the diff you will see something like this

```
 assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Federated":"arn:aws:iam::account-id:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/oidc-id"},"Action":"sts:AssumeRoleWithWebIdentity","Condition":{"StringLike":{"oidc.eks.eu-central-1.amazonaws.com/id/oidc-id:sub":"system:serviceaccount:dev:config-server"}}}]}'
```
should be

```
 assumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Federated":"arn:aws:iam::account-id:oidc-provider/oidc.eks.eu-central-1.amazonaws.com/id/oidc-id"},"Action":["sts:AssumeRoleWithWebIdentity"],"Condition":{"StringLike":{"oidc.eks.eu-central-1.amazonaws.com/id/oidc-id:sub":"system:serviceaccount:dev:config-server"}}}]}'
```

If you take a deeper look you will see that the calculated diff the bracket [ ] at the action value. 

So the problem is that 
```
"Action":["sts:AssumeRoleWithWebIdentity"]
```
will be transformed to
```
"Action":"sts:AssumeRoleWithWebIdentity"
```

What environment did it happen in?
Crossplane version: crossplane 1.5.0
crossplane/provider-aws:v0.20.0

Thanks
